#!/bin/bash
BASE_DIR=../../../alien-ofelia-conet-ccnx
SERVER=192.168.64.1
PORT=9699
NID=ccn:/example/mb1
NID_CCNX=ccn:/example
EX_NAME=$(pwd | awk -F "/" '{print $NF}')

while [ $# -gt 0 ]; do
    if [ "$1" = "-s" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
       SERVER=$2
      shift 2
    elif [ "$1" = "-nx" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      NID_CCNX=$2
      shift 2
    elif [ "$1" = "-p" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      PORT=$2
      shift 2
    elif [ "$1" = "-n" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      EX_NAME=$2
      shift 2
    else
      break
    fi
done

export CCND_LOG=./log.$EX_NAME
export CCN_LOCAL_SOCKNAME=/tmp/.sock.ccnx.$EX_NAME

if  [ "$(pidof client-ccnd)" ];then
     echo "Pid CCND: $(pidof client-ccnd)"	
else
    echo "Avvio CCND e attendo 10 sec"
     ./$EX_NAME-ccnd 1 1 0 0 0  & #> /dev/null 2>&1 &
     sleep 10
fi


$BASE_DIR/csrc/libexec/ccndc add $NID_CCNX udp $SERVER $PORT && $BASE_DIR/csrc/libexec/ccndc add ccnx:/ udp $SERVER
$BASE_DIR/csrc/cmd/ccncatchunks2 -d -p 20 -s $NID
