#!/bin/bash
BASE_DIR=/root/alien-ofelia-conet-ccnx
SERVER=192.168.64.2
PORT=9699

BASE_NAME=example2
NAME=mb2_
N_CONTENT=20

i="0"
while [ "$i" -lt "$N_CONTENT" ]; do

NID[$i]=ccn:/$BASE_NAME/$NAME$i
    i=$[$i+1]
done

RANGE=20
#NID[17]=ccn:/example2/mb2_17
#NID[18]=ccn:/example2/mb2_18
#NID[19]=ccn:/example2/mb2_19

NID_CCNX=ccn:/$BASE_NAME

TIME=5

while [ $# -gt 0 ]; do
    if [ "$1" = "-s" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
       SERVER=$2
      shift 2
    elif [ "$1" = "-nx" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      NID_CCNX=$2
      shift 2
    elif [ "$1" = "-p" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      PORT=$2
      shift 2
    elif [ "$1" = "-t" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      TIME=$2
     shift 2
    elif [ "$1" = "-n" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      NID=$2
      shift 2
    else
      break
    fi
done

kill $(pidof ccnd) > /dev/null 2>&1

i="0"
#while [ "$i" -lt "15" ]; do
while [ 1 ]; do
     if  [ "$(pidof ccnd)" ];then
     	echo "Old CCND pid: $(pidof ccnd)"	
#     	sudo kill $(pidof ccnd)
#     fi
     else #
        $BASE_DIR/csrc/ccnd/ccnd 1 1 0 0 0  > /dev/null 2>&1 &
        echo "Attendo avvio di ccnd "
        sleep 10
        echo "New CCND pid: $(pidof ccnd)" 
     fi	#
#     number=$RANDOM
#     let "number %= $RANGE"
#	time1=$(($(date +%s%N)/1000000))
     $BASE_DIR/csrc/libexec/ccndc add $NID_CCNX udp $SERVER $PORT && $BASE_DIR/csrc/libexec/ccndc add ccnx:/ udp $SERVER 
#     $BASE_DIR/csrc/cmd/ccncatchunks2 -d -p 20 -s ${NID[$number]} &
     echo ${NID[($i % $RANGE)]}
     $BASE_DIR/csrc/cmd/ccncatchunks2 -d -p 20 -s ${NID[($i % $RANGE)]} &
#	time2=$(($(date +%s%N)/1000000))
#	timediff=$(( time2-time1 ))
#	echo $timediff
     sleep $TIME
     if  [ "$(pidof ccncatchunks2)" ];then  
         kill $(pidof ccnd) > /dev/null 2>&1
         kill $(pidof ccncatchunks2) > /dev/null 2>&1
         echo "((((((((((((((((( sveglia!!! )))))))))))))))))))"
     fi	 
     echo "@@@@ risveglio @@@@"
     i=$[$i+1]
     if  [ "$i" -eq "20" ]; then
	echo "========================================="
     fi	
done
