#!/bin/bash
BASE_DIR=/root/alien-ofelia-conet-ccnx
SERVER=192.168.1.8
PORT=9699

RANGE=15
NID[0]=ccn:/example/mb0
NID[1]=ccn:/example/mb1
NID[2]=ccn:/example/mb2
NID[3]=ccn:/example/mb3
NID[4]=ccn:/example/mb4
NID[5]=ccn:/example/mb5
NID[6]=ccn:/example/mb6
NID[7]=ccn:/example/mb7
NID[8]=ccn:/example/mb8
NID[9]=ccn:/example/mb9
NID[10]=ccn:/example/mb10
NID[11]=ccn:/example/mb11
NID[12]=ccn:/example/mb12
NID[13]=ccn:/example/mb13
NID[14]=ccn:/example/mb14

NID_CCNX=ccn:/example
TIME=10

while [ $# -gt 0 ]; do
    if [ "$1" = "-s" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
       SERVER=$2
      shift 2
    elif [ "$1" = "-nx" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      NID_CCNX=$2
      shift 2
    elif [ "$1" = "-p" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      PORT=$2
      shift 2
    elif [ "$1" = "-t" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      TIME=$2
     shift 2
    elif [ "$1" = "-n" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      NID=$2
      shift 2
    else
      break
    fi
done

kill $(pidof ccnd) > /dev/null 2>&1

i="0"
#while [ "$i" -lt "15" ]; do
while [ 1 ]; do
     if  [ "$(pidof ccnd)" ];then
     	echo "Old CCND pid: $(pidof ccnd)"	
#     	sudo kill $(pidof ccnd)
#     fi
     else #
        $BASE_DIR/csrc/ccnd/ccnd 1 1 0 0 0  > /dev/null 2>&1 &
        echo "Attendo avvio di ccnd "
        sleep 10
        echo "New CCND pid: $(pidof ccnd)" 
     fi	#
#     number=$RANDOM
#     let "number %= $RANGE"
     $BASE_DIR/csrc/libexec/ccndc add $NID_CCNX udp $SERVER $PORT && $BASE_DIR/csrc/libexec/ccndc add ccnx:/ udp $SERVER 
#     $BASE_DIR/csrc/cmd/ccncatchunks2 -d -p 20 -s ${NID[$number]} &
     echo ${NID[($i % $RANGE)]}
     $BASE_DIR/csrc/cmd/ccncatchunks2 -d -p 20 -s ${NID[($i % $RANGE)]} &
     sleep $TIME
     if  [ "$(pidof ccncatchunks2)" ];then  
         kill $(pidof ccnd) > /dev/null 2>&1
         kill $(pidof ccncatchunks2) > /dev/null 2>&1
         echo "((((((((((((((((( sveglia!!! )))))))))))))))))))"
     fi	 
     echo "@@@@ risveglio @@@@"
     i=$[$i+1]
done
