$(making conetImpl a c implementation of conet functionalities)

#where do you want to put header files?
INCLUDE_FOLDER=../include #forse non si usa

#where do you want to put libconet.a?
LIB_FOLDER=../lib

CCNX_FOLDER=../../ccnx401base-cp-raw 
CCNX_INCLUDE_FOLDER=../../ccnx401base-cp-raw/csrc/include
CCNX_LIB_FOLDER=../../ccnx401base-cp-raw/lib

#src folder of ccnx based conet implementation
CONET_CCNX_SRC=../../ccnx401base-cp-raw/csrc/lib/conet

SRC_FOLDER=../src #forse non si usa


libconetccnx.so: conet.o conet_net.o conet_packet.o conet_timer.o
	gcc -shared -fPIC -o $(LIB_FOLDER)/libconetccnx.so $(LIB_FOLDER)/conet.o $(LIB_FOLDER)/conet_net.o $(LIB_FOLDER)/conet_packet.o $(LIB_FOLDER)/conet_timer.o -L$(CCNX_LIB_FOLDER) -lccn

####################### CONET-ccnx-based implementation

	
conet.o: $(CONET_CCNX_SRC)/conet.c $(CCNX_INCLUDE_FOLDER)/conet/conet.h
	gcc -w -c -g $(CONET_CCNX_SRC)/conet.c -o $(LIB_FOLDER)/conet.o -fPIC -I$(CCNX_INCLUDE_FOLDER) -L$(CCNX_LIB_FOLDER) -lccn

conet_net.o: $(CONET_CCNX_SRC)/conet_net.c $(CCNX_INCLUDE_FOLDER)/conet/conet_net.h
	gcc -w -c -g $(CONET_CCNX_SRC)/conet_net.c -o $(LIB_FOLDER)/conet_net.o -fPIC -I$(CCNX_INCLUDE_FOLDER)/conet -L$(CCNX_LIB_FOLDER) -lccn

conet_packet.o: $(CONET_CCNX_SRC)/conet_packet.c $(CCNX_INCLUDE_FOLDER)/conet/conet_packet.h
	gcc -w -c -g $(CONET_CCNX_SRC)/conet_packet.c -o $(LIB_FOLDER)/conet_packet.o -fPIC -I$(CCNX_INCLUDE_FOLDER) -L$(CCNX_LIB_FOLDER) -lccn
	
#conet_test.o: $(CONET_CCNX_SRC)/conet_test.c $(CCNX_INCLUDE_FOLDER)/conet/conet_test.h
#	gcc -w -c -g $(CONET_CCNX_SRC)/conet_test.c -o $(LIB_FOLDER)/conet_test.o -fPIC -I$(CCNX_INCLUDE_FOLDER) -L$(CCNX_LIB_FOLDER) -lccn
	
conet_timer.o: $(CONET_CCNX_SRC)/conet_timer.c $(CCNX_INCLUDE_FOLDER)/conet/conet_timer.h
	gcc -w -c -g $(CONET_CCNX_SRC)/conet_timer.c -o $(LIB_FOLDER)/conet_timer.o -fPIC -I$(CCNX_INCLUDE_FOLDER) -L$(CCNX_LIB_FOLDER) -lccn
