#!/bin/bash
CHUNK_SIZE=4096
#FILE=testfile10MB
FILE[0]=testfile200K
FILE[1]=testfile200K
FILE[2]=testfile200K
FILE[3]=testfile200K
FILE[4]=testfile200K
N_FILES=5

ICNID=ccn:/example2/mb2_ #.. il numero N_CONTENT
N_CONTENT=20
#FILE2=testfile10K
#ICNID2=ccn:/example/mb2
BASE_DIR=../../../../alien-ofelia-conet-ccnx

#REP_DIR and FILE_DIR are relative to BASE_DIR
REP_DIR=ccnrep
FILE_DIR=content-files


if [ ! -n "$1" ]; then
  echo "Uso parametri di default"
fi

while [ $# -gt 0 ]; do
    if [ "$1" = "-cs" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
       CHUNK_SIZE=$2
      shift 2
    elif [ "$1" = "-f" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      FILE=$2
      shift 2
    elif [ "$1" = "-n" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi  
      EX_NAME=$2
      #N_CONTENT=$2
      shift 2
    else
      break
    fi
done

export CCND_LOG=./log.$EX_NAME
export CCN_LOCAL_SOCKNAME=/tmp/.sock.ccnx.$EX_NAME

if  [ "$(pidof $EX_NAME-ccnd)" ];then
     echo "Pid CCND: $(pidof $EX_NAME-ccnd)"        
else
     echo "Avvio CCND e attendo 10 sec"
     #$BASE_DIR/csrc/ccnd/ccnd 0 0 0 0 0  > /dev/null 2>&1 &
     ./$EX_NAME-ccnd 0 0 0 0 0  > /dev/null 2>&1 &
     sleep 10
fi

#cd $BASE_DIR/$REP_DIR
cd ./repo
$BASE_DIR/csrc/ccnr/ccnr &
i="0"
while [ "$i" -lt "$N_CONTENT" ]; do
    let "number= $i"
    let "number %= $N_FILES"	
    echo "name: $ICNID$i"
    $BASE_DIR/javasrc/tools/ccnputfile -javaopts -D"ccn.lib.blocksize=$CHUNK_SIZE" -unversioned $ICNID$i $BASE_DIR/$FILE_DIR/${FILE[$number]}
    sleep 8
    i=$[$i+1]
done

