#!/bin/bash
#it loads one file 
#it can load two files if some lines will be uncommented

CHUNK_SIZE=4096
#FILE=testfile10MB
FILE=testfile1K
ICNID=ccn:/example/mb1
#FILE2=testfile10K
#ICNID2=ccn:/example/mb2
BASE_DIR=../../../../alien-ofelia-conet-ccnx

#REP_DIR and FILE_DIR are relative to BASE_DIR
REP_DIR=ccnrep
FILE_DIR=content-files

EX_NAME=$(pwd | awk -F "/" '{print $NF}')

if [ ! -n "$1" ]; then
  echo "Uso parametri di default"
fi


while [ $# -gt 0 ]; do
    if [ "$1" = "-cs" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
       CHUNK_SIZE=$2
      shift 2
    elif [ "$1" = "-f" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi
      FILE=$2
      shift 2
    elif [ "$1" = "-n" ]; then
      if [ $# -lt 2 ]; then
        usage
      fi  
      EX_NAME=$2
      shift 2
    else
      break
    fi
done

export CCND_LOG=./log.$EX_NAME
export CCN_LOCAL_SOCKNAME=/tmp/.sock.ccnx.$EX_NAME

if  [ "$(pidof $EX_NAME-ccnd)" ];then
     echo "Pid CCND: $(pidof $EX_NAME-ccnd)"        
else
     echo "Avvio CCND e attendo 10 sec"
     ./$EX_NAME-ccnd 0 0 0 0 0  &#> /dev/null 2>&1 &
     sleep 10
fi

cd ./repo
$BASE_DIR/csrc/ccnr/ccnr &
$BASE_DIR/javasrc/tools/ccnputfile -javaopts -D"ccn.lib.blocksize=$CHUNK_SIZE" -unversioned $ICNID $BASE_DIR/$FILE_DIR/$FILE
#sleep 8
#$BASE_DIR/javasrc/tools/ccnputfile -javaopts -D"ccn.lib.blocksize=$CHUNK_SIZE" -unversioned $ICNID2 $BASE_DIR/$FILE_DIR/$FILE2

