.TH "bug" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 
 
.IP "\fBGlobal \fBccn_name_from_uri\fP(struct \fBccn_charbuf\fP *c, const char *uri) \fP" 1c
XXX - need to error out on other uri schemes 
.PP
.PP
 
.IP "\fBGlobal \fBccnbx\fP(const char *path, const char *selector, int options) \fP" 1c
This would be confused by attributes 
.PP

