.TH "ccn_btree_content_entry" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_btree_content_entry \- 
.PP
Logical structure of the entry within a leaf node.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_btree_content_payload\fP \fBce\fP"
.br
.ti -1c
.RI "struct \fBccn_btree_entry_trailer\fP \fBtrailer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logical structure of the entry within a leaf node. 
.PP
Definition at line 54 of file btree_content.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBccn_btree_content_payload\fP \fBccn_btree_content_entry::ce\fP"
.PP
Definition at line 55 of file btree_content.h.
.SS "struct \fBccn_btree_entry_trailer\fP \fBccn_btree_content_entry::trailer\fP"
.PP
Definition at line 56 of file btree_content.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
