cmd/ccn_fetch_test.c
NAME
cmd/ccn_fetch_test.c -
Provides a test platform for ccn_fetch.
SYNOPSIS
Defines
#define LOCAL_BUF_MAX 20000
#define MinMilliSleep 2
#define MyAlloc(NNN, TTT) (TTT *) calloc(NNN, sizeof(TTT))
Typedefs
typedef struct ccn_charbuf * MyCharbuf
typedef char * string
typedef struct TestElemStruct * TestElem
Functions
static uint64_t GetCurrentTime (void)
static double DeltaTime (uint64_t mt1, uint64_t mt2)
static void MilliSleep (uint64_t n)
static int retErr (string msg)
static TestElem NewElem (struct MyParms *p)
static TestElem ElemDone (TestElem e)
static int runTest (struct MyParms *p)
int main (int argc, string *argv)
Variables
static char * help
Detailed Description
Provides a test platform for ccn_fetch.
Copyright (C) 2011 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_fetch_test.c.
Define Documentation
#define LOCAL_BUF_MAX 20000
Definition at line 38 of file ccn_fetch_test.c.
Referenced by NewElem().
#define MinMilliSleep 2
Definition at line 69 of file ccn_fetch_test.c.
Referenced by MilliSleep().
#define MyAlloc(NNN, TTT) (TTT *) calloc(NNN, sizeof(TTT))
Definition at line 82 of file ccn_fetch_test.c.
Referenced by NewElem().
Typedef Documentation
typedef struct ccn_charbuf* MyCharbuf
Definition at line 40 of file ccn_fetch_test.c.
typedef char* string
Definition at line 41 of file ccn_fetch_test.c.
typedef struct TestElemStruct* TestElem
Definition at line 91 of file ccn_fetch_test.c.
Function Documentation
static double DeltaTime (uint64_t mt1, uint64_t mt2) [static]
Definition at line 64 of file ccn_fetch_test.c.
Referenced by ElemDone().
static TestElem ElemDone (TestElem e) [static]
Definition at line 142 of file ccn_fetch_test.c.
Referenced by runTest().
static uint64_t GetCurrentTime (void) [static]
Definition at line 56 of file ccn_fetch_test.c.
Referenced by ElemDone(), and NewElem().
int main (int argc, string * argv)
Definition at line 235 of file ccn_fetch_test.c.
static void MilliSleep (uint64_t n) [static]
Definition at line 71 of file ccn_fetch_test.c.
Referenced by runTest().
static TestElem NewElem (struct MyParms * p) [static]
Definition at line 104 of file ccn_fetch_test.c.
Referenced by runTest().
static int retErr (string msg) [static]
Definition at line 85 of file ccn_fetch_test.c.
Referenced by main(), and runTest().
static int runTest (struct MyParms * p) [static]
Definition at line 158 of file ccn_fetch_test.c.
Referenced by main().
Variable Documentation
char* help [static]"Initial value:
 'usage: ccn_fetch_test {switch | ccnName}*\n\
    -help help\n\
    -out XXX sets output file to XXX (default: stdout)\n\
    -mb NNN ses NNN as max number of buffers to use (default: 4)\n\
    -d enables debug output (default: none)\n\
    -f use fixed-size segments (default: variable)\n\
    -nv no resolve version (default: CCN_V_HIGH)\n'
Definition at line 226 of file ccn_fetch_test.c.
Referenced by main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.