.TH "ccn_btree_internal_entry" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccn_btree_internal_entry \- 
.PP
Logical structure of the entry within an internal (non-leaf) node.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_btree_internal_payload\fP \fBie\fP"
.br
.ti -1c
.RI "struct \fBccn_btree_entry_trailer\fP \fBtrailer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Logical structure of the entry within an internal (non-leaf) node. 
.PP
Definition at line 210 of file btree.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBccn_btree_internal_payload\fP \fBccn_btree_internal_entry::ie\fP"
.PP
Definition at line 211 of file btree.h.
.SS "struct \fBccn_btree_entry_trailer\fP \fBccn_btree_internal_entry::trailer\fP"
.PP
Definition at line 212 of file btree.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
