lib/ccn_schedule.c
NAME
lib/ccn_schedule.c -
Support for scheduling events.
SYNOPSIS
Typedefs
typedef uintptr_t heapmicros
Use this unsigned type to keep track of time in the heap.
Functions
static void update_epoch (struct ccn_schedule *sched)
static void update_time (struct ccn_schedule *sched)
struct ccn_schedule * ccn_schedule_create (void *clienth, const struct ccn_gettime *ccnclock)
void ccn_schedule_destroy (struct ccn_schedule **schedp)
struct ccn_gettime * ccn_schedule_get_gettime (struct ccn_schedule *schedp)
static void heap_insert (struct ccn_schedule_heap_item *heap, heapmicros micros, struct ccn_scheduled_event *ev, int h, int n)
static void heap_sift (struct ccn_schedule_heap_item *heap, int n)
static struct ccn_scheduled_event * reschedule_event (struct ccn_schedule *sched, int micros, struct ccn_scheduled_event *ev)
struct ccn_scheduled_event * ccn_schedule_event (struct ccn_schedule *sched, int micros, ccn_scheduled_action action, void *evdata, intptr_t evint)
static int ccn_schedule_cancelled_event (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
int ccn_schedule_cancel (struct ccn_schedule *sched, struct ccn_scheduled_event *ev)
Cancel a scheduled event.
static void ccn_schedule_run_next (struct ccn_schedule *sched)
int ccn_schedule_run (struct ccn_schedule *sched)
Variables
static const heapmicros epochmax = ((heapmicros)(~0))/2
Detailed Description
Support for scheduling events.
Part of the CCNx C Library.
Copyright (C) 2009-2012 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_schedule.c.
Typedef Documentation
typedef uintptr_t heapmicros
Use this unsigned type to keep track of time in the heap. 32 bits can work, but 64 bits are preferable.
Definition at line 31 of file ccn_schedule.c.
Function Documentation
int ccn_schedule_cancel (struct ccn_schedule * sched, struct ccn_scheduled_event * ev)
Cancel a scheduled event. Cancels the event (calling action with CCN_SCHEDULE_CANCEL set)
Returns:
0 if OK, or -1 if this is not possible.
Definition at line 268 of file ccn_schedule.c.
Referenced by ccnd_internal_client_stop(), ccnr_direct_client_stop(), ccnr_internal_client_stop(), ccns_close(), content_queue_destroy(), destroyCompareData(), finalize_interest(), kickCompare(), kickUpdate(), propagate_interest(), r_sendq_content_queue_destroy(), resetDiffData(), resetUpdateData(), start_round(), strategy_settimer(), sync_diff_stop(), and update_npe_children().
static int ccn_schedule_cancelled_event (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 255 of file ccn_schedule.c.
Referenced by ccn_schedule_cancel().
struct ccn_schedule* ccn_schedule_create (void * clienth, const struct ccn_gettime * ccnclock) [read]
Definition at line 100 of file ccn_schedule.c.
Referenced by ccnd_create(), ccns_open(), main(), and r_init_create().
void ccn_schedule_destroy (struct ccn_schedule ** schedp)
Definition at line 116 of file ccn_schedule.c.
Referenced by ccn_destroy(), ccnd_destroy(), incoming_content(), main(), and r_init_destroy().
struct ccn_scheduled_event* ccn_schedule_event (struct ccn_schedule * sched, int micros, ccn_scheduled_action action, void * evdata, intptr_t evint) [read]
Definition at line 234 of file ccn_schedule.c.
Referenced by adjacency_timed_reset(), age_forwarding_needed(), ccnd_face_status_change(), ccnd_init_face_guid_cob(), ccnd_internal_client_has_somthing_to_say(), ccnd_internal_client_start(), ccnd_register_adjacency(), ccnd_req_guest(), ccnr_direct_client_start(), ccnr_face_status_change(), ccnr_internal_client_start(), clean_needed(), face_send_queue_insert(), kickCompare(), kickHeartBeat(), kickUpdate(), main(), propagate_interest(), r_proto_policy_complete(), r_sendq_face_send_queue_insert(), r_store_index_needs_cleaning(), r_store_init(), r_store_set_content_timer(), reap_enumerations_needed(), reap_needed(), schedule_adjacency_negotiation(), set_content_timer(), start_round(), strategy_settimer(), SyncStartHeartbeat(), SyncUpdateRoot(), update_npe_children(), and update_rtt().
struct ccn_gettime* ccn_schedule_get_gettime (struct ccn_schedule * schedp) [read]
Definition at line 142 of file ccn_schedule.c.
int ccn_schedule_run (struct ccn_schedule * sched)
Definition at line 317 of file ccn_schedule.c.
Referenced by ccn_run(), ccnd_run(), main(), r_dispatch_run(), and r_init_create().
static void ccn_schedule_run_next (struct ccn_schedule * sched) [static]
Definition at line 283 of file ccn_schedule.c.
Referenced by ccn_schedule_run().
static void heap_insert (struct ccn_schedule_heap_item * heap, heapmicros micros, struct ccn_scheduled_event * ev, int h, int n) [static]
Definition at line 152 of file ccn_schedule.c.
Referenced by reschedule_event().
static void heap_sift (struct ccn_schedule_heap_item * heap, int n) [static]
Definition at line 175 of file ccn_schedule.c.
Referenced by ccn_schedule_run_next().
static struct ccn_scheduled_event* reschedule_event (struct ccn_schedule * sched, int micros, struct ccn_scheduled_event * ev) [static, read]
Definition at line 199 of file ccn_schedule.c.
Referenced by ccn_schedule_event(), and ccn_schedule_run_next().
static void update_epoch (struct ccn_schedule * sched) [static]
Definition at line 61 of file ccn_schedule.c.
Referenced by reschedule_event(), and update_time().
static void update_time (struct ccn_schedule * sched) [static]
Definition at line 75 of file ccn_schedule.c.
Referenced by ccn_schedule_create(), ccn_schedule_event(), and ccn_schedule_run().
Variable Documentation
const heapmicros epochmax = ((heapmicros)(~0))/2 [static]
Definition at line 32 of file ccn_schedule.c.
Referenced by reschedule_event(), and update_time().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.