lib/ccn_buf_decoder.c
NAME
lib/ccn_buf_decoder.c -
Support for Interest and ContentObject decoding.
SYNOPSIS
Functions
struct ccn_buf_decoder * ccn_buf_decoder_start (struct ccn_buf_decoder *d, const unsigned char *buf, size_t size)
void ccn_buf_advance (struct ccn_buf_decoder *d)
int ccn_buf_match_dtag (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
int ccn_buf_match_some_dtag (struct ccn_buf_decoder *d)
int ccn_buf_match_some_blob (struct ccn_buf_decoder *d)
int ccn_buf_match_blob (struct ccn_buf_decoder *d, const unsigned char **bufp, size_t *sizep)
int ccn_buf_match_udata (struct ccn_buf_decoder *d, const char *s)
int ccn_buf_match_attr (struct ccn_buf_decoder *d, const char *s)
void ccn_buf_check_close (struct ccn_buf_decoder *d)
Enter an error state if element closer not found.
int ccn_buf_advance_past_element (struct ccn_buf_decoder *d)
int ccn_parse_required_tagged_BLOB (struct ccn_buf_decoder *d, enum ccn_dtag dtag, int minlen, int maxlen)
int ccn_parse_optional_tagged_BLOB (struct ccn_buf_decoder *d, enum ccn_dtag dtag, int minlen, int maxlen)
uintmax_t ccn_parse_required_tagged_binary_number (struct ccn_buf_decoder *d, enum ccn_dtag dtag, int minlen, int maxlen)
uintmax_t ccn_parse_optional_tagged_binary_number (struct ccn_buf_decoder *d, enum ccn_dtag dtag, int minlen, int maxlen, uintmax_t default_value)
int ccn_parse_required_tagged_UDATA (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
int ccn_parse_optional_tagged_UDATA (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
int ccn_parse_tagged_string (struct ccn_buf_decoder *d, enum ccn_dtag dtag, struct ccn_charbuf *store)
Parses a ccnb-encoded element expected to contain a UDATA string.
int ccn_parse_Name (struct ccn_buf_decoder *d, struct ccn_indexbuf *components)
Parses a ccnb-encoded name.
int ccn_parse_PublisherID (struct ccn_buf_decoder *d, struct ccn_parsed_interest *pi)
static int ccn_parse_optional_Any_or_Bloom (struct ccn_buf_decoder *d)
int ccn_parse_Exclude (struct ccn_buf_decoder *d)
int ccn_parse_nonNegativeInteger (struct ccn_buf_decoder *d)
int ccn_parse_uintmax (struct ccn_buf_decoder *d, uintmax_t *result)
Parse a potentially large non-negative integer.
int ccn_parse_timestamp (struct ccn_buf_decoder *d)
int ccn_parse_required_tagged_timestamp (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
int ccn_parse_optional_tagged_nonNegativeInteger (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
int ccn_fetch_tagged_nonNegativeInteger (enum ccn_dtag tt, const unsigned char *buf, size_t start, size_t stop)
int ccn_parse_interest (const unsigned char *msg, size_t size, struct ccn_parsed_interest *interest, struct ccn_indexbuf *components)
static int ccn_parse_KeyName (struct ccn_buf_decoder *d, struct parsed_KeyName *x)
static int ccn_parse_Signature (struct ccn_buf_decoder *d, struct ccn_parsed_ContentObject *x)
static int ccn_parse_SignedInfo (struct ccn_buf_decoder *d, struct ccn_parsed_ContentObject *x)
int ccn_parse_ContentObject (const unsigned char *msg, size_t size, struct ccn_parsed_ContentObject *x, struct ccn_indexbuf *components)
int ccn_ref_tagged_BLOB (enum ccn_dtag tt, const unsigned char *buf, size_t start, size_t stop, const unsigned char **presult, size_t *psize)
int ccn_ref_tagged_string (enum ccn_dtag dtag, const unsigned char *buf, size_t start, size_t stop, const unsigned char **presult, size_t *psize)
Produce a pointer and length for the string in a ccnb-encoded tagged element containing a UDATA string.
static struct ccn_buf_decoder * ccn_buf_decoder_start_at_components (struct ccn_buf_decoder *d, const unsigned char *buf, size_t buflen)
int ccn_content_get_value (const unsigned char *data, size_t data_size, const struct ccn_parsed_ContentObject *content, const unsigned char **value, size_t *value_size)
int ccn_compare_names (const unsigned char *a, size_t asize, const unsigned char *b, size_t bsize)
int ccn_parse_LinkAuthenticator (struct ccn_buf_decoder *d, struct ccn_parsed_Link *pl)
int ccn_parse_Link (struct ccn_buf_decoder *d, struct ccn_parsed_Link *link, struct ccn_indexbuf *components)
int ccn_parse_Collection_start (struct ccn_buf_decoder *d)
int ccn_parse_Collection_next (struct ccn_buf_decoder *d, struct ccn_parsed_Link *link, struct ccn_indexbuf *components)
Detailed Description
Support for Interest and ContentObject decoding.
Part of the CCNx C Library.
Copyright (C) 2008-2012 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file ccn_buf_decoder.c.
Function Documentation
void ccn_buf_advance (struct ccn_buf_decoder * d)
Definition at line 40 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), appendComponents(), appendExclusions(), ccn_append_interest_bounds(), ccn_append_link_name(), ccn_buf_advance_past_element(), ccn_buf_check_close(), ccn_buf_decoder_start_at_components(), ccn_check_namebuf(), ccn_chk_signing_params(), ccn_compare_names(), ccn_content_matches_interest(), ccn_excluded(), ccn_face_instance_parse(), ccn_fetch_tagged_nonNegativeInteger(), ccn_flatname_append_from_ccnb(), ccn_forwarding_entry_parse(), ccn_header_parse(), ccn_name_comp_get(), ccn_name_last_component_offset(), ccn_parse_Collection_start(), ccn_parse_ContentObject(), ccn_parse_Exclude(), ccn_parse_interest(), ccn_parse_KeyName(), ccn_parse_Link(), ccn_parse_LinkAuthenticator(), ccn_parse_Name(), ccn_parse_nonNegativeInteger(), ccn_parse_optional_Any_or_Bloom(), ccn_parse_optional_tagged_nonNegativeInteger(), ccn_parse_PublisherID(), ccn_parse_required_tagged_binary_number(), ccn_parse_required_tagged_BLOB(), ccn_parse_required_tagged_timestamp(), ccn_parse_required_tagged_UDATA(), ccn_parse_Signature(), ccn_parse_SignedInfo(), ccn_parse_tagged_required_uintmax(), ccn_parse_tagged_string(), ccn_parse_timestamp(), ccn_parse_uintmax(), ccn_pubid_matches(), ccn_ref_tagged_BLOB(), ccn_ref_tagged_string(), ccn_uri_append(), extract_bounds(), extractDeltas(), find_first_match_candidate(), make_template(), r_proto_check_exclude(), r_proto_initiate_key_fetch(), r_proto_parse_policy(), reportExclude(), slice_parse(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncParseComposite(), SyncParseName(), SyncParseUnsigned(), SyncPatternMatch(), SyncPrefixMatch(), and SyncRootDecodeAndAdd().
int ccn_buf_advance_past_element (struct ccn_buf_decoder * d)
Definition at line 119 of file ccn_buf_decoder.c.
Referenced by ccn_append_interest_bounds(), ccn_chk_signing_params(), ccn_flatname_append_from_ccnb(), ccn_uri_append(), and find_first_match_candidate().
void ccn_buf_check_close (struct ccn_buf_decoder * d)
Enter an error state if element closer not found.
Definition at line 108 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), appendComponents(), ccn_append_interest_bounds(), ccn_append_link_name(), ccn_buf_advance_past_element(), ccn_check_namebuf(), ccn_chk_signing_params(), ccn_compare_names(), ccn_excluded(), ccn_face_instance_parse(), ccn_fetch_tagged_nonNegativeInteger(), ccn_flatname_append_from_ccnb(), ccn_forwarding_entry_parse(), ccn_header_parse(), ccn_name_comp_get(), ccn_name_last_component_offset(), ccn_parse_Collection_next(), ccn_parse_ContentObject(), ccn_parse_Exclude(), ccn_parse_interest(), ccn_parse_KeyName(), ccn_parse_Link(), ccn_parse_LinkAuthenticator(), ccn_parse_Name(), ccn_parse_optional_Any_or_Bloom(), ccn_parse_optional_tagged_nonNegativeInteger(), ccn_parse_PublisherID(), ccn_parse_required_tagged_binary_number(), ccn_parse_required_tagged_BLOB(), ccn_parse_required_tagged_timestamp(), ccn_parse_required_tagged_UDATA(), ccn_parse_Signature(), ccn_parse_SignedInfo(), ccn_parse_tagged_required_uintmax(), ccn_parse_tagged_string(), ccn_ref_tagged_BLOB(), ccn_ref_tagged_string(), ccn_uri_append(), extract_bounds(), extractDeltas(), find_first_match_candidate(), make_template(), r_proto_check_exclude(), r_proto_initiate_key_fetch(), r_proto_parse_policy(), reportExclude(), slice_parse(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncParseComposite(), SyncParseName(), SyncParseUnsigned(), SyncPatternMatch(), SyncPrefixMatch(), and SyncRootDecodeAndAdd().
struct ccn_buf_decoder* ccn_buf_decoder_start (struct ccn_buf_decoder * d, const unsigned char * buf, size_t size) [read]
Definition at line 28 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), ccn_append_interest_bounds(), ccn_append_link_name(), ccn_buf_decoder_start_at_components(), ccn_check_namebuf(), ccn_chk_signing_params(), ccn_content_matches_interest(), ccn_excluded(), ccn_face_instance_parse(), ccn_fetch_tagged_nonNegativeInteger(), ccn_flatname_append_from_ccnb(), ccn_forwarding_entry_parse(), ccn_get_public_key(), ccn_header_parse(), ccn_interest_lifetime(), ccn_locate_key(), ccn_name_comp_get(), ccn_name_last_component_offset(), ccn_name_split(), ccn_parse_ContentObject(), ccn_parse_interest(), ccn_pubid_matches(), ccn_ref_tagged_BLOB(), ccn_ref_tagged_string(), ccn_uri_append(), ccnd_reg_uri(), extract_bounds(), extractDeltas(), extractNode(), find_first_match_candidate(), load_policy(), main(), make_template(), process_incoming_link_message(), r_proto_check_exclude(), r_proto_initiate_key_fetch(), r_proto_parse_policy(), slice_parse(), SyncCacheEntryFetch(), SyncHandleSlice(), SyncInitDecoderFromCharbufRange(), SyncInterestArrived(), SyncNodeFromBytes(), and testRootBasic().
static struct ccn_buf_decoder* ccn_buf_decoder_start_at_components (struct ccn_buf_decoder * d, const unsigned char * buf, size_t buflen) [static, read]
Definition at line 914 of file ccn_buf_decoder.c.
Referenced by ccn_compare_names().
int ccn_buf_match_attr (struct ccn_buf_decoder * d, const char * s)
Definition at line 98 of file ccn_buf_decoder.c.
int ccn_buf_match_blob (struct ccn_buf_decoder * d, const unsigned char ** bufp, size_t * sizep)
Definition at line 70 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), appendComponents(), appendExclusions(), ccn_check_namebuf(), ccn_compare_names(), ccn_content_matches_interest(), ccn_excluded(), ccn_face_instance_parse(), ccn_flatname_append_from_ccnb(), ccn_forwarding_entry_parse(), ccn_get_public_key(), ccn_header_parse(), ccn_name_comp_get(), ccn_name_last_component_offset(), ccn_parse_Name(), ccn_parse_required_tagged_binary_number(), ccn_ref_tagged_BLOB(), ccn_uri_append(), make_template(), r_proto_check_exclude(), reportExclude(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncParseComposite(), SyncParseName(), SyncPatternMatch(), and SyncPrefixMatch().
int ccn_buf_match_dtag (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 48 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), appendComponents(), appendExclusions(), ccn_append_interest_bounds(), ccn_append_link_name(), ccn_buf_decoder_start_at_components(), ccn_check_namebuf(), ccn_chk_signing_params(), ccn_compare_names(), ccn_content_matches_interest(), ccn_excluded(), ccn_face_instance_parse(), ccn_fetch_tagged_nonNegativeInteger(), ccn_flatname_append_from_ccnb(), ccn_forwarding_entry_parse(), ccn_header_parse(), ccn_locate_key(), ccn_name_comp_get(), ccn_name_last_component_offset(), ccn_parse_Collection_next(), ccn_parse_Collection_start(), ccn_parse_ContentObject(), ccn_parse_Exclude(), ccn_parse_interest(), ccn_parse_KeyName(), ccn_parse_Link(), ccn_parse_LinkAuthenticator(), ccn_parse_Name(), ccn_parse_optional_Any_or_Bloom(), ccn_parse_optional_tagged_binary_number(), ccn_parse_optional_tagged_BLOB(), ccn_parse_optional_tagged_nonNegativeInteger(), ccn_parse_optional_tagged_UDATA(), ccn_parse_PublisherID(), ccn_parse_required_tagged_binary_number(), ccn_parse_required_tagged_BLOB(), ccn_parse_required_tagged_timestamp(), ccn_parse_required_tagged_UDATA(), ccn_parse_Signature(), ccn_parse_SignedInfo(), ccn_parse_tagged_required_uintmax(), ccn_parse_tagged_string(), ccn_ref_tagged_BLOB(), ccn_ref_tagged_string(), ccn_uri_append(), extract_bounds(), extractDeltas(), find_first_match_candidate(), main(), make_template(), r_proto_check_exclude(), r_proto_initiate_key_fetch(), r_proto_parse_policy(), reportExclude(), slice_parse(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncExtractName(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncIsName(), SyncParseComposite(), SyncParseName(), SyncParseUnsigned(), SyncPatternMatch(), SyncPrefixMatch(), and SyncRootDecodeAndAdd().
int ccn_buf_match_some_blob (struct ccn_buf_decoder * d)
Definition at line 63 of file ccn_buf_decoder.c.
Referenced by ccn_buf_match_blob(), ccn_chk_signing_params(), ccn_parse_LinkAuthenticator(), ccn_parse_PublisherID(), ccn_parse_required_tagged_BLOB(), and ccn_pubid_matches().
int ccn_buf_match_some_dtag (struct ccn_buf_decoder * d)
Definition at line 56 of file ccn_buf_decoder.c.
int ccn_buf_match_udata (struct ccn_buf_decoder * d, const char * s)
Definition at line 88 of file ccn_buf_decoder.c.
int ccn_compare_names (const unsigned char * a, size_t asize, const unsigned char * b, size_t bsize)
Definition at line 942 of file ccn_buf_decoder.c.
Referenced by content_skiplist_findbefore(), namecompare(), and r_proto_start_write().
int ccn_content_get_value (const unsigned char * data, size_t data_size, const struct ccn_parsed_ContentObject * content, const unsigned char ** value, size_t * value_size)
Definition at line 929 of file ccn_buf_decoder.c.
Referenced by CallMe(), ccn_cache_key(), ccn_get_header(), ccn_guest_prefix(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), ccndc_do_face_action(), ccndc_do_prefix_action(), ccns_read_slice(), decode_message(), display_the_content(), extractDeltas(), extractNode(), handle_key(), handle_prefix_reg_reply(), incoming_content(), main(), process_test(), r_proto_initiate_key_fetch(), SyncCacheEntryFetch(), SyncNodeFromParsedObject(), and SyncPointerToContent().
int ccn_fetch_tagged_nonNegativeInteger (enum ccn_dtag tt, const unsigned char * buf, size_t start, size_t stop)
Definition at line 543 of file ccn_buf_decoder.c.
Referenced by get_outbound_faces(), r_store_set_content_timer(), and set_content_timer().
int ccn_parse_Collection_next (struct ccn_buf_decoder * d, struct ccn_parsed_Link * link, struct ccn_indexbuf * components)
Definition at line 1098 of file ccn_buf_decoder.c.
Referenced by main().
int ccn_parse_Collection_start (struct ccn_buf_decoder * d)
Definition at line 1084 of file ccn_buf_decoder.c.
Referenced by main().
int ccn_parse_ContentObject (const unsigned char * msg, size_t size, struct ccn_parsed_ContentObject * x, struct ccn_indexbuf * components)
Definition at line 814 of file ccn_buf_decoder.c.
Referenced by add_cob_exclusion(), ccn_content_matches_interest(), ccn_dispatch_message(), ccnd_answer_req(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_req_prefix_or_self_reg(), ccnd_req_unreg(), ccnr_answer_req(), decode_message(), deliver_content(), interest_handler(), load_policy(), main(), process_incoming_content(), process_test(), r_proto_policy_update(), r_store_content_field_access(), r_store_set_flatname(), start_node_fetch(), storeHandler(), SyncHandleSlice(), SyncLocalRepoFetch(), SyncPointerToContent(), and test_insert_content().
int ccn_parse_Exclude (struct ccn_buf_decoder * d)
Definition at line 368 of file ccn_buf_decoder.c.
Referenced by ccn_parse_interest().
int ccn_parse_interest (const unsigned char * msg, size_t size, struct ccn_parsed_interest * interest, struct ccn_indexbuf * components)
Definition at line 564 of file ccn_buf_decoder.c.
Referenced by append_interest_details(), ccn_age_interest(), ccn_construct_interest(), ccn_content_matches_interest(), ccn_dispatch_message(), ccn_parse_interest(), ccnd_debug_ccnb(), ccnr_debug_ccnb(), main(), process_incoming_interest(), propagate_interest(), r_lookup(), r_proto_begin_enumeration(), r_proto_start_write_checked(), testhelp_count_matches(), and update_npe_children().
static int ccn_parse_KeyName (struct ccn_buf_decoder * d, struct parsed_KeyName * x) [static]
Definition at line 687 of file ccn_buf_decoder.c.
Referenced by ccn_parse_SignedInfo().
int ccn_parse_Link (struct ccn_buf_decoder * d, struct ccn_parsed_Link * link, struct ccn_indexbuf * components)
Definition at line 1041 of file ccn_buf_decoder.c.
Referenced by ccn_parse_Collection_next(), ccn_parse_Link(), load_policy(), and main().
int ccn_parse_LinkAuthenticator (struct ccn_buf_decoder * d, struct ccn_parsed_Link * pl)
Definition at line 982 of file ccn_buf_decoder.c.
Referenced by ccn_parse_Link().
int ccn_parse_Name (struct ccn_buf_decoder * d, struct ccn_indexbuf * components)
Parses a ccnb-encoded name. Parameters:
d is the decoder
components may be NULL, otherwise is filled in with the Component boundary offsets
Returns:
the number of Components in the Name, or -1 if there is an error.
Definition at line 288 of file ccn_buf_decoder.c.
Referenced by ccn_append_link_name(), ccn_forwarding_entry_parse(), ccn_name_split(), ccn_parse_ContentObject(), ccn_parse_interest(), ccn_parse_KeyName(), ccn_parse_Link(), ccnd_reg_uri(), r_proto_initiate_key_fetch(), and slice_parse().
int ccn_parse_nonNegativeInteger (struct ccn_buf_decoder * d)
Definition at line 389 of file ccn_buf_decoder.c.
Referenced by ccn_fetch_tagged_nonNegativeInteger(), ccn_parse_optional_tagged_nonNegativeInteger(), and slice_parse().
static int ccn_parse_optional_Any_or_Bloom (struct ccn_buf_decoder * d) [static]
Definition at line 351 of file ccn_buf_decoder.c.
Referenced by ccn_parse_Exclude().
uintmax_t ccn_parse_optional_tagged_binary_number (struct ccn_buf_decoder * d, enum ccn_dtag dtag, int minlen, int maxlen, uintmax_t default_value)
Definition at line 204 of file ccn_buf_decoder.c.
Referenced by ccn_interest_lifetime(), ccn_parse_LinkAuthenticator(), and ccn_parse_SignedInfo().
int ccn_parse_optional_tagged_BLOB (struct ccn_buf_decoder * d, enum ccn_dtag dtag, int minlen, int maxlen)
Definition at line 167 of file ccn_buf_decoder.c.
Referenced by ccn_chk_signing_params(), ccn_parse_interest(), ccn_parse_LinkAuthenticator(), ccn_parse_optional_Any_or_Bloom(), ccn_parse_Signature(), and ccn_parse_SignedInfo().
int ccn_parse_optional_tagged_nonNegativeInteger (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 529 of file ccn_buf_decoder.c.
Referenced by ccn_chk_signing_params(), ccn_face_instance_parse(), ccn_forwarding_entry_parse(), ccn_parse_interest(), ccn_parse_LinkAuthenticator(), and ccn_parse_SignedInfo().
int ccn_parse_optional_tagged_UDATA (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 234 of file ccn_buf_decoder.c.
Referenced by ccn_parse_Link(), and ccn_parse_Signature().
int ccn_parse_PublisherID (struct ccn_buf_decoder * d, struct ccn_parsed_interest * pi)
Definition at line 316 of file ccn_buf_decoder.c.
Referenced by ccn_parse_interest(), and ccn_parse_KeyName().
uintmax_t ccn_parse_required_tagged_binary_number (struct ccn_buf_decoder * d, enum ccn_dtag dtag, int minlen, int maxlen)
Definition at line 176 of file ccn_buf_decoder.c.
Referenced by ccn_parse_optional_tagged_binary_number(), and process_incoming_link_message().
int ccn_parse_required_tagged_BLOB (struct ccn_buf_decoder * d, enum ccn_dtag dtag, int minlen, int maxlen)
Definition at line 142 of file ccn_buf_decoder.c.
Referenced by ccn_chk_signing_params(), ccn_parse_ContentObject(), ccn_parse_Exclude(), ccn_parse_optional_tagged_BLOB(), ccn_parse_Signature(), ccn_parse_SignedInfo(), extract_bounds(), and SyncParseHash().
int ccn_parse_required_tagged_timestamp (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 512 of file ccn_buf_decoder.c.
Referenced by ccn_parse_LinkAuthenticator(), and ccn_parse_SignedInfo().
int ccn_parse_required_tagged_UDATA (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 213 of file ccn_buf_decoder.c.
Referenced by ccn_parse_optional_tagged_UDATA().
static int ccn_parse_Signature (struct ccn_buf_decoder * d, struct ccn_parsed_ContentObject * x) [static]
Definition at line 708 of file ccn_buf_decoder.c.
Referenced by ccn_buf_decoder_start_at_components(), and ccn_parse_ContentObject().
static int ccn_parse_SignedInfo (struct ccn_buf_decoder * d, struct ccn_parsed_ContentObject * x) [static]
Definition at line 739 of file ccn_buf_decoder.c.
Referenced by ccn_parse_ContentObject().
int ccn_parse_tagged_string (struct ccn_buf_decoder * d, enum ccn_dtag dtag, struct ccn_charbuf * store)
Parses a ccnb-encoded element expected to contain a UDATA string. Parameters:
d is the decoder
dtag is the expected dtag value
store - on success, the string value is appended to store, with null termination.
Returns:
the offset into the store buffer of the copied value, or -1 for error. If a parse error occurs, d->decoder.state is set to a negative value. If the element is not present, -1 is returned but no parse error is indicated.
Definition at line 253 of file ccn_buf_decoder.c.
Referenced by ccn_face_instance_parse(), ccn_forwarding_entry_parse(), and r_proto_parse_policy().
int ccn_parse_timestamp (struct ccn_buf_decoder * d)
Definition at line 468 of file ccn_buf_decoder.c.
Referenced by ccn_parse_required_tagged_timestamp().
int ccn_parse_uintmax (struct ccn_buf_decoder * d, uintmax_t * result)
Parse a potentially large non-negative integer. Returns:
0 for success, and the value is place in *result; for an error a negative value is returned and *result is unchanged.
Definition at line 433 of file ccn_buf_decoder.c.
Referenced by ccn_parse_tagged_required_uintmax(), slice_parse(), and SyncParseUnsigned().
int ccn_ref_tagged_BLOB (enum ccn_dtag tt, const unsigned char * buf, size_t start, size_t stop, const unsigned char ** presult, size_t * psize)
Definition at line 849 of file ccn_buf_decoder.c.
Referenced by add_cob_exclusion(), add_info_exclusion(), ccn_btree_insert_content(), ccn_btree_match_interest(), ccn_chk_signing_params(), ccn_content_get_value(), ccn_digest_Content(), ccn_initiate_key_fetch(), ccn_is_final_pco(), ccn_locate_key(), ccn_name_next_sibling(), ccn_verify_signature(), ccnd_debug_ccnb(), ccndc_get_ccnd_id(), ccnr_debug_ccnb(), display_the_content(), extract_bounds(), GetNumberFromInfo(), handle_ccndid_response(), incoming_content(), incoming_interest(), is_final(), load_policy(), main(), propagate_interest(), r_proto_policy_update(), r_store_content_field_access(), r_util_segment_from_component(), and segFromInfo().
int ccn_ref_tagged_string (enum ccn_dtag dtag, const unsigned char * buf, size_t start, size_t stop, const unsigned char ** presult, size_t * psize)
Produce a pointer and length for the string in a ccnb-encoded tagged element containing a UDATA string. Parameters:
dtag is the expected dtag value
buf is a ccnb-encoded source.
start is an offset into buf at which the element starts
stop is an offset into buf where the element ends
presult if non-NULL, a pointer through which pointer into buf for start of string will be stored
psize if non-NULL, a pointer through which size of string will be stored.
Returns:
0 on success, <0 on failure.
Definition at line 883 of file ccn_buf_decoder.c.
Referenced by ccn_verify_signature().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.