ccnd/ccnd_internal_client.c
NAME
ccnd/ccnd_internal_client.c -
Internal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols.
SYNOPSIS
Defines
#define GOT_HERE
#define CCND_NOTICE_NAME 'notice.txt'
#define CCND_PING 1
#define ADJ_SOL_SENT (1U << 0)
#define ADJ_SOL_RECV (1U << 1)
#define ADJ_OFR_SENT (1U << 2)
#define ADJ_OFR_RECV (1U << 3)
#define ADJ_CRQ_SENT (1U << 4)
#define ADJ_CRQ_RECV (1U << 5)
#define ADJ_DAT_SENT (1U << 6)
#define ADJ_DAT_RECV (1U << 7)
#define ADJ_TIMEDWAIT (1U << 8)
#define ADJ_PINGING (1U << 9)
#define ADJ_RETRYING (1U << 10)
#define ADJ_ACTIVE (1U << 11)
#define adjstate_change(h, f, s, c) adjstate_change_db(h, f, s, c, __LINE__)
#define ADJ_REFRESH_SEC 120
#define ADJ_MICROS (ADJ_REFRESH_SEC * 1000000)
#define MORECOMPS_MASK 0x007F
Local interpretation of selfp->intdata.
#define MUST_VERIFY 0x0080
#define MUST_VERIFY1 (MUST_VERIFY + 1)
#define OPER_MASK 0xFF00
#define OP_PING 0x0000
#define OP_NEWFACE 0x0200
#define OP_DESTROYFACE 0x0300
#define OP_PREFIXREG 0x0400
#define OP_SELFREG 0x0500
#define OP_UNREG 0x0600
#define OP_NOTICE 0x0700
#define OP_SERVICE 0x0800
#define OP_ADJACENCY 0x0900
#define OP_GUEST 0x0A00
#define CCND_ID_TEMPL 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
#define CCN_PATH_VAR_TMP '/var/tmp'
#define CCND_KEYSTORE_PASS '\010\043\103\375\327\237\152\351\155'
Functions
static void ccnd_start_notice (struct ccnd_handle *ccnd)
static void adjacency_timed_reset (struct ccnd_handle *ccnd, unsigned faceid)
Schedule recovery from a broken adjacency negotiation.
static struct ccn_charbuf * ccnd_init_service_ccnb (struct ccnd_handle *ccnd, const char *baseuri, int freshness)
Creates a key object using the service discovery name profile.
int adjstate_change_db (struct ccnd_handle *ccnd, struct face *face, int set, int clear, int line)
Update face->adjstate by setting / clearing the indicated bits.
static int append_adjacency_uri (struct ccnd_handle *ccnd, struct ccn_charbuf *cb, struct face *face)
Append the URI representation of the adjacency prefix for face to the charbuf cb.
static int adjacency_do_refresh (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event to refresh adjacency.
static void ccnd_register_adjacency (struct ccnd_handle *ccnd, struct face *face, unsigned forwarding_flags)
Register the adjacency prefix with the given forwarding flags.
static int ccnd_flush_guid_cob (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event for getting rid of an old guid cob.
static void ccnd_init_face_guid_cob (struct ccnd_handle *ccnd, struct face *face)
Create the adjacency content object for our endpoint of the face.
static int extract_bounds (const unsigned char *ccnb, struct ccn_parsed_interest *pi, const unsigned char **plo, const unsigned char **phi)
Isolate the lower and upper bounds for the guid component from Exclude.
static enum ccn_upcall_res solicit_response (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Handle the data that comes back in response to interest sent by send_adjacency_solicit.
static int send_adjacency_solicit (struct ccnd_handle *ccnd, struct face *face)
Send an adjacency solitiation interest, to elicit an offer from the other side.
static int ccnd_do_solicit (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event to call send_adjacency_solicit.
static int ccnd_answer_by_guid (struct ccnd_handle *ccnd, struct ccn_upcall_info *info)
Answer an adjacency guid request from any face, based on the guid in the name.
static enum ccn_upcall_res incoming_adjacency (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Handle the data comming back from an adjacency offer or commit request.
void ccnd_adjacency_offer_or_commit_req (struct ccnd_handle *ccnd, struct face *face)
Express an interest to pull adjacency information from the other side.
static void check_offer_matches_my_solicit (struct ccnd_handle *ccnd, struct face *face, struct ccn_upcall_info *info)
Determine whether an offer matches up with our solicitation.
static void schedule_adjacency_negotiation (struct ccnd_handle *ccnd, unsigned faceid)
Schedule negotiation of a link guid if appropriate.
static int adjacency_do_reset (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Scheduled event for recovering from a broken adjacency negotiation.
static int clean_guest (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static enum ccn_upcall_res ccnd_req_guest (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static enum ccn_upcall_res ccnd_answer_req (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Common interest handler for ccnd_internal_client.
static int ccnd_internal_client_refresh (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static void ccnd_uri_listen (struct ccnd_handle *ccnd, const char *uri, ccn_handler p, intptr_t intdata)
static void ccnd_reg_ccnx_ccndid (struct ccnd_handle *ccnd)
Make a forwarding table entry for ccnx:/ccnx/CCNDID.
int ccnd_init_internal_keystore (struct ccnd_handle *ccnd)
static int post_face_notice (struct ccnd_handle *ccnd, unsigned faceid)
static int ccnd_notice_push (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
void ccnd_face_status_change (struct ccnd_handle *ccnd, unsigned faceid)
Called by ccnd when a face undergoes a substantive status change that should be reported to interested parties.
int ccnd_internal_client_start (struct ccnd_handle *ccnd)
void ccnd_internal_client_stop (struct ccnd_handle *ccnd)
Detailed Description
Internal client of ccnd, handles requests for inspecting and controlling operation of the ccnd; requests and responses themselves use ccn protocols.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2009-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_internal_client.c.
Define Documentation
#define ADJ_ACTIVE (1U << 11)
Definition at line 121 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), adjacency_do_reset(), adjacency_timed_reset(), and ccnd_register_adjacency().
#define ADJ_CRQ_RECV (1U << 5)
Definition at line 115 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and incoming_adjacency().
#define ADJ_CRQ_SENT (1U << 4)
Definition at line 114 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req(), and incoming_adjacency().
#define ADJ_DAT_RECV (1U << 7)
Definition at line 117 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), ccnd_answer_req(), ccnd_register_adjacency(), and incoming_adjacency().
#define ADJ_DAT_SENT (1U << 6)
Definition at line 116 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), ccnd_answer_req(), ccnd_register_adjacency(), and incoming_adjacency().
#define ADJ_MICROS (ADJ_REFRESH_SEC * 1000000)
Definition at line 186 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh().
#define ADJ_OFR_RECV (1U << 3)
Definition at line 113 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req(), ccnd_answer_req(), ccnd_init_face_guid_cob(), and check_offer_matches_my_solicit().
#define ADJ_OFR_SENT (1U << 2)
Definition at line 112 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req(), ccnd_init_face_guid_cob(), and incoming_adjacency().
#define ADJ_PINGING (1U << 9)
Definition at line 119 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), ccnd_adjacency_offer_or_commit_req(), and incoming_adjacency().
#define ADJ_REFRESH_SEC 120
Definition at line 185 of file ccnd_internal_client.c.
Referenced by ccnd_register_adjacency().
#define ADJ_RETRYING (1U << 10)
Definition at line 120 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req(), and incoming_adjacency().
#define ADJ_SOL_RECV (1U << 1)
Definition at line 111 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
#define ADJ_SOL_SENT (1U << 0)
Definition at line 110 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req(), ccnd_answer_req(), check_offer_matches_my_solicit(), send_adjacency_solicit(), and solicit_response().
#define ADJ_TIMEDWAIT (1U << 8)
Definition at line 118 of file ccnd_internal_client.c.
Referenced by adjacency_do_reset(), adjacency_timed_reset(), ccnd_adjacency_offer_or_commit_req(), ccnd_answer_req(), and incoming_adjacency().
#define adjstate_change(h, f, s, c) adjstate_change_db(h, f, s, c, __LINE__)
Definition at line 155 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), adjacency_do_reset(), adjacency_timed_reset(), ccnd_adjacency_offer_or_commit_req(), ccnd_answer_req(), ccnd_register_adjacency(), check_offer_matches_my_solicit(), incoming_adjacency(), and send_adjacency_solicit().
#define CCN_PATH_VAR_TMP '/var/tmp'
Definition at line 1316 of file ccnd_internal_client.c.
Referenced by ccnd_init_internal_keystore().
#define CCND_ID_TEMPL 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Definition at line 1240 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start(), and ccnd_uri_listen().
#define CCND_KEYSTORE_PASS '\010\043\103\375\327\237\152\351\155'
Definition at line 1325 of file ccnd_internal_client.c.
Referenced by ccnd_init_internal_keystore().
#define CCND_NOTICE_NAME 'notice.txt'
Definition at line 48 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start(), and ccnd_start_notice().
#define CCND_PING 1
Definition at line 56 of file ccnd_internal_client.c.
#define GOT_HERE
Definition at line 46 of file ccnd_internal_client.c.
#define MORECOMPS_MASK 0x007F
Local interpretation of selfp->intdata.
Definition at line 953 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnr_answer_req().
#define MUST_VERIFY 0x0080
Definition at line 954 of file ccnd_internal_client.c.
#define MUST_VERIFY1 (MUST_VERIFY + 1)
Definition at line 955 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start().
#define OP_ADJACENCY 0x0900
Definition at line 965 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_DESTROYFACE 0x0300
Definition at line 959 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_GUEST 0x0A00
Definition at line 966 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_NEWFACE 0x0200
Definition at line 958 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_NOTICE 0x0700
Definition at line 963 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), ccnd_internal_client_start(), and ccnr_answer_req().
#define OP_PING 0x0000
Definition at line 957 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), ccnd_internal_client_start(), and ccnr_answer_req().
#define OP_PREFIXREG 0x0400
Definition at line 960 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_SELFREG 0x0500
Definition at line 961 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OP_SERVICE 0x0800
Definition at line 964 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), ccnd_internal_client_start(), ccnr_answer_req(), and r_init_create().
#define OP_UNREG 0x0600
Definition at line 962 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnd_internal_client_start().
#define OPER_MASK 0xFF00
Definition at line 956 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and ccnr_answer_req().
Function Documentation
static int adjacency_do_refresh (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event to refresh adjacency.
Definition at line 191 of file ccnd_internal_client.c.
Referenced by ccnd_register_adjacency().
static int adjacency_do_reset (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event for recovering from a broken adjacency negotiation.
Definition at line 770 of file ccnd_internal_client.c.
Referenced by adjacency_timed_reset().
static void adjacency_timed_reset (struct ccnd_handle * ccnd, unsigned faceid) [static]
Schedule recovery from a broken adjacency negotiation.
Definition at line 799 of file ccnd_internal_client.c.
Referenced by incoming_adjacency(), and solicit_response().
int adjstate_change_db (struct ccnd_handle * ccnd, struct face * face, int set, int clear, int line)
Update face->adjstate by setting / clearing the indicated bits. If a bit is in both masks, it is set.
Returns:
the old values, or -1 for an error.
Definition at line 130 of file ccnd_internal_client.c.
static int append_adjacency_uri (struct ccnd_handle * ccnd, struct ccn_charbuf * cb, struct face * face) [static]
Append the URI representation of the adjacency prefix for face to the charbuf cb. Returns:
0 for success, -1 for error.
Definition at line 162 of file ccnd_internal_client.c.
Referenced by ccnd_register_adjacency(), and post_face_notice().
void ccnd_adjacency_offer_or_commit_req (struct ccnd_handle * ccnd, struct face * face)
Express an interest to pull adjacency information from the other side.
Definition at line 644 of file ccnd_internal_client.c.
Referenced by adjacency_do_refresh(), ccnd_answer_req(), and incoming_adjacency().
static int ccnd_answer_by_guid (struct ccnd_handle * ccnd, struct ccn_upcall_info * info) [static]
Answer an adjacency guid request from any face, based on the guid in the name. Returns:
CCN_UPCALL_RESULT_INTEREST_CONSUMED if an answer was sent, otherwise -1.
Definition at line 541 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static enum ccn_upcall_res ccnd_answer_req (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Common interest handler for ccnd_internal_client.
Definition at line 972 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start().
static int ccnd_do_solicit (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event to call send_adjacency_solicit.
Definition at line 507 of file ccnd_internal_client.c.
Referenced by schedule_adjacency_negotiation().
void ccnd_face_status_change (struct ccnd_handle * ccnd, unsigned faceid)
Called by ccnd when a face undergoes a substantive status change that should be reported to interested parties. In the destroy case, this is called from the hash table finalizer, so it shouldn't do much directly. Inspecting the face is OK, though.
Definition at line 1468 of file ccnd_internal_client.c.
Referenced by adjacency_timed_reset(), ccnd_register_adjacency(), ccnd_start_notice(), do_deferred_write(), finalize_face(), and register_new_face().
static int ccnd_flush_guid_cob (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Scheduled event for getting rid of an old guid cob.
Definition at line 260 of file ccnd_internal_client.c.
Referenced by ccnd_init_face_guid_cob().
static void ccnd_init_face_guid_cob (struct ccnd_handle * ccnd, struct face * face) [static]
Create the adjacency content object for our endpoint of the face.
Definition at line 280 of file ccnd_internal_client.c.
Referenced by ccnd_answer_by_guid(), and ccnd_answer_req().
int ccnd_init_internal_keystore (struct ccnd_handle * ccnd)
Definition at line 1329 of file ccnd_internal_client.c.
Referenced by ccnd_create(), and ccnd_internal_client_start().
static struct ccn_charbuf* ccnd_init_service_ccnb (struct ccnd_handle * ccnd, const char * baseuri, int freshness) [static, read]
Creates a key object using the service discovery name profile.
Definition at line 66 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static int ccnd_internal_client_refresh (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 1221 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start().
int ccnd_internal_client_start (struct ccnd_handle * ccnd)
Definition at line 1516 of file ccnd_internal_client.c.
Referenced by ccnd_create().
void ccnd_internal_client_stop (struct ccnd_handle * ccnd)
Definition at line 1569 of file ccnd_internal_client.c.
Referenced by ccnd_destroy().
static int ccnd_notice_push (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 1428 of file ccnd_internal_client.c.
Referenced by ccnd_face_status_change().
static void ccnd_reg_ccnx_ccndid (struct ccnd_handle * ccnd) [static]
Make a forwarding table entry for ccnx:/ccnx/CCNDID. This one entry handles most of the namespace served by the ccnd internal client.
Definition at line 1294 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start().
static void ccnd_register_adjacency (struct ccnd_handle * ccnd, struct face * face, unsigned forwarding_flags) [static]
Register the adjacency prefix with the given forwarding flags.
Definition at line 221 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req(), and incoming_adjacency().
static enum ccn_upcall_res ccnd_req_guest (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 840 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static void ccnd_start_notice (struct ccnd_handle * ccnd) [static]
Definition at line 1483 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static void ccnd_uri_listen (struct ccnd_handle * ccnd, const char * uri, ccn_handler p, intptr_t intdata) [static]
Definition at line 1243 of file ccnd_internal_client.c.
Referenced by ccnd_internal_client_start().
static void check_offer_matches_my_solicit (struct ccnd_handle * ccnd, struct face * face, struct ccn_upcall_info * info) [static]
Determine whether an offer matches up with our solicitation.
Definition at line 704 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static int clean_guest (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 816 of file ccnd_internal_client.c.
Referenced by ccnd_req_guest().
static int extract_bounds (const unsigned char * ccnb, struct ccn_parsed_interest * pi, const unsigned char ** plo, const unsigned char ** phi) [static]
Isolate the lower and upper bounds for the guid component from Exclude. This is used as part of the adjacency protocol.
Definition at line 343 of file ccnd_internal_client.c.
Referenced by ccnd_answer_req().
static enum ccn_upcall_res incoming_adjacency (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Handle the data comming back from an adjacency offer or commit request.
Definition at line 589 of file ccnd_internal_client.c.
Referenced by ccnd_adjacency_offer_or_commit_req().
static int post_face_notice (struct ccnd_handle * ccnd, unsigned faceid) [static]
Definition at line 1391 of file ccnd_internal_client.c.
Referenced by ccnd_notice_push().
static void schedule_adjacency_negotiation (struct ccnd_handle * ccnd, unsigned faceid) [static]
Schedule negotiation of a link guid if appropriate.
Definition at line 745 of file ccnd_internal_client.c.
Referenced by adjacency_do_reset(), and ccnd_face_status_change().
static int send_adjacency_solicit (struct ccnd_handle * ccnd, struct face * face) [static]
Send an adjacency solitiation interest, to elicit an offer from the other side.
Definition at line 425 of file ccnd_internal_client.c.
Referenced by ccnd_do_solicit().
static enum ccn_upcall_res solicit_response (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Handle the data that comes back in response to interest sent by send_adjacency_solicit. We don't actually need to do much here, since the protocol is actually looking for an interest from the other side.
Definition at line 399 of file ccnd_internal_client.c.
Referenced by send_adjacency_solicit().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.