libexec/ccndc-log.c
NAME
libexec/ccndc-log.c -
Logging utilities for ccndc.
SYNOPSIS
Functions
void ccndc_note (int lineno, const char *format,...)
Issue note on stderr, controlled by verbose flag.
void ccndc_warn (int lineno, const char *format,...)
Issue warning on stderr.
void ccndc_fatal (int line, const char *format,...)
Issue error message on stderr and terminate execution of the app.
void on_error_exit (int res, int lineno, const char *msg)
Variables
int verbose = 0
Detailed Description
Logging utilities for ccndc.
Copyright (C) 2009-2012 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccndc-log.c.
Function Documentation
void ccndc_fatal (int line, const char * format, ...)
Issue error message on stderr and terminate execution of the app. Parameters:
lineno Line number where problem happened
format printf-style format line
Definition at line 54 of file ccndc-log.c.
Referenced by create_command_from_command_line(), on_error_exit(), and read_configfile().
void ccndc_note (int lineno, const char * format, ...)
Issue note on stderr, controlled by verbose flag. Parameters:
lineno Line number where problem happened
format printf-style format line
Definition at line 28 of file ccndc-log.c.
Referenced by ccndc_daemonize(), and ccndc_srv().
void ccndc_warn (int lineno, const char * format, ...)
Issue warning on stderr. Parameters:
lineno Line number where problem happened
format printf-style format line
Definition at line 42 of file ccndc-log.c.
Referenced by ccndc_add(), ccndc_create(), ccndc_del(), ccndc_destroy(), ccndc_destroyface(), ccndc_get_ccnd_id(), ccndc_renew(), ccndc_srv(), main(), parse_ccn_face_instance(), parse_ccn_face_instance_from_face(), parse_ccn_forwarding_entry(), and read_configfile().
void on_error_exit (int res, int lineno, const char * msg)
Definition at line 67 of file ccndc-log.c.
Variable Documentation
int verbose = 0
Definition at line 25 of file ccndc-log.c.
Referenced by ccnbx(), ccndc_note(), main(), and printraw().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.