libexec/ccndc-main.c
NAME
libexec/ccndc-main.c -
Bring up a link to another ccnd.
SYNOPSIS
Functions
static int read_configfile (struct ccndc_data *ccndc, const char *filename)
Process configuration file.
static void usage (const char *progname)
char * create_command_from_command_line (int argc, char **argv)
int main (int argc, char **argv)
Detailed Description
Bring up a link to another ccnd.
A CCNx program.
Copyright (C) 2009-2012 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccndc-main.c.
Function Documentation
char* create_command_from_command_line (int argc, char ** argv)
Definition at line 65 of file ccndc-main.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 97 of file ccndc-main.c.
static int read_configfile (struct ccndc_data * ccndc, const char * filename) [static]
Process configuration file. Parameters:
filename Processing configuration file in two rounds. First round performs a dry run to check for errors. If no erors found, commands are executing if normal mode.
Definition at line 184 of file ccndc-main.c.
Referenced by main().
static void usage (const char * progname) [static]
Definition at line 37 of file ccndc-main.c.
Referenced by initialize(), main(), parseopts(), and process_options().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.