libexec/ccndc.h
NAME
libexec/ccndc.h -
Bring up a link to another ccnd.
SYNOPSIS
Data Structures
struct ccndc_data
Internal data structure for ccndc.
Functions
struct ccndc_data * ccndc_initialize_data (void)
Initialize internal data structures.
void ccndc_destroy_data (struct ccndc_data **data)
Destroy internal data structures.
int ccndc_dispatch_cmd (struct ccndc_data *self, int check_only, const char *cmd, const char *options, int num_options)
Select a correct command based on the supplied argument.
int ccndc_add (struct ccndc_data *self, int check_only, const char *cmd)
Create a new FIB entry if it doesn't exist.
int ccndc_del (struct ccndc_data *self, int check_only, const char *cmd)
Delete a FIB entry if it exists.
int ccndc_renew (struct ccndc_data *self, int check_only, const char *cmd)
Delete a face and recreate it with the specified parameters and prefix.
int ccndc_create (struct ccndc_data *self, int check_only, const char *cmd)
Create a new face without adding any prefix to it.
int ccndc_destroy (struct ccndc_data *self, int check_only, const char *cmd)
Destroy a face.
int ccndc_srv (struct ccndc_data *self, const unsigned char *domain, size_t domain_size)
brief Add (and if exists recreated) FIB entry based on guess from SRV records for a specified domain
int ccndc_destroyface (struct ccndc_data *self, int check_only, const char *cmd)
Destroy face if it exists.
int ccndc_get_ccnd_id (struct ccndc_data *self)
Get ID of the local CCND.
struct ccn_face_instance * ccndc_do_face_action (struct ccndc_data *self, const char *action, struct ccn_face_instance *face_instance)
Perform action using face management protocol.
int ccndc_do_prefix_action (struct ccndc_data *self, const char *action, struct ccn_forwarding_entry *forwarding_entry)
Perform action using prefix management protocol.
struct ccn_forwarding_entry * parse_ccn_forwarding_entry (struct ccndc_data *self, const char *cmd_uri, const char *cmd_flags, int freshness)
struct ccn_face_instance * parse_ccn_face_instance (struct ccndc_data *self, const char *cmd_proto, const char *cmd_host, const char *cmd_port, const char *cmd_mcastttl, const char *cmd_mcastif, int freshness)
struct ccn_face_instance * parse_ccn_face_instance_from_face (struct ccndc_data *self, const char *cmd_faceid)
Detailed Description
Bring up a link to another ccnd.
A CCNx program.
Copyright (C) 2009-2012 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccndc.h.
Function Documentation
int ccndc_add (struct ccndc_data * self, int check_only, const char * cmd)
Create a new FIB entry if it doesn't exist. The call also automatically creates a face (if it doesn't exist)
cmd format: uri (udp|tcp) host [port [flags [mcastttl [mcastif]]]])
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be created)
cmd add command without leading 'add' component
Returns:
0 on success
Definition at line 177 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
int ccndc_create (struct ccndc_data * self, int check_only, const char * cmd)
Create a new face without adding any prefix to it. cmd format: (udp|tcp) host [port [flags [mcastttl [mcastif]]]])
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be created)
cmd create command without leading 'create' component
Returns:
0 on success
Definition at line 320 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
int ccndc_del (struct ccndc_data * self, int check_only, const char * cmd)
Delete a FIB entry if it exists. cmd format: uri (udp|tcp) host [port [flags [mcastttl [mcastif]]]])
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be removed)
cmd del command without leading 'del' component
Returns:
0 on success
Definition at line 248 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
int ccndc_destroy (struct ccndc_data * self, int check_only, const char * cmd)
Destroy a face. cmd format: (udp|tcp) host [port [flags [mcastttl [mcastif [destroyface]]]]])
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be removed)
cmd destroy command without leading 'destroy' component
Returns:
0 on success
Definition at line 376 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
void ccndc_destroy_data (struct ccndc_data ** data)
Destroy internal data structures. data pointer to 'this'
Definition at line 106 of file ccndc.c.
Referenced by main().
int ccndc_destroyface (struct ccndc_data * self, int check_only, const char * cmd)
Destroy face if it exists. cmd format: faceid
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be destroyed)
cmd destroyface command without leading 'destroyface' component
Returns:
0 on success
Definition at line 530 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
int ccndc_dispatch_cmd (struct ccndc_data * self, int check_only, const char * cmd, const char * options, int num_options)
Select a correct command based on the supplied argument. Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (no messages are exchanged with ccnd)
cmd command name (e.g., add, del, or destroyface)
options command options
num_options number of command line options (not checked if < 0)
Returns:
0 on success, non zero means error, -99 means command line error
Definition at line 121 of file ccndc.c.
Referenced by main(), and read_configfile().
struct ccn_face_instance* ccndc_do_face_action (struct ccndc_data * self, const char * action, struct ccn_face_instance * face_instance) [read]
Perform action using face management protocol. Parameters:
self data pointer to 'this'
action action string
face_instance filled ccn_face_instance structure
Returns:
on success returns a new struct ccn_face_instance, describing created/destroyed face the structure needs to be manually destroyed
Definition at line 998 of file ccndc.c.
Referenced by ccndc_add(), ccndc_create(), ccndc_del(), ccndc_destroy(), ccndc_destroyface(), ccndc_renew(), and ccndc_srv().
int ccndc_do_prefix_action (struct ccndc_data * self, const char * action, struct ccn_forwarding_entry * forwarding_entry)
Perform action using prefix management protocol. Parameters:
self data pointer to 'this'
action action string
forwarding_entry filled ccn_forwarding_entry structure
Returns:
0 on success
Definition at line 1060 of file ccndc.c.
Referenced by ccndc_add(), ccndc_del(), ccndc_renew(), and ccndc_srv().
int ccndc_get_ccnd_id (struct ccndc_data * self)
Get ID of the local CCND. CCND ID is recorded in supplied ccndc_data data structure
Parameters:
self data pointer to 'this'
Definition at line 935 of file ccndc.c.
Referenced by ccndc_initialize_data().
struct ccndc_data* ccndc_initialize_data (void) [read]
Initialize internal data structures. Returns:
'this' pointer
Definition at line 73 of file ccndc.c.
Referenced by main().
int ccndc_renew (struct ccndc_data * self, int check_only, const char * cmd)
Delete a face and recreate it with the specified parameters and prefix. cmd format: uri (udp|tcp) host [port [flags [mcastttl [mcastif]]]])
Parameters:
self data pointer to 'this'
check_only flag indicating that only command checking is requested (nothing will be created)
cmd add command without leading 'renew' component
Returns:
0 on success
Definition at line 446 of file ccndc.c.
Referenced by ccndc_dispatch_cmd().
int ccndc_srv (struct ccndc_data * self, const unsigned char * domain, size_t domain_size)
brief Add (and if exists recreated) FIB entry based on guess from SRV records for a specified domain Parameters:
domain domain name
domain_size size of the 'domain' variable
Returns:
0 on success
Definition at line 574 of file ccndc.c.
Referenced by ccndc_dispatch_cmd(), and incoming_interest().
struct ccn_face_instance* parse_ccn_face_instance (struct ccndc_data * self, const char * cmd_proto, const char * cmd_host, const char * cmd_port, const char * cmd_mcastttl, const char * cmd_mcastif, int freshness) [read]
Definition at line 741 of file ccndc.c.
Referenced by ccndc_add(), ccndc_create(), ccndc_del(), ccndc_destroy(), ccndc_renew(), and ccndc_srv().
struct ccn_face_instance* parse_ccn_face_instance_from_face (struct ccndc_data * self, const char * cmd_faceid) [read]
Definition at line 889 of file ccndc.c.
Referenced by ccndc_destroyface().
struct ccn_forwarding_entry* parse_ccn_forwarding_entry (struct ccndc_data * self, const char * cmd_uri, const char * cmd_flags, int freshness) [read]
Definition at line 682 of file ccndc.c.
Referenced by ccndc_add(), ccndc_del(), ccndc_renew(), and ccndc_srv().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.