ccnd/ccnd_msg.c
NAME
ccnd/ccnd_msg.c -
Logging support for ccnd.
SYNOPSIS
Functions
void ccnd_msg (struct ccnd_handle *h, const char *fmt,...)
Produce ccnd debug output.
void ccnd_debug_ccnb (struct ccnd_handle *h, int lineno, const char *msg, struct face *face, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry.
Variables
const char * ccnd_usage_message
CCND Usage message.
Detailed Description
Logging support for ccnd.
Part of ccnd - the CCNx Daemon.
Copyright (C) 2008-2013 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnd_msg.c.
Function Documentation
void ccnd_debug_ccnb (struct ccnd_handle * h, int lineno, const char * msg, struct face * face, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnd debug trace entry. Output is produced by calling ccnd_msg.
Parameters:
h the ccnd handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
face handle of associated face; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 91 of file ccnd_msg.c.
Referenced by age_forwarding(), ccnd_answer_req(), ccnd_reg_prefix(), ccnd_req_unreg(), do_propagate(), drop_nonlocal_interest(), face_send_queue_insert(), find_first_match_candidate(), mark_stale(), next_child_at_level(), process_incoming_content(), process_incoming_interest(), remove_content(), send_content(), set_content_timer(), strategy_callout(), stuff_and_send(), and stuff_link_check().
void ccnd_msg (struct ccnd_handle * h, const char * fmt, ...)
Produce ccnd debug output. Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnd handle
fmt printf-like format string
Definition at line 45 of file ccnd_msg.c.
Referenced by accept_connection(), adjstate_change_db(), ccn_append_link_stuff(), ccnd_close_fd(), ccnd_collect_stats(), ccnd_create(), ccnd_debug_ccnb(), ccnd_getboundsocket(), ccnd_init_internal_keystore(), ccnd_listen_on_address(), ccnd_listen_on_wildcards(), ccnd_new_face_msg(), ccnd_parse_uri_list(), ccnd_req_destroyface(), ccnd_req_newface(), ccnd_run(), ccnd_send(), ccnd_setsockopt_v6only(), ccnd_start_notice(), ccnd_stats_http_set_debug(), check_comm_file(), content_sender(), create_local_listener(), do_deferred_write(), establish_min_recv_bufsize(), face_send_queue_insert(), finalize_content(), finalize_face(), get_outbound_faces(), handle_send_error(), ie_next_usec(), main(), make_connection(), note_content_from(), pfi_set_expiry_from_lifetime(), process_incoming_content(), process_incoming_interest(), process_incoming_link_message(), process_input(), process_input_buffer(), process_input_message(), record_connection(), setup_multicast(), shutdown_client_fd(), start_ccnd(), and update_forward_to().
Variable Documentation
const char* ccnd_usage_message
CCND Usage message.
Definition at line 176 of file ccnd_msg.c.
Referenced by main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.