.TH "cmd/ccninitkeystore.c" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd/ccninitkeystore.c \- 
.PP
Initialize a CCNx keystore with given parameters.  

.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCCN_KEYSTORE_PASS\fP   'Th1s1sn0t8g00dp8ssw0rd.'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBusage\fP (const char *\fBprogname\fP)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Initialize a CCNx keystore with given parameters. 

A CCNx command-line utility.
.PP
Copyright (C) 2011 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBccninitkeystore.c\fP.
.SH "Define Documentation"
.PP 
.SS "#define CCN_KEYSTORE_PASS   'Th1s1sn0t8g00dp8ssw0rd.'"
.PP
Definition at line 31 of file ccninitkeystore.c.
.PP
Referenced by main().
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 50 of file ccninitkeystore.c.
.SS "static void usage (const char * progname)\fC [static]\fP"
.PP
Definition at line 34 of file ccninitkeystore.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
