cmd/ccnlibtest.c
NAME
cmd/ccnlibtest.c -
SYNOPSIS
Defines
#define N_POOLS 10
#define MINI_STORE_LIMIT 10
#define USAGE 'ccnlibtest [-hv] (pool n | flags x | prefix uri | reconnect secs | run millis | file.ccnb) ...'
Functions
void printraw (const void *r, int n)
int add_to_pool (int pool, const unsigned char *r, size_t n)
int n_pool (int pool)
enum ccn_upcall_res incoming_content (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
int cob_matches (struct ccn_upcall_info *info, struct ccn_charbuf *cob)
enum ccn_upcall_res outgoing_content (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
void usage (void)
Usage.
int main (int argc, char **argv)
Variables
int verbose
static unsigned char rawbuf [65536]
static ssize_t rawlen
static struct ccn_closure incoming_content_action [N_POOLS]
static struct mini_store store [N_POOLS]
Detailed Description
Definition in file ccnlibtest.c.
Define Documentation
#define MINI_STORE_LIMIT 10
Definition at line 60 of file ccnlibtest.c.
Referenced by add_to_pool(), n_pool(), and outgoing_content().
#define N_POOLS 10
Definition at line 59 of file ccnlibtest.c.
Referenced by main().
#define USAGE 'ccnlibtest [-hv] (pool n | flags x | prefix uri | reconnect secs | run millis | file.ccnb) ...'
Definition at line 177 of file ccnlibtest.c.
Function Documentation
int add_to_pool (int pool, const unsigned char * r, size_t n)
Definition at line 69 of file ccnlibtest.c.
Referenced by incoming_content(), and main().
int cob_matches (struct ccn_upcall_info * info, struct ccn_charbuf * cob)
Definition at line 120 of file ccnlibtest.c.
Referenced by outgoing_content().
enum ccn_upcall_res incoming_content (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Definition at line 103 of file ccnlibtest.c.
int main (int argc, char ** argv)
Definition at line 187 of file ccnlibtest.c.
int n_pool (int pool)
Definition at line 90 of file ccnlibtest.c.
Referenced by main().
enum ccn_upcall_res outgoing_content (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Definition at line 132 of file ccnlibtest.c.
Referenced by main().
void printraw (const void * r, int n)
Definition at line 36 of file ccnlibtest.c.
Referenced by incoming_content(), and outgoing_content().
static void usage (void)
Usage.
Definition at line 180 of file ccnlibtest.c.
Variable Documentation
struct ccn_closure incoming_content_action[N_POOLS] [static]
Definition at line 65 of file ccnlibtest.c.
Referenced by main().
unsigned char rawbuf[65536] [static]
Definition at line 56 of file ccnlibtest.c.
ssize_t rawlen [static]
Definition at line 57 of file ccnlibtest.c.
Referenced by main(), and send_ccnb_file().
struct mini_store store[N_POOLS] [static]
Definition at line 66 of file ccnlibtest.c.
Referenced by add_to_pool(), ccn_face_instance_parse(), ccn_forwarding_entry_parse(), main(), and n_pool().
int verbose
Definition at line 33 of file ccnlibtest.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.