cmd/ccnnamelist.c
NAME
cmd/ccnnamelist.c -
SYNOPSIS
Functions
static size_t process_data (struct ccn_skeleton_decoder *d, unsigned char *data, size_t n, struct ccn_charbuf *c)
static int process_fd (int fd, struct ccn_charbuf *c)
static int process_file (char *path, struct ccn_charbuf *c)
static void usage (const char *progname)
int main (int argc, char *argv[])
Function Documentation
int main (int argc, char * argv[])
Definition at line 151 of file ccnnamelist.c.
static size_t process_data (struct ccn_skeleton_decoder * d, unsigned char * data, size_t n, struct ccn_charbuf * c) [static]
Definition at line 41 of file ccnnamelist.c.
Referenced by process_fd().
static int process_fd (int fd, struct ccn_charbuf * c) [static]
Definition at line 61 of file ccnnamelist.c.
Referenced by main(), and process_file().
static int process_file (char * path, struct ccn_charbuf * c) [static]
Definition at line 120 of file ccnnamelist.c.
Referenced by main().
static void usage (const char * progname) [static]
Definition at line 140 of file ccnnamelist.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.