ccnr/ccnr_sync.c
NAME
ccnr/ccnr_sync.c -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
PUBLIC uintmax_t ccnr_accession_encode (struct ccnr_handle *ccnr, ccnr_accession a)
PUBLIC ccnr_accession ccnr_accession_decode (struct ccnr_handle *ccnr, uintmax_t encoded)
PUBLIC int ccnr_accession_compare (struct ccnr_handle *ccnr, ccnr_accession x, ccnr_accession y)
PUBLIC uintmax_t ccnr_hwm_encode (struct ccnr_handle *ccnr, ccnr_hwm hwm)
PUBLIC ccnr_hwm ccnr_hwm_decode (struct ccnr_handle *ccnr, uintmax_t encoded)
PUBLIC int ccnr_acc_in_hwm (struct ccnr_handle *ccnr, ccnr_accession a, ccnr_hwm hwm)
PUBLIC ccnr_hwm ccnr_hwm_update (struct ccnr_handle *ccnr, ccnr_hwm hwm, ccnr_accession a)
PUBLIC ccnr_hwm ccnr_hwm_merge (struct ccnr_handle *ccnr, ccnr_hwm x, ccnr_hwm y)
PUBLIC int ccnr_hwm_compare (struct ccnr_handle *ccnr, ccnr_hwm x, ccnr_hwm y)
PUBLIC void r_sync_msg (struct sync_plumbing *sdd, const char *fmt,...)
A wrapper for ccnr_msg that takes a sync_plumbing instead of ccnr_handle.
PUBLIC int r_sync_fence (struct sync_plumbing *sdd, uint64_t seq_num)
A call to r_sync_fence sets a 'fence' marker that is remembered for any clean shut down of a repo/sync pair.
PUBLIC int r_sync_notify_content (struct ccnr_handle *ccnr, int e, struct content_entry *content)
A wrapper for the sync_notify method that takes a content entry.
static struct sync_enumeration_state * cleanup_se (struct ccnr_handle *ccnr, struct sync_enumeration_state *md)
static int r_sync_enumerate_action (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
PUBLIC int r_sync_enumerate (struct sync_plumbing *sdd, struct ccn_charbuf *interest)
Request that a SyncNotifyContent call be made for each content object in the repository that matches the interest.
PUBLIC int r_sync_lookup (struct sync_plumbing *sdd, struct ccn_charbuf *interest, struct ccn_charbuf *content_ccnb)
Look up a content object that is stored locally in the repository based on the supplied interest.
PUBLIC int r_lookup (struct ccnr_handle *ccnr, struct ccn_charbuf *interest, struct ccn_charbuf *content_ccnb)
Look up a content object that is stored locally in the repository based on the supplied interest.
PUBLIC enum ccn_upcall_res r_sync_upcall_store (struct sync_plumbing *sdd, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Called when a content object is received by sync and needs to be committed to stable storage by the repo.
PUBLIC int r_sync_local_store (struct sync_plumbing *sdd, struct ccn_charbuf *content_cb)
Called when a content object has been constructed locally by sync and needs to be committed to stable storage by the repo.
Variables
static const int se_cookie = __LINE__
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_sync.c.
Function Documentation
PUBLIC int ccnr_acc_in_hwm (struct ccnr_handle * ccnr, ccnr_accession a, ccnr_hwm hwm)
Definition at line 91 of file ccnr_sync.c.
PUBLIC int ccnr_accession_compare (struct ccnr_handle * ccnr, ccnr_accession x, ccnr_accession y)
Definition at line 70 of file ccnr_sync.c.
PUBLIC ccnr_accession ccnr_accession_decode (struct ccnr_handle * ccnr, uintmax_t encoded)
Definition at line 64 of file ccnr_sync.c.
Referenced by r_store_content_btree_insert(), and r_store_look().
PUBLIC uintmax_t ccnr_accession_encode (struct ccnr_handle * ccnr, ccnr_accession a)
Definition at line 58 of file ccnr_sync.c.
Referenced by r_store_content_base(), r_store_content_btree_insert(), r_store_content_from_accession(), r_store_set_accession_from_offset(), and r_sync_notify_content().
PUBLIC int ccnr_hwm_compare (struct ccnr_handle * ccnr, ccnr_hwm x, ccnr_hwm y)
Definition at line 109 of file ccnr_sync.c.
PUBLIC ccnr_hwm ccnr_hwm_decode (struct ccnr_handle * ccnr, uintmax_t encoded)
Definition at line 85 of file ccnr_sync.c.
PUBLIC uintmax_t ccnr_hwm_encode (struct ccnr_handle * ccnr, ccnr_hwm hwm)
Definition at line 79 of file ccnr_sync.c.
PUBLIC ccnr_hwm ccnr_hwm_merge (struct ccnr_handle * ccnr, ccnr_hwm x, ccnr_hwm y)
Definition at line 103 of file ccnr_sync.c.
PUBLIC ccnr_hwm ccnr_hwm_update (struct ccnr_handle * ccnr, ccnr_hwm hwm, ccnr_accession a)
Definition at line 97 of file ccnr_sync.c.
static struct sync_enumeration_state* cleanup_se (struct ccnr_handle * ccnr, struct sync_enumeration_state * md) [static, read]
Definition at line 205 of file ccnr_sync.c.
Referenced by r_sync_enumerate_action().
PUBLIC int r_lookup (struct ccnr_handle * ccnr, struct ccn_charbuf * interest, struct ccn_charbuf * content_ccnb)
Look up a content object that is stored locally in the repository based on the supplied interest. Takes a ccnr handle instead of sync data. appends the content object to the content_ccnb. returns 0 for success, -1 for error.
Definition at line 421 of file ccnr_sync.c.
Referenced by r_proto_initiate_key_fetch(), and r_sync_lookup().
PUBLIC int r_sync_enumerate (struct sync_plumbing * sdd, struct ccn_charbuf * interest)
Request that a SyncNotifyContent call be made for each content object in the repository that matches the interest. Request that a SyncNotifyContent call is made for each content object matching the interest.
If SyncNotifyContent returns -1 the active enumeration will be cancelled.
When there are no more matching objects, SyncNotifyContent will be called passing NULL for name.
Content objects that arrive during an enumeration may or may not be included in that enumeration.
Returns:
-1 for error, or an enumeration number which will also be passed in the SyncNotifyContent
Definition at line 324 of file ccnr_sync.c.
static int r_sync_enumerate_action (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 221 of file ccnr_sync.c.
PUBLIC int r_sync_fence (struct sync_plumbing * sdd, uint64_t seq_num)
A call to r_sync_fence sets a 'fence' marker that is remembered for any clean shut down of a repo/sync pair.
Definition at line 133 of file ccnr_sync.c.
PUBLIC int r_sync_local_store (struct sync_plumbing * sdd, struct ccn_charbuf * content_cb)
Called when a content object has been constructed locally by sync and needs to be committed to stable storage by the repo. returns 0 for success, -1 for error.
Definition at line 498 of file ccnr_sync.c.
Referenced by r_sync_local_store().
PUBLIC int r_sync_lookup (struct sync_plumbing * sdd, struct ccn_charbuf * interest, struct ccn_charbuf * content_ccnb)
Look up a content object that is stored locally in the repository based on the supplied interest. appends the content object to the content_ccnb. returns 0 for success, -1 for error.
Definition at line 412 of file ccnr_sync.c.
PUBLIC void r_sync_msg (struct sync_plumbing * sdd, const char * fmt, ...)
A wrapper for ccnr_msg that takes a sync_plumbing instead of ccnr_handle. Report message from sync code back through ccnr message infrastructure.
Definition at line 122 of file ccnr_sync.c.
PUBLIC int r_sync_notify_content (struct ccnr_handle * ccnr, int e, struct content_entry * content)
A wrapper for the sync_notify method that takes a content entry.
Definition at line 147 of file ccnr_sync.c.
Referenced by r_store_set_accession_from_offset(), r_sync_enumerate_action(), and r_sync_notify_content().
PUBLIC enum ccn_upcall_res r_sync_upcall_store (struct sync_plumbing * sdd, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Called when a content object is received by sync and needs to be committed to stable storage by the repo.
Definition at line 455 of file ccnr_sync.c.
Referenced by r_sync_upcall_store().
Variable Documentation
const int se_cookie = __LINE__ [static]
Definition at line 202 of file ccnr_sync.c.
Referenced by cleanup_se(), and r_sync_enumerate_action().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.