ccnr/ccnr_sendq.h
NAME
ccnr/ccnr_sendq.h -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
int r_sendq_face_send_queue_insert (struct ccnr_handle *h, struct fdholder *fdholder, struct content_entry *content)
void r_sendq_content_queue_destroy (struct ccnr_handle *h, struct content_queue **pq)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_sendq.h.
Function Documentation
void r_sendq_content_queue_destroy (struct ccnr_handle * h, struct content_queue ** pq)
Definition at line 97 of file ccnr_sendq.c.
Referenced by r_io_shutdown_client_fd().
int r_sendq_face_send_queue_insert (struct ccnr_handle * h, struct fdholder * fdholder, struct content_entry * content)
Definition at line 222 of file ccnr_sendq.c.
Referenced by r_match_consume_matching_interests(), and r_proto_answer_req().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.