ccnr/ccnr_msg.h
NAME
ccnr/ccnr_msg.h -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
int ccnr_msg_level_from_string (const char *s)
void ccnr_debug_ccnb (struct ccnr_handle *h, int lineno, const char *msg, struct fdholder *fdholder, const unsigned char *ccnb, size_t ccnb_size)
Produce a ccnr debug trace entry.
void ccnr_msg (struct ccnr_handle *h, const char *fmt,...)
Produce ccnr debug output.
void ccnr_vmsg (struct ccnr_handle *h, const char *fmt, va_list ap)
Produce ccnr debug output.
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_msg.h.
Function Documentation
void ccnr_debug_ccnb (struct ccnr_handle * h, int lineno, const char * msg, struct fdholder * fdholder, const unsigned char * ccnb, size_t ccnb_size)
Produce a ccnr debug trace entry. Output is produced by calling ccnr_msg.
Parameters:
h the ccnr handle
lineno caller's source line number (usually __LINE__)
msg a short text tag to identify the entry
fdholder handle of associated fdholder; may be NULL
ccnb points to ccnb-encoded Interest or ContentObject
ccnb_size is in bytes
Definition at line 147 of file ccnr_msg.c.
Referenced by ccnr_answer_req(), load_policy(), r_lookup(), r_match_consume_matching_interests(), r_proto_answer_req(), r_proto_begin_enumeration(), r_proto_bulk_import(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_proto_expect_content(), r_proto_initiate_key_fetch(), r_proto_policy_complete(), r_proto_policy_update(), r_proto_start_write(), r_proto_start_write_checked(), r_store_lookup(), r_store_lookup_backwards(), r_store_next_child_at_level(), and reap_enumerations().
void ccnr_msg (struct ccnr_handle * h, const char * fmt, ...)
Produce ccnr debug output. Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnr handle
fmt printf-like format string
Definition at line 86 of file ccnr_msg.c.
Referenced by ccnr_close_fd(), ccnr_collect_stats(), ccnr_debug_ccnb(), ccnr_debug_content(), ccnr_direct_client_refresh(), ccnr_init_repo_keystore(), ccnr_stats_http_set_debug(), cleanup_se(), content_sender(), establish_min_send_bufsize(), handle_send_error(), load_policy(), main(), merge_files(), process_input_buffer(), process_input_message(), r_dispatch_process_input(), r_dispatch_run(), r_init_config_msg(), r_init_confval(), r_init_create(), r_init_debug_getenv(), r_init_fail(), r_init_map_and_process_file(), r_init_parse_config(), r_io_accept_connection(), r_io_open_repo_data_file(), r_io_prepare_poll_fds(), r_io_record_fd(), r_io_send(), r_io_shutdown_client_fd(), r_link_do_deferred_write(), r_net_listen_on_address(), r_net_setsockopt_v6only(), r_proto_activate_policy(), r_proto_begin_enumeration(), r_proto_bulk_import(), r_proto_check_exclude(), r_proto_continue_enumeration(), r_proto_deactivate_policy(), r_proto_dump_enums(), r_proto_expect_content(), r_proto_policy_complete(), r_proto_policy_update(), r_proto_start_write(), r_proto_start_write_checked(), r_sendq_face_send_queue_insert(), r_store_commit_content(), r_store_content_base(), r_store_content_from_accession(), r_store_content_read(), r_store_fatal(), r_store_final(), r_store_forget_content(), r_store_index_cleaner(), r_store_index_needs_cleaning(), r_store_init(), r_store_read_stable_point(), r_store_reindexing(), r_store_set_flatname(), r_store_trim(), r_store_write_stable_point(), r_sync_fence(), r_sync_local_store(), r_sync_notify_content(), r_sync_upcall_store(), and start_ccnr().
int ccnr_msg_level_from_string (const char * s)
Definition at line 48 of file ccnr_msg.c.
Referenced by main(), and r_init_debug_getenv().
void ccnr_vmsg (struct ccnr_handle * h, const char * fmt, va_list ap)
Produce ccnr debug output. Output is produced via h->logger under the control of h->debug; prepends decimal timestamp and process identification. Caller should not supply newlines.
Parameters:
h the ccnr handle
fmt printf-like format string
Definition at line 103 of file ccnr_msg.c.
Referenced by ccnr_msg(), and r_sync_msg().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.