.TH "ccnr/ccnr_forwarding.c" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnr/ccnr_forwarding.c \- 
.PP
Part of ccnr - CCNx Repository Daemon.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "PUBLIC void \fBr_fwd_finalize_nameprefix\fP (struct \fBhashtb_enumerator\fP *e)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Part of ccnr - CCNx Repository Daemon. 


.PP
Definition in file \fBccnr_forwarding.c\fP.
.SH "Function Documentation"
.PP 
.SS "PUBLIC void r_fwd_finalize_nameprefix (struct \fBhashtb_enumerator\fP * e)"
.PP
Definition at line 67 of file ccnr_forwarding.c.
.PP
Referenced by r_init_create().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
