ccnr/ccnr_link.c
NAME
ccnr/ccnr_link.c -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
PUBLIC void r_link_send_content (struct ccnr_handle *h, struct fdholder *fdholder, struct content_entry *content)
PUBLIC void r_link_stuff_and_send (struct ccnr_handle *h, struct fdholder *fdholder, const unsigned char *data1, size_t size1, const unsigned char *data2, size_t size2, off_t *offsetp)
Send a message, which may be in two pieces.
PUBLIC void r_link_do_deferred_write (struct ccnr_handle *h, int fd)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_link.c.
Function Documentation
PUBLIC void r_link_do_deferred_write (struct ccnr_handle * h, int fd)
Definition at line 111 of file ccnr_link.c.
Referenced by r_dispatch_run().
PUBLIC void r_link_send_content (struct ccnr_handle * h, struct fdholder * fdholder, struct content_entry * content)
Definition at line 73 of file ccnr_link.c.
Referenced by content_sender().
PUBLIC void r_link_stuff_and_send (struct ccnr_handle * h, struct fdholder * fdholder, const unsigned char * data1, size_t size1, const unsigned char * data2, size_t size2, off_t * offsetp)
Send a message, which may be in two pieces.
Definition at line 88 of file ccnr_link.c.
Referenced by r_store_send_content().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.