.TH "ccnr/ccnr_sendq.h" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccnr/ccnr_sendq.h \- 
.PP
Part of ccnr - CCNx Repository Daemon.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBr_sendq_face_send_queue_insert\fP (struct \fBccnr_handle\fP *h, struct \fBfdholder\fP *\fBfdholder\fP, struct \fBcontent_entry\fP *content)"
.br
.ti -1c
.RI "void \fBr_sendq_content_queue_destroy\fP (struct \fBccnr_handle\fP *h, struct \fBcontent_queue\fP **pq)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Part of ccnr - CCNx Repository Daemon. 


.PP
Definition in file \fBccnr_sendq.h\fP.
.SH "Function Documentation"
.PP 
.SS "void r_sendq_content_queue_destroy (struct \fBccnr_handle\fP * h, struct \fBcontent_queue\fP ** pq)"
.PP
Definition at line 97 of file ccnr_sendq.c.
.PP
Referenced by r_io_shutdown_client_fd().
.SS "int r_sendq_face_send_queue_insert (struct \fBccnr_handle\fP * h, struct \fBfdholder\fP * fdholder, struct \fBcontent_entry\fP * content)"
.PP
Definition at line 222 of file ccnr_sendq.c.
.PP
Referenced by r_match_consume_matching_interests(), and r_proto_answer_req().
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
