ccnr/ccnr_internal_client.c
NAME
ccnr/ccnr_internal_client.c -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Defines
#define CCNR_ID_TEMPL 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
#define CCNR_KEYSTORE_PASS 'Th1s 1s n0t 8 g00d R3p0s1t0ry p8ssw0rd!'
Functions
static struct ccn_charbuf * ccnr_init_service_ccnb (struct ccnr_handle *ccnr, struct ccn *h, const char *baseuri, int freshness)
PUBLIC enum ccn_upcall_res ccnr_answer_req (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Common interest handler.
static int ccnr_internal_client_refresh (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
PUBLIC void ccnr_uri_listen (struct ccnr_handle *ccnr, struct ccn *ccn, const char *uri, ccn_handler p, intptr_t intdata)
int ccnr_init_repo_keystore (struct ccnr_handle *ccnr, struct ccn *h)
Create the repository keystore if necessary, and load it into the client handle h.
static int post_face_notice (struct ccnr_handle *ccnr, unsigned filedesc)
static int ccnr_notice_push (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
void ccnr_face_status_change (struct ccnr_handle *ccnr, unsigned filedesc)
Called by ccnr when a fdholder undergoes a substantive status change that should be reported to interested parties.
int ccnr_internal_client_start (struct ccnr_handle *ccnr)
void ccnr_internal_client_stop (struct ccnr_handle *ccnr)
static int ccnr_direct_client_refresh (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
int ccnr_direct_client_start (struct ccnr_handle *ccnr)
void ccnr_direct_client_stop (struct ccnr_handle *ccnr)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_internal_client.c.
Define Documentation
#define CCNR_ID_TEMPL 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
Definition at line 276 of file ccnr_internal_client.c.
Referenced by ccnr_uri_listen().
#define CCNR_KEYSTORE_PASS 'Th1s 1s n0t 8 g00d R3p0s1t0ry p8ssw0rd!'
Definition at line 321 of file ccnr_internal_client.c.
Referenced by ccnr_init_repo_keystore().
Function Documentation
PUBLIC enum ccn_upcall_res ccnr_answer_req (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Common interest handler.
Definition at line 100 of file ccnr_internal_client.c.
Referenced by r_init_create().
static int ccnr_direct_client_refresh (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 520 of file ccnr_internal_client.c.
Referenced by ccnr_direct_client_start().
int ccnr_direct_client_start (struct ccnr_handle * ccnr)
Definition at line 546 of file ccnr_internal_client.c.
Referenced by r_init_create().
void ccnr_direct_client_stop (struct ccnr_handle * ccnr)
Definition at line 560 of file ccnr_internal_client.c.
Referenced by r_init_destroy().
void ccnr_face_status_change (struct ccnr_handle * ccnr, unsigned filedesc)
Called by ccnr when a fdholder undergoes a substantive status change that should be reported to interested parties. In the destroy case, this is called from the hash table finalizer, so it shouldn't do much directly. Inspecting the fdholder is OK, though.
Definition at line 471 of file ccnr_internal_client.c.
Referenced by r_io_register_new_face(), and r_link_do_deferred_write().
int ccnr_init_repo_keystore (struct ccnr_handle * ccnr, struct ccn * h)
Create the repository keystore if necessary, and load it into the client handle h. It is permitted for h to be NULL to skip the load.
Returns:
-1 if there were problems.
Definition at line 333 of file ccnr_internal_client.c.
Referenced by ccnr_direct_client_start(), ccnr_internal_client_start(), and r_init_create().
static struct ccn_charbuf* ccnr_init_service_ccnb (struct ccnr_handle * ccnr, struct ccn * h, const char * baseuri, int freshness) [static, read]
Definition at line 50 of file ccnr_internal_client.c.
Referenced by ccnr_answer_req().
static int ccnr_internal_client_refresh (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 257 of file ccnr_internal_client.c.
Referenced by ccnr_internal_client_start().
int ccnr_internal_client_start (struct ccnr_handle * ccnr)
Definition at line 484 of file ccnr_internal_client.c.
Referenced by r_init_create().
void ccnr_internal_client_stop (struct ccnr_handle * ccnr)
Definition at line 502 of file ccnr_internal_client.c.
Referenced by r_io_shutdown_all().
static int ccnr_notice_push (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 431 of file ccnr_internal_client.c.
Referenced by ccnr_face_status_change().
PUBLIC void ccnr_uri_listen (struct ccnr_handle * ccnr, struct ccn * ccn, const char * uri, ccn_handler p, intptr_t intdata)
Definition at line 279 of file ccnr_internal_client.c.
Referenced by r_init_create().
static int post_face_notice (struct ccnr_handle * ccnr, unsigned filedesc) [static]
Definition at line 402 of file ccnr_internal_client.c.
Referenced by ccnr_notice_push().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.