ccnr/ccnr_net.h
NAME
ccnr/ccnr_net.h -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
void r_net_setsockopt_v6only (struct ccnr_handle *h, int fd)
char * r_net_get_local_sockname (void)
int r_net_listen_on (struct ccnr_handle *h, const char *addrs)
int r_net_listen_on_address (struct ccnr_handle *h, const char *addr)
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_net.h.
Function Documentation
char* r_net_get_local_sockname (void)
Definition at line 52 of file ccnr_net.c.
Referenced by r_init_create().
int r_net_listen_on (struct ccnr_handle * h, const char * addrs)
Definition at line 133 of file ccnr_net.c.
Referenced by r_init_create().
int r_net_listen_on_address (struct ccnr_handle * h, const char * addr)
Definition at line 86 of file ccnr_net.c.
Referenced by r_net_listen_on().
void r_net_setsockopt_v6only (struct ccnr_handle * h, int fd)
Definition at line 60 of file ccnr_net.c.
Referenced by r_net_listen_on_address().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.