ccnr/ccnr_init.h
NAME
ccnr/ccnr_init.h -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Functions
struct ccnr_parsed_policy * ccnr_parsed_policy_create (void)
void ccnr_parsed_policy_destroy (struct ccnr_parsed_policy **ppp)
struct ccnr_handle * r_init_create (const char *progname, ccnr_logger logger, void *loggerdata)
Create a new ccnr instance.
void r_init_fail (struct ccnr_handle *, int, const char *, int)
void r_init_destroy (struct ccnr_handle **pccnr)
Destroy the ccnr instance, releasing all associated resources.
int r_init_map_and_process_file (struct ccnr_handle *h, struct ccn_charbuf *filename, int add_content)
struct ccn_charbuf * ccnr_init_policy_link_cob (struct ccnr_handle *ccnr, struct ccn *h, struct ccn_charbuf *targetname)
should probably return a new cob, rather than reusing one.
intmax_t r_init_confval (struct ccnr_handle *h, const char *key, intmax_t lo, intmax_t hi, intmax_t deflt)
Get the specified numerical config value, subject to limits.
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_init.h.
Function Documentation
struct ccn_charbuf* ccnr_init_policy_link_cob (struct ccnr_handle * ccnr, struct ccn * h, struct ccn_charbuf * targetname) [read]
should probably return a new cob, rather than reusing one. should publish link as: CCNRID_POLICY_URI("ccnx:/C1.M.S.localhost/C1.M.SRV/repository/POLICY)/C1.M.K<pubid>/<version>/00 should have key locator which is the key name of the repository
Definition at line 860 of file ccnr_init.c.
Referenced by load_policy(), and r_proto_policy_update().
struct ccnr_parsed_policy* ccnr_parsed_policy_create (void) [read]
Definition at line 438 of file ccnr_init.c.
Referenced by load_policy(), and r_proto_policy_update().
void ccnr_parsed_policy_destroy (struct ccnr_parsed_policy ** ppp)
Definition at line 448 of file ccnr_init.c.
Referenced by r_proto_policy_update().
intmax_t r_init_confval (struct ccnr_handle * h, const char * key, intmax_t lo, intmax_t hi, intmax_t deflt)
Get the specified numerical config value, subject to limits.
Definition at line 167 of file ccnr_init.c.
Referenced by r_init_create(), and r_store_init().
struct ccnr_handle* r_init_create (const char * progname, ccnr_logger logger, void * loggerdata) [read]
Create a new ccnr instance. Parameters:
progname - name of program binary, used for locating helpers
logger - logger function
loggerdata - data to pass to logger function
Definition at line 468 of file ccnr_init.c.
void r_init_destroy (struct ccnr_handle ** pccnr)
Destroy the ccnr instance, releasing all associated resources.
Definition at line 653 of file ccnr_init.c.
void r_init_fail (struct ccnr_handle *, int, const char *, int)
Definition at line 638 of file ccnr_init.c.
Referenced by load_policy(), r_init_create(), r_init_read_config(), and r_store_init().
int r_init_map_and_process_file (struct ccnr_handle * h, struct ccn_charbuf * filename, int add_content)
Definition at line 711 of file ccnr_init.c.
Referenced by merge_files(), and r_proto_bulk_import().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.