ccnr/ccnr_internal_client.h
NAME
ccnr/ccnr_internal_client.h -
Part of ccnr - CCNx Repository Daemon.
SYNOPSIS
Defines
#define MORECOMPS_MASK 0x007F
Local interpretation of selfp->intdata.
#define MUST_VERIFY 0x0080
#define MUST_VERIFY1 (MUST_VERIFY + 1)
#define OPER_MASK 0xFF00
#define OP_PING 0x0000
#define OP_NEWFACE 0x0200
#define OP_DESTROYFACE 0x0300
#define OP_PREFIXREG 0x0400
#define OP_SELFREG 0x0500
#define OP_UNREG 0x0600
#define OP_NOTICE 0x0700
#define OP_SERVICE 0x0800
Functions
void ccnr_internal_client_stop (struct ccnr_handle *ccnr)
int ccnr_internal_client_start (struct ccnr_handle *ccnr)
void ccnr_face_status_change (struct ccnr_handle *ccnr, unsigned filedesc)
Called by ccnr when a fdholder undergoes a substantive status change that should be reported to interested parties.
int ccnr_init_repo_keystore (struct ccnr_handle *ccnr, struct ccn *ccn)
Create the repository keystore if necessary, and load it into the client handle h.
void ccnr_direct_client_stop (struct ccnr_handle *ccnr)
int ccnr_direct_client_start (struct ccnr_handle *ccnr)
void ccnr_uri_listen (struct ccnr_handle *ccnr, struct ccn *ccn, const char *uri, ccn_handler p, intptr_t intdata)
enum ccn_upcall_res ccnr_answer_req (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Common interest handler.
Detailed Description
Part of ccnr - CCNx Repository Daemon.
Definition in file ccnr_internal_client.h.
Define Documentation
#define MORECOMPS_MASK 0x007F
Local interpretation of selfp->intdata.
Definition at line 39 of file ccnr_internal_client.h.
#define MUST_VERIFY 0x0080
Definition at line 40 of file ccnr_internal_client.h.
#define MUST_VERIFY1 (MUST_VERIFY + 1)
Definition at line 41 of file ccnr_internal_client.h.
#define OP_DESTROYFACE 0x0300
Definition at line 45 of file ccnr_internal_client.h.
#define OP_NEWFACE 0x0200
Definition at line 44 of file ccnr_internal_client.h.
#define OP_NOTICE 0x0700
Definition at line 49 of file ccnr_internal_client.h.
#define OP_PING 0x0000
Definition at line 43 of file ccnr_internal_client.h.
#define OP_PREFIXREG 0x0400
Definition at line 46 of file ccnr_internal_client.h.
#define OP_SELFREG 0x0500
Definition at line 47 of file ccnr_internal_client.h.
#define OP_SERVICE 0x0800
Definition at line 50 of file ccnr_internal_client.h.
#define OP_UNREG 0x0600
Definition at line 48 of file ccnr_internal_client.h.
#define OPER_MASK 0xFF00
Definition at line 42 of file ccnr_internal_client.h.
Function Documentation
enum ccn_upcall_res ccnr_answer_req (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info)
Common interest handler.
Definition at line 100 of file ccnr_internal_client.c.
Referenced by r_init_create().
int ccnr_direct_client_start (struct ccnr_handle * ccnr)
Definition at line 546 of file ccnr_internal_client.c.
Referenced by r_init_create().
void ccnr_direct_client_stop (struct ccnr_handle * ccnr)
Definition at line 560 of file ccnr_internal_client.c.
Referenced by r_init_destroy().
void ccnr_face_status_change (struct ccnr_handle * ccnr, unsigned filedesc)
Called by ccnr when a fdholder undergoes a substantive status change that should be reported to interested parties. In the destroy case, this is called from the hash table finalizer, so it shouldn't do much directly. Inspecting the fdholder is OK, though.
Definition at line 471 of file ccnr_internal_client.c.
Referenced by r_io_register_new_face(), and r_link_do_deferred_write().
int ccnr_init_repo_keystore (struct ccnr_handle * ccnr, struct ccn * h)
Create the repository keystore if necessary, and load it into the client handle h. It is permitted for h to be NULL to skip the load.
Returns:
-1 if there were problems.
Definition at line 333 of file ccnr_internal_client.c.
Referenced by ccnr_direct_client_start(), ccnr_internal_client_start(), and r_init_create().
int ccnr_internal_client_start (struct ccnr_handle * ccnr)
Definition at line 484 of file ccnr_internal_client.c.
Referenced by r_init_create().
void ccnr_internal_client_stop (struct ccnr_handle * ccnr)
Definition at line 502 of file ccnr_internal_client.c.
Referenced by r_io_shutdown_all().
void ccnr_uri_listen (struct ccnr_handle * ccnr, struct ccn * ccn, const char * uri, ccn_handler p, intptr_t intdata)
Definition at line 279 of file ccnr_internal_client.c.
Referenced by r_init_create().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.