cmd/ccnsyncwatch.c
NAME
cmd/ccnsyncwatch.c -
Utility to use the Sync library protocol to watch changes in a repository's contents.
SYNOPSIS
Functions
char * hex_string (unsigned char *s, size_t l)
int hex_value (char c)
void usage (char *prog)
int sync_cb (struct ccns_name_closure *nc, struct ccn_charbuf *lhash, struct ccn_charbuf *rhash, struct ccn_charbuf *name)
int main (int argc, char **argv)
Detailed Description
Utility to use the Sync library protocol to watch changes in a repository's contents.
A CCNx program.
Copyright (C) 2012 Palo Alto Research Center, Inc.
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
Definition in file ccnsyncwatch.c.
Function Documentation
char* hex_string (unsigned char * s, size_t l)
Definition at line 33 of file ccnsyncwatch.c.
Referenced by sync_cb().
int hex_value (char c)
Definition at line 46 of file ccnsyncwatch.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 97 of file ccnsyncwatch.c.
int sync_cb (struct ccns_name_closure * nc, struct ccn_charbuf * lhash, struct ccn_charbuf * rhash, struct ccn_charbuf * name)
Definition at line 68 of file ccnsyncwatch.c.
Referenced by main().
void usage (char * prog)
Definition at line 54 of file ccnsyncwatch.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.