.TH "cmd/ccnsyncslice.c" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmd/ccnsyncslice.c \- 
.PP
Utility to use the Sync library to create or delete sync configuration slices.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBusage\fP (char *prog)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Utility to use the Sync library to create or delete sync configuration slices. 

A CCNx program.
.PP
Copyright (C) 2012 Palo Alto Research Center, Inc.
.PP
This work is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License version 2 as published by the Free Software Foundation. This work is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details. You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA. 
.PP
Definition in file \fBccnsyncslice.c\fP.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"
.PP
Definition at line 41 of file ccnsyncslice.c.
.SS "void usage (char * prog)"
.PP
Definition at line 32 of file ccnsyncslice.c.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
