.TH "ccns_name_closure" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ccns_name_closure \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBccns_callback\fP \fBcallback\fP"
.br
.ti -1c
.RI "struct ccns_handle * \fBccns\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.ti -1c
.RI "uint64_t \fBcount\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file sync.h.
.SH "Field Documentation"
.PP 
.SS "\fBccns_callback\fP \fBccns_name_closure::callback\fP"
.PP
Definition at line 51 of file sync.h.
.PP
Referenced by ccns_open(), and main().
.SS "struct ccns_handle* \fBccns_name_closure::ccns\fP"
.PP
Definition at line 52 of file sync.h.
.PP
Referenced by ccns_open().
.SS "uint64_t \fBccns_name_closure::count\fP"
.PP
Definition at line 54 of file sync.h.
.SS "void* \fBccns_name_closure::data\fP"
.PP
Definition at line 53 of file sync.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
