.TH "content_by_accession_entry" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
content_by_accession_entry \- 
.PP
The content_by_accession hash table, keyed by accession, holds entries that have a known accession.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBcontent_entry\fP * \fBcontent\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The content_by_accession hash table, keyed by accession, holds entries that have a known accession. 
.PP
Definition at line 361 of file ccnr_private.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBcontent_entry\fP* \fBcontent_by_accession_entry::content\fP"
.PP
Definition at line 362 of file ccnr_private.h.
.PP
Referenced by finalize_accession(), r_store_content_from_accession(), r_store_enroll_content(), r_store_look(), and r_store_set_accession_from_offset().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
