.TH "enum_state" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
enum_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBname\fP"
.br
.ti -1c
.RI "struct \fBcontent_entry\fP * \fBcontent\fP"
.br
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBreply_body\fP"
.br
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBinterest\fP"
.br
.ti -1c
.RI "struct \fBccn_indexbuf\fP * \fBinterest_comps\fP"
.br
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBcob\fP [ENUM_N_COBS]"
.br
.ti -1c
.RI "int \fBcob_deferred\fP [ENUM_N_COBS]"
.br
.ti -1c
.RI "intmax_t \fBnext_segment\fP"
.br
.ti -1c
.RI "\fBccnr_cookie\fP \fBstarting_cookie\fP"
.br
.ti -1c
.RI "enum \fBes_active_state\fP \fBactive\fP"
.br
.ti -1c
.RI "long \fBlifetime\fP"
.br
.ti -1c
.RI "long \fBlastuse_sec\fP"
.br
.ti -1c
.RI "unsigned \fBlastuse_usec\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 438 of file ccnr_private.h.
.SH "Field Documentation"
.PP 
.SS "enum \fBes_active_state\fP \fBenum_state::active\fP"
.PP
Definition at line 448 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_dump_enums(), and reap_enumerations().
.SS "struct \fBccn_charbuf\fP* \fBenum_state::cob\fP[ENUM_N_COBS]"
.PP
Definition at line 444 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and r_proto_finalize_enum_state().
.SS "int \fBenum_state::cob_deferred\fP[ENUM_N_COBS]"
.PP
Definition at line 445 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), and r_proto_continue_enumeration().
.SS "struct \fBcontent_entry\fP* \fBenum_state::content\fP"
.PP
Definition at line 440 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), and r_proto_continue_enumeration().
.SS "struct \fBccn_charbuf\fP* \fBenum_state::interest\fP"
.PP
Definition at line 442 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and r_proto_finalize_enum_state().
.SS "struct \fBccn_indexbuf\fP* \fBenum_state::interest_comps\fP"
.PP
Definition at line 443 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and r_proto_finalize_enum_state().
.SS "long \fBenum_state::lastuse_sec\fP"
.PP
Definition at line 450 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and reap_enumerations().
.SS "unsigned \fBenum_state::lastuse_usec\fP"
.PP
Definition at line 451 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and reap_enumerations().
.SS "long \fBenum_state::lifetime\fP"
.PP
Definition at line 449 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), and reap_enumerations().
.SS "struct \fBccn_charbuf\fP* \fBenum_state::name\fP"
.PP
Definition at line 439 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), r_proto_dump_enums(), r_proto_finalize_enum_state(), and reap_enumerations().
.SS "intmax_t \fBenum_state::next_segment\fP"
.PP
Definition at line 446 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and r_proto_dump_enums().
.SS "struct \fBccn_charbuf\fP* \fBenum_state::reply_body\fP"
.PP
Definition at line 441 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), r_proto_continue_enumeration(), and r_proto_finalize_enum_state().
.SS "\fBccnr_cookie\fP \fBenum_state::starting_cookie\fP"
.PP
Definition at line 447 of file ccnr_private.h.
.PP
Referenced by r_proto_begin_enumeration(), and r_proto_dump_enums().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
