include/ccn/face_mgmt.h
NAME
include/ccn/face_mgmt.h -
Part of the CCNx C Library.
SYNOPSIS
Data Structures
struct ccn_face_instance
Defines
#define CCN_NO_FACEID (~0U)
Functions
struct ccn_face_instance * ccn_face_instance_parse (const unsigned char *p, size_t size)
Parse a ccnb-ecoded FaceInstance into an internal representation.
void ccn_face_instance_destroy (struct ccn_face_instance **)
Destroy the result of ccn_face_instance_parse().
int ccnb_append_face_instance (struct ccn_charbuf *, const struct ccn_face_instance *)
Marshal an internal face instance representation into ccnb form.
Detailed Description
Part of the CCNx C Library.
Copyright (C) 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file face_mgmt.h.
Define Documentation
#define CCN_NO_FACEID (~0U)
Definition at line 27 of file face_mgmt.h.
Function Documentation
void ccn_face_instance_destroy (struct ccn_face_instance **)
Destroy the result of ccn_face_instance_parse().
Definition at line 109 of file ccn_face_mgmt.c.
Referenced by ccn_face_instance_parse(), ccnd_req_destroyface(), ccnd_req_newface(), ccndc_add(), ccndc_create(), ccndc_del(), ccndc_destroy(), ccndc_destroyface(), ccndc_do_face_action(), ccndc_renew(), ccndc_srv(), main(), parse_ccn_face_instance(), and parse_ccn_face_instance_from_face().
struct ccn_face_instance* ccn_face_instance_parse (const unsigned char * p, size_t size) [read]
Parse a ccnb-ecoded FaceInstance into an internal representation. The space used for the various strings is held by the charbuf. A client may replace the strings with other pointers, but then assumes responsibilty for managing those pointers.
Returns:
pointer to newly allocated structure describing the face, or NULL if there is an error.
Definition at line 41 of file ccn_face_mgmt.c.
Referenced by ccnd_req_destroyface(), ccnd_req_newface(), ccndc_do_face_action(), and main().
int ccnb_append_face_instance (struct ccn_charbuf *, const struct ccn_face_instance *)
Marshal an internal face instance representation into ccnb form.
Definition at line 123 of file ccn_face_mgmt.c.
Referenced by ccnd_req_destroyface(), ccnd_req_newface(), ccndc_do_face_action(), and main().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.