.TH "guest_entry" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
guest_entry \- 
.PP
The guest hash table is keyed by the faceid of the requestor.  

.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBcob\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The guest hash table is keyed by the faceid of the requestor. 

The cob is an answer for the request. 
.PP
Definition at line 339 of file ccnd_private.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBccn_charbuf\fP* \fBguest_entry::cob\fP"
.PP
Definition at line 340 of file ccnd_private.h.
.PP
Referenced by ccnd_req_guest(), and finalize_guest().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
