sync/IndexSorter.c
NAME
sync/IndexSorter.c -
IndexSorter.c.
SYNOPSIS
Functions
IndexSorter_Base IndexSorter_New (IndexSorter_Index lim, IndexSorter_Index empty)
void IndexSorter_Add (IndexSorter_Base base, IndexSorter_Index x)
IndexSorter_Index IndexSorter_Rem (IndexSorter_Base base)
IndexSorter_Index IndexSorter_Best (IndexSorter_Base base)
void IndexSorter_Reset (IndexSorter_Base base)
void IndexSorter_Free (IndexSorter_Base *basePtr)
Detailed Description
IndexSorter.c.
Part of the CCNx C Library.
Copyright (C) 2011 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file IndexSorter.c.
Function Documentation
void IndexSorter_Add (IndexSorter_Base base, IndexSorter_Index x)
Definition at line 37 of file IndexSorter.c.
Referenced by SyncSortNames(), testReader(), and UpdateAction().
IndexSorter_Index IndexSorter_Best (IndexSorter_Base base)
Definition at line 105 of file IndexSorter.c.
Referenced by AdvanceName(), BestName(), and SyncTreeMergeNames().
void IndexSorter_Free (IndexSorter_Base * basePtr)
Definition at line 116 of file IndexSorter.c.
Referenced by SyncSortNames(), testReader(), and UpdateAction().
IndexSorter_Base IndexSorter_New (IndexSorter_Index lim, IndexSorter_Index empty)
Definition at line 27 of file IndexSorter.c.
Referenced by SyncSortNames(), SyncUpdateRoot(), and testReader().
IndexSorter_Index IndexSorter_Rem (IndexSorter_Base base)
Definition at line 66 of file IndexSorter.c.
Referenced by AdvanceName(), SyncSortNames(), SyncTreeMergeNames(), and testReader().
void IndexSorter_Reset (IndexSorter_Base base)
Definition at line 111 of file IndexSorter.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.