sync/IndexSorter.h
NAME
sync/IndexSorter.h -
SYNOPSIS
Data Structures
struct IndexSorter_Struct
Typedefs
typedef uintmax_t IndexSorter_Index
typedef struct IndexSorter_Struct * IndexSorter_Base
typedef int IndexSorter_sorter (IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
Functions
IndexSorter_Base IndexSorter_New (IndexSorter_Index lim, IndexSorter_Index empty)
void IndexSorter_Add (IndexSorter_Base base, IndexSorter_Index x)
IndexSorter_Index IndexSorter_Rem (IndexSorter_Base base)
IndexSorter_Index IndexSorter_Best (IndexSorter_Base base)
void IndexSorter_Reset (IndexSorter_Base base)
void IndexSorter_Free (IndexSorter_Base *basePtr)
Typedef Documentation
typedef struct IndexSorter_Struct* IndexSorter_Base
Definition at line 40 of file IndexSorter.h.
typedef uintmax_t IndexSorter_Index
Definition at line 36 of file IndexSorter.h.
typedef int IndexSorter_sorter(IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
Definition at line 43 of file IndexSorter.h.
Function Documentation
void IndexSorter_Add (IndexSorter_Base base, IndexSorter_Index x)
Definition at line 37 of file IndexSorter.c.
Referenced by SyncSortNames(), testReader(), and UpdateAction().
IndexSorter_Index IndexSorter_Best (IndexSorter_Base base)
Definition at line 105 of file IndexSorter.c.
Referenced by AdvanceName(), BestName(), and SyncTreeMergeNames().
void IndexSorter_Free (IndexSorter_Base * basePtr)
Definition at line 116 of file IndexSorter.c.
Referenced by SyncSortNames(), testReader(), and UpdateAction().
IndexSorter_Base IndexSorter_New (IndexSorter_Index lim, IndexSorter_Index empty)
Definition at line 27 of file IndexSorter.c.
Referenced by SyncSortNames(), SyncUpdateRoot(), and testReader().
IndexSorter_Index IndexSorter_Rem (IndexSorter_Base base)
Definition at line 66 of file IndexSorter.c.
Referenced by AdvanceName(), SyncSortNames(), SyncTreeMergeNames(), and testReader().
void IndexSorter_Reset (IndexSorter_Base base)
Definition at line 111 of file IndexSorter.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.