include/ccn/schedule.h
NAME
include/ccn/schedule.h -
Event scheduling.
SYNOPSIS
Data Structures
struct ccn_timeval
struct ccn_gettime
struct ccn_scheduled_event
Defines
#define CCN_SCHEDULE_CANCEL 0x10
Typedefs
typedef void(* ccn_gettime_action )(const struct ccn_gettime *, struct ccn_timeval *)
typedef int(* ccn_scheduled_action )(struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Functions
struct ccn_schedule * ccn_schedule_create (void *clienth, const struct ccn_gettime *ccnclock)
void ccn_schedule_destroy (struct ccn_schedule **schedp)
struct ccn_gettime * ccn_schedule_get_gettime (struct ccn_schedule *)
struct ccn_scheduled_event * ccn_schedule_event (struct ccn_schedule *sched, int micros, ccn_scheduled_action action, void *evdata, intptr_t evint)
int ccn_schedule_cancel (struct ccn_schedule *, struct ccn_scheduled_event *)
Cancel a scheduled event.
int ccn_schedule_run (struct ccn_schedule *)
Detailed Description
Event scheduling.
Part of the CCNx C Library.
Copyright (C) 2008, 2009 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file schedule.h.
Define Documentation
#define CCN_SCHEDULE_CANCEL 0x10
Definition at line 59 of file schedule.h.
Referenced by adjacency_do_refresh(), adjacency_do_reset(), age_forwarding(), ccn_schedule_cancel(), ccn_schedule_destroy(), ccnd_do_solicit(), ccnd_flush_guid_cob(), ccnd_internal_client_refresh(), ccnd_notice_push(), ccnr_direct_client_refresh(), ccnr_internal_client_refresh(), ccnr_notice_push(), clean_daemon(), clean_guest(), CompareAction(), compareAction(), content_sender(), do_propagate(), each_round(), expire_content(), fill_holes(), HeartbeatAction(), process_icb_action(), r_proto_policy_update(), r_store_index_cleaner(), r_store_reindexing(), r_sync_enumerate_action(), reap(), reap_enumerations(), reporter(), strategy_timer(), and updateAction().
Typedef Documentation
typedef void(* ccn_gettime_action)(const struct ccn_gettime *, struct ccn_timeval *)
Definition at line 43 of file schedule.h.
typedef int(* ccn_scheduled_action)(struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
Definition at line 60 of file schedule.h.
Function Documentation
int ccn_schedule_cancel (struct ccn_schedule * sched, struct ccn_scheduled_event * ev)
Cancel a scheduled event. Cancels the event (calling action with CCN_SCHEDULE_CANCEL set)
Returns:
0 if OK, or -1 if this is not possible.
Definition at line 268 of file ccn_schedule.c.
Referenced by ccnd_internal_client_stop(), ccnr_direct_client_stop(), ccnr_internal_client_stop(), ccns_close(), content_queue_destroy(), destroyCompareData(), finalize_interest(), kickCompare(), kickUpdate(), propagate_interest(), r_sendq_content_queue_destroy(), resetDiffData(), resetUpdateData(), start_round(), strategy_settimer(), sync_diff_stop(), and update_npe_children().
struct ccn_schedule* ccn_schedule_create (void * clienth, const struct ccn_gettime * ccnclock) [read]
Definition at line 100 of file ccn_schedule.c.
Referenced by ccnd_create(), ccns_open(), main(), and r_init_create().
void ccn_schedule_destroy (struct ccn_schedule ** schedp)
Definition at line 116 of file ccn_schedule.c.
Referenced by ccn_destroy(), ccnd_destroy(), incoming_content(), main(), and r_init_destroy().
struct ccn_scheduled_event* ccn_schedule_event (struct ccn_schedule * sched, int micros, ccn_scheduled_action action, void * evdata, intptr_t evint) [read]
Definition at line 234 of file ccn_schedule.c.
Referenced by adjacency_timed_reset(), age_forwarding_needed(), ccnd_face_status_change(), ccnd_init_face_guid_cob(), ccnd_internal_client_has_somthing_to_say(), ccnd_internal_client_start(), ccnd_register_adjacency(), ccnd_req_guest(), ccnr_direct_client_start(), ccnr_face_status_change(), ccnr_internal_client_start(), clean_needed(), face_send_queue_insert(), kickCompare(), kickHeartBeat(), kickUpdate(), main(), propagate_interest(), r_proto_policy_complete(), r_sendq_face_send_queue_insert(), r_store_index_needs_cleaning(), r_store_init(), r_store_set_content_timer(), reap_enumerations_needed(), reap_needed(), schedule_adjacency_negotiation(), set_content_timer(), start_round(), strategy_settimer(), SyncStartHeartbeat(), SyncUpdateRoot(), update_npe_children(), and update_rtt().
struct ccn_gettime* ccn_schedule_get_gettime (struct ccn_schedule *) [read]
Definition at line 142 of file ccn_schedule.c.
int ccn_schedule_run (struct ccn_schedule *)
Definition at line 317 of file ccn_schedule.c.
Referenced by ccn_run(), ccnd_run(), main(), r_dispatch_run(), and r_init_create().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.