.TH "SyncNameAccumEntry" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncNameAccumEntry \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBccn_charbuf\fP * \fBname\fP"
.br
.ti -1c
.RI "intmax_t \fBdata\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 343 of file SyncUtil.h.
.SH "Field Documentation"
.PP 
.SS "intmax_t \fBSyncNameAccumEntry::data\fP"
.PP
Definition at line 345 of file SyncUtil.h.
.PP
Referenced by copyFilter(), SyncNameAccumAppend(), SyncNameAccumCanon(), SyncRegisterInterests(), SyncSortNames(), SyncTreeMergeNames(), and testReader().
.SS "struct \fBccn_charbuf\fP* \fBSyncNameAccumEntry::name\fP"
.PP
Definition at line 344 of file SyncUtil.h.
.PP
Referenced by AdvanceName(), appendExclusions(), BestName(), canonFilter(), CompareAction(), copyFilter(), MakeNodeFromNames(), merge_names(), node_from_names(), putFileList(), SyncAddName(), SyncFreeNameAccumAndNames(), SyncNameAccumAppend(), SyncNameAccumCanon(), SyncNameAccumSorter(), SyncRegisterInterests(), SyncRootAppendSlice(), SyncRootLookupName(), SyncSortNames(), SyncTreeMergeNames(), testReadBuilder(), testReader(), try_node_split(), TryNodeSplit(), and UpdateAction().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
