.TH "sync/sync_plumbing.h" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sync/sync_plumbing.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBsync_plumbing\fP"
.br
.ti -1c
.RI "struct \fBsync_plumbing_sync_methods\fP"
.br
.ti -1c
.RI "struct \fBsync_plumbing_client_methods\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
