sync/sync_diff.h
NAME
sync/sync_diff.h -
SYNOPSIS
Data Structures
struct sync_diff_add_closure
sync_diff_add_closure is called from the differencing operation to note a name difference for sdd.
struct sync_diff_fetch_data
struct sync_diff_get_closure
sync_diff_get_closure is called from the differencing operation when a node is required for a cache entry.
struct sync_diff_data
struct sync_done_closure
sync_done_closure is called from the update operation when the new tree root is ready for installation (in ud->ceStop).
struct sync_update_data
Enumerations
enum sync_diff_side { sync_diff_X, sync_diff_Y }
enum sync_diff_state { sync_diff_state_init, sync_diff_state_preload, sync_diff_state_busy, sync_diff_state_error, sync_diff_state_done }
enum sync_update_state { sync_update_state_init, sync_update_state_busy, sync_update_state_error, sync_update_state_done }
Functions
int sync_diff_start (struct sync_diff_data *sdd)
sync_diff_start starts a differencing operation between two sync trees, specified by sdd->hashX and sdd->hashY for the collection in sdd->root.
int sync_diff_note_node (struct sync_diff_data *sdd, struct SyncHashCacheEntry *ce)
sync_diff_note_node is used to establish the result of the client closure sdd->get, and restarts the comparison.
int sync_diff_stop (struct sync_diff_data *sdd)
sync_diff_stop will stop the differencing operation if it has not completed.
int sync_update_start (struct sync_update_data *ud, struct SyncNameAccum *acc)
sync_update_start is called to start an update of ud->ceStart, based on the names added via acc, to result in a tree with root hash stored in ud->ceStop.
int sync_update_stop (struct sync_update_data *ud)
sync_update_stop can be called to stop the update operation.
Enumeration Type Documentation
enum sync_diff_side
Enumerator:
sync_diff_X
sync_diff_Y
Definition at line 27 of file sync_diff.h.
enum sync_diff_state
Enumerator:
sync_diff_state_init
sync_diff_state_preload
sync_diff_state_busy
sync_diff_state_error
sync_diff_state_done
Definition at line 69 of file sync_diff.h.
enum sync_update_state
Enumerator:
sync_update_state_init
sync_update_state_busy
sync_update_state_error
sync_update_state_done
Definition at line 118 of file sync_diff.h.
Function Documentation
int sync_diff_note_node (struct sync_diff_data * sdd, struct SyncHashCacheEntry * ce)
sync_diff_note_node is used to establish the result of the client closure sdd->get, and restarts the comparison. When the client closure sdd->get is called it should initiate the fetch or construction of a sync tree node. Depending on characteristics of the client the sync tree node should be stored into either ce->ncL or ce->ncR, and sync_diff_note_node should be called. The flags in ce will be updated by sync_diff_note_node.
Returns:
< 0 for failure, no fetch queued for ce.
0 for no action, ce == NULL || ce has no node.
> 0 for success, fetch was queued and ce has a node.
Definition at line 1550 of file sync_diff.c.
Referenced by my_response().
int sync_diff_start (struct sync_diff_data * sdd)
sync_diff_start starts a differencing operation between two sync trees, specified by sdd->hashX and sdd->hashY for the collection in sdd->root. If sdd->hashX is not empty then there must be a valid cache entry for it. If sdd->hashY is not empty then there must be a valid cache entry for it. The root (in sdd->root) must be valid, and have a valid base and scheduler. The client always owns the storage for sdd.
The closure sdd->get is called when a sync tree node is needed to continue the comparison, giving the name of the node (which has the hash as the last component). When the node has been fetched, the client should call sync_diff_note_node, which will continue the comparison.
The closure sdd->add is called once for each name that is covered by hashY but not by hashX. When there are no more additions then it is called once with name == NULL. The sdd->add closure is called with a name that may not be valid after the call completes, so the client must copy the name if it needs to persist.
Hint: If sdd->hashX is the empty hash (NULL or length == 0), then the differencing operation is simply an enumeration operation.
Returns:
< 0 for failure, 0 if no difference running, > 0 for success.
Definition at line 1516 of file sync_diff.c.
Referenced by each_round().
int sync_diff_stop (struct sync_diff_data * sdd)
sync_diff_stop will stop the differencing operation if it has not completed. A call to sdd->add will NOT take place from within this call. Internal resources are released.
Returns:
< 0 for failure, 0 if already stopped, > 0 for success.
Definition at line 1608 of file sync_diff.c.
Referenced by ccns_close().
int sync_update_start (struct sync_update_data * ud, struct SyncNameAccum * acc)
sync_update_start is called to start an update of ud->ceStart, based on the names added via acc, to result in a tree with root hash stored in ud->ceStop. Returns:
< 0 for failure, 0 if update already running, > 0 for success.
Definition at line 1624 of file sync_diff.c.
Referenced by each_round().
int sync_update_stop (struct sync_update_data * ud)
sync_update_stop can be called to stop the update operation. Internal resources are released.
Returns:
< 0 for failure, 0 if no update running, > 0 for success.
Definition at line 1665 of file sync_diff.c.
Referenced by ccns_close().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.