sync_plumbing_client_methods
NAME
sync_plumbing_client_methods -
SYNOPSIS
Data Fields
void(* r_sync_msg )(struct sync_plumbing *sd, const char *fmt,...)
int(* r_sync_fence )(struct sync_plumbing *sd, uint64_t seq_num)
int(* r_sync_enumerate )(struct sync_plumbing *sd, struct ccn_charbuf *interest)
int(* r_sync_lookup )(struct sync_plumbing *sd, struct ccn_charbuf *interest, struct ccn_charbuf *content)
int(* r_sync_local_store )(struct sync_plumbing *sd, struct ccn_charbuf *content)
enum ccn_upcall_res(* r_sync_upcall_store )(struct sync_plumbing *sd, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Detailed Description
Definition at line 85 of file sync_plumbing.h.
Field Documentation
int(* sync_plumbing_client_methods::r_sync_enumerate)(struct sync_plumbing *sd, struct ccn_charbuf *interest)
Definition at line 104 of file sync_plumbing.h.
Referenced by SyncStartHeartbeat(), and SyncStartSliceEnum().
int(* sync_plumbing_client_methods::r_sync_fence)(struct sync_plumbing *sd, uint64_t seq_num)
Definition at line 95 of file sync_plumbing.h.
Referenced by setFence().
int(* sync_plumbing_client_methods::r_sync_local_store)(struct sync_plumbing *sd, struct ccn_charbuf *content)
Definition at line 120 of file sync_plumbing.h.
Referenced by SyncLocalRepoStore().
int(* sync_plumbing_client_methods::r_sync_lookup)(struct sync_plumbing *sd, struct ccn_charbuf *interest, struct ccn_charbuf *content)
Definition at line 111 of file sync_plumbing.h.
Referenced by start_node_fetch(), SyncHandleSlice(), SyncLocalRepoFetch(), and SyncStartContentFetch().
void(* sync_plumbing_client_methods::r_sync_msg)(struct sync_plumbing *sd, const char *fmt,...)
Definition at line 87 of file sync_plumbing.h.
Referenced by sync_msg().
enum ccn_upcall_res(* sync_plumbing_client_methods::r_sync_upcall_store)(struct sync_plumbing *sd, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
Definition at line 128 of file sync_plumbing.h.
Referenced by SyncRemoteFetchResponse().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.