.TH "SyncNameAccumList" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncNameAccumList \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBSyncNameAccumList\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBSyncNameAccum\fP * \fBaccum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 354 of file SyncUtil.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBSyncNameAccum\fP* \fBSyncNameAccumList::accum\fP"
.PP
Definition at line 356 of file SyncUtil.h.
.PP
Referenced by canonFilter(), and SyncFreeBase().
.SS "struct \fBSyncNameAccumList\fP* \fBSyncNameAccumList::next\fP"
.PP
Definition at line 355 of file SyncUtil.h.
.PP
Referenced by canonFilter(), and SyncFreeBase().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
