.TH "SyncNodeAccum" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncNodeAccum \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlen\fP"
.br
.ti -1c
.RI "int \fBlim\fP"
.br
.ti -1c
.RI "struct \fBSyncNodeComposite\fP ** \fBents\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 406 of file SyncUtil.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBSyncNodeComposite\fP** \fBSyncNodeAccum::ents\fP"
.PP
Definition at line 409 of file SyncUtil.h.
.PP
Referenced by node_from_nodes(), nodeFromNodes(), SyncAccumNode(), SyncAllocNodeAccum(), and SyncFreeNodeAccum().
.SS "int \fBSyncNodeAccum::len\fP"
.PP
Definition at line 407 of file SyncUtil.h.
.PP
Referenced by node_from_nodes(), nodeFromNodes(), and SyncAccumNode().
.SS "int \fBSyncNodeAccum::lim\fP"
.PP
Definition at line 408 of file SyncUtil.h.
.PP
Referenced by SyncAccumNode(), and SyncAllocNodeAccum().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
