sync/SyncHashCache.c
NAME
sync/SyncHashCache.c -
Part of CCNx Sync.
SYNOPSIS
Functions
static struct SyncHashCacheEntry * localFreeEntry (struct SyncHashCacheEntry *ce)
struct SyncHashCacheEntry * SyncHashLookup (struct SyncHashCacheHead *head, const unsigned char *xp, ssize_t xs)
lookup a full hash in a hash table (raw contents, no tag)
struct SyncHashCacheEntry * SyncHashEnter (struct SyncHashCacheHead *head, const unsigned char *xp, ssize_t xs, enum SyncHashState set)
based on the raw hash, ensure that a remote cache entry exists ent->state |= set
void SyncHashRemoveEntry (struct SyncHashCacheHead *head, struct SyncHashCacheEntry *ce)
remove the entry (if present)
void SyncHashClearMarks (struct SyncHashCacheHead *head)
clear all marks
struct SyncHashCacheHead * SyncHashCacheCreate (struct SyncRootStruct *root, uint32_t mod)
create a new hash table with the given modulus (mod == 0 uses a default)
struct SyncHashCacheHead * SyncHashCacheFree (struct SyncHashCacheHead *head)
frees the cache resources caller must ensure no further use of the cache
int SyncCacheEntryStore (struct SyncHashCacheEntry *ce)
stores the cahe entry to the repo to be eligible, ce != NULL && ce->ncL == NULL && (ce->state & SyncHashState_stored) == 0
int SyncCacheEntryFetch (struct SyncHashCacheEntry *ce)
fetches the cache entry to be eligible, ce != NULL && ce->ncL != NULL && (ce->state & SyncHashState_stored) == 1
Detailed Description
Part of CCNx Sync.
Definition in file SyncHashCache.c.
Function Documentation
static struct SyncHashCacheEntry* localFreeEntry (struct SyncHashCacheEntry * ce) [static, read]
Definition at line 33 of file SyncHashCache.c.
Referenced by SyncHashCacheFree(), and SyncHashRemoveEntry().
int SyncCacheEntryFetch (struct SyncHashCacheEntry * ce)
fetches the cache entry to be eligible, ce != NULL && ce->ncL != NULL && (ce->state & SyncHashState_stored) == 1 Returns:
< 0 for failure, 0 if not eligible, and > 0 for success
Definition at line 208 of file SyncHashCache.c.
Referenced by cacheEntryForElem(), doComparison(), formatStats(), newNodeCommon(), sync_update_start(), SyncInterestArrived(), UpdateAction(), and updateAction().
int SyncCacheEntryStore (struct SyncHashCacheEntry * ce)
stores the cahe entry to the repo to be eligible, ce != NULL && ce->ncL == NULL && (ce->state & SyncHashState_stored) == 0 Returns:
< 0 for failure, 0 if not eligible, and > 0 for success
Definition at line 175 of file SyncHashCache.c.
Referenced by HeartbeatAction().
struct SyncHashCacheHead* SyncHashCacheCreate (struct SyncRootStruct * root, uint32_t mod) [read]
create a new hash table with the given modulus (mod == 0 uses a default)
Definition at line 143 of file SyncHashCache.c.
Referenced by SyncAddRoot().
struct SyncHashCacheHead* SyncHashCacheFree (struct SyncHashCacheHead * head) [read]
frees the cache resources caller must ensure no further use of the cache Returns:
NULL
Definition at line 153 of file SyncHashCache.c.
Referenced by SyncRemRoot().
void SyncHashClearMarks (struct SyncHashCacheHead * head)
clear all marks
Definition at line 129 of file SyncHashCache.c.
Referenced by purgeOldEntries().
struct SyncHashCacheEntry* SyncHashEnter (struct SyncHashCacheHead * head, const unsigned char * xp, ssize_t xs, enum SyncHashState set) [read]
based on the raw hash, ensure that a remote cache entry exists ent->state |= set
Definition at line 63 of file SyncHashCache.c.
Referenced by advise_interest_arrived(), cacheEntryForElem(), ensureRemoteEntry(), my_response(), newNodeCommon(), SyncInterestArrived(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartCompareAction(), UpdateAction(), and updateAction().
struct SyncHashCacheEntry* SyncHashLookup (struct SyncHashCacheHead * head, const unsigned char * xp, ssize_t xs) [read]
lookup a full hash in a hash table (raw contents, no tag) Returns:
entry if it exists
Definition at line 43 of file SyncHashCache.c.
Referenced by cacheEntryForElem(), CompareAction(), doPreload(), entryForHash(), MakeNodeFromNames(), newNodeCommon(), node_from_names(), nodeFromNodes(), SyncRemoteFetchResponse(), SyncRootTopEntry(), and SyncTreeWorkerPush().
void SyncHashRemoveEntry (struct SyncHashCacheHead * head, struct SyncHashCacheEntry * ce)
remove the entry (if present)
Definition at line 105 of file SyncHashCache.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.