sync/SyncUtil.c
NAME
sync/SyncUtil.c -
Part of CCNx Sync.
SYNOPSIS
Defines
#define SET_ERR(d) SyncSetDecodeErr(d, -__LINE__)
#define UseLocalTopoPrefix 1
Functions
void SyncNoteErr (const char *msg)
int SyncSetDecodeErr (struct ccn_buf_decoder *d, int val)
int SyncCheckDecodeErr (struct ccn_buf_decoder *d)
int64_t SyncCurrentTime (void)
int64_t SyncDeltaTime (int64_t mt1, int64_t mt2)
struct ccn_buf_decoder * SyncInitDecoderFromCharbufRange (struct ccn_buf_decoder *d, const struct ccn_charbuf *cb, ssize_t start, ssize_t stop)
struct ccn_buf_decoder * SyncInitDecoderFromCharbuf (struct ccn_buf_decoder *d, const struct ccn_charbuf *cb, ssize_t start)
int SyncDecodeHexDigit (char c)
int SyncDecodeUriChar (char c)
char * SyncHexStr (const unsigned char *cp, size_t sz)
int SyncNoteFailed (struct SyncRootStruct *root, char *where, char *why, int line)
void SyncNoteSimple (struct SyncRootStruct *root, char *where, char *s1)
void SyncNoteSimple2 (struct SyncRootStruct *root, char *where, char *s1, char *s2)
void SyncNoteSimple3 (struct SyncRootStruct *root, char *where, char *s1, char *s2, char *s3)
void SyncNoteUri (struct SyncRootStruct *root, char *where, char *why, struct ccn_charbuf *name)
void SyncNoteUriBase (struct SyncBaseStruct *base, char *where, char *why, struct ccn_charbuf *name)
int SyncCmpNamesInner (struct ccn_buf_decoder *xx, struct ccn_buf_decoder *yy)
compare two names advances both decoders, but early exit may leave them not fully over the names decoder error flags may be useful, though, if any errors occur
int SyncCmpNames (const struct ccn_charbuf *cbx, const struct ccn_charbuf *cby)
int SyncIsName (const struct ccn_charbuf *cb)
tests to see if charbuf refers to a name
int SyncComponentCount (const struct ccn_charbuf *name)
int SyncPatternMatch (const struct ccn_charbuf *pattern, const struct ccn_charbuf *name, int start)
simple pattern matching, where the pattern may contain components with a single 255 byte to match a single name component
int SyncPrefixMatch (const struct ccn_charbuf *prefix, const struct ccn_charbuf *name, int start)
int SyncComponentMatch (const struct ccn_charbuf *x, const struct ccn_charbuf *y)
int SyncGetComponentPtr (const struct ccn_charbuf *src, int comp, const unsigned char **xp, ssize_t *xs)
finds the bytes for a component (not including the tag) src must be a name, comp the component index
int SyncAppendAllComponents (struct ccn_charbuf *dst, const struct ccn_charbuf *src)
appends components from src to dst (both must be names)
struct ccn_charbuf * SyncNameForIndexbuf (const unsigned char *buf, struct ccn_indexbuf *comps)
Convenience routine to make a name from a ccn_indexbuf.
struct ccn_charbuf * SyncUriForName (struct ccn_charbuf *name)
Convenience routine to make a uri for a name.
struct ccn_charbuf * SyncConstructCommandPrefix (struct SyncRootStruct *root, char *marker)
Convenience routine to make a Sync protocol command prefix for a marker.
void SyncGetHashPtr (const struct ccn_buf_decoder *hd, const unsigned char **xp, ssize_t *xs)
finds the hash code, storing the pointer to *xp and the length to *xs if the hash is valid (test for *xs != 0 to be sure) a hash code may be a ContentHash, or the last component of a Name (for convenience, a Component may also be used) non-destructive to the decoder no error codes, but a pointer is set only for valid cases
int SyncCmpHashesRaw (const unsigned char *xp, ssize_t xs, const unsigned char *yp, ssize_t ys)
compares two hash codes in charbufs
int SyncCompareHash (struct ccn_charbuf *hashX, struct ccn_charbuf *hashY)
compares two hash codes in charbufs
void SyncAccumHashRaw (struct SyncLongHashStruct *hp, const unsigned char *xp, size_t xs)
void SyncAccumHashInner (struct SyncLongHashStruct *hp, const struct ccn_buf_decoder *d)
void SyncAccumHash (struct SyncLongHashStruct *hp, const struct ccn_charbuf *cb)
struct ccn_charbuf * SyncLongHashToBuf (const struct SyncLongHashStruct *hp)
uint32_t SyncSmallHash (const unsigned char *xp, ssize_t xs)
struct SyncHashInfoList * SyncNoteHash (struct SyncHashInfoList *head, struct SyncHashCacheEntry *ce)
struct SyncNameAccum * SyncExclusionsFromHashList (struct SyncRootStruct *root, struct SyncNameAccum *acc, struct SyncHashInfoList *list)
int SyncAppendTaggedNumber (struct ccn_charbuf *cb, enum ccn_dtag dtag, unsigned val)
int SyncAppendRandomBytes (struct ccn_charbuf *cb, int n)
int SyncAppendRandomHash (struct ccn_charbuf *cb, int n)
int SyncAppendRandomName (struct ccn_charbuf *cb, int nComp, int maxCompLen)
int SyncAppendElementInner (struct ccn_charbuf *cb, struct ccn_buf_decoder *d)
int SyncAppendElement (struct ccn_charbuf *dst, const struct ccn_charbuf *src)
struct ccn_charbuf * SyncExtractName (struct ccn_buf_decoder *d)
struct ccn_charbuf * SyncCopyName (const struct ccn_charbuf *name)
unsigned SyncParseUnsigned (struct ccn_buf_decoder *d, enum ccn_dtag dtag)
ssize_t SyncParseHash (struct ccn_buf_decoder *d)
ssize_t SyncParseName (struct ccn_buf_decoder *d)
struct SyncNameAccum * SyncAllocNameAccum (int lim)
struct SyncNameAccum * SyncFreeNameAccum (struct SyncNameAccum *na)
frees the name accum, but not the names
struct SyncNameAccum * SyncFreeNameAccumAndNames (struct SyncNameAccum *na)
frees the name accum and all of the names
int SyncNameAccumSorter (IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
default sorter callback for a name accum uses CCN standard name order
int SyncNameAccumAppend (struct SyncNameAccum *na, struct ccn_charbuf *name, intmax_t data)
appends a new name with associated data important: the name is not copied!
struct ccn_charbuf * SyncNameAccumCanon (struct SyncNameAccum *na, const struct ccn_charbuf *name)
canonicalizes a name with respect to the given name accum should be used for relatively small canon sets
struct SyncNodeAccum * SyncAllocNodeAccum (int lim)
struct SyncNodeAccum * SyncFreeNodeAccum (struct SyncNodeAccum *na)
void SyncAccumNode (struct SyncNodeAccum *na, struct SyncNodeComposite *nc)
int SyncAddName (struct SyncBaseStruct *base, struct ccn_charbuf *name, uint64_t seq_num)
Adds the given name to any applicable roots.
struct SyncNameAccum * SyncSortNames (struct SyncRootStruct *root, struct SyncNameAccum *src)
takes a list of names and sort them, removing duplicates names are transfered to the return accum, so src is left empty
static int appendLifetime (struct ccn_charbuf *cb, int lifetime)
static int appendExclusions (struct ccn_charbuf *cb, struct SyncNameAccum *excl)
struct ccn_charbuf * SyncGenInterest (struct ccn_charbuf *name, int scope, int lifetime, int maxSuffix, int childPref, struct SyncNameAccum *excl)
given a spec for the desired fields (scope, lifetime, maxSuffix, child are omitted if negative)
struct ccn_charbuf * SyncNameForLocalNode (struct SyncRootStruct *root, struct ccn_charbuf *hash)
given a sync node hash,
int SyncPointerToContent (struct ccn_charbuf *cb, struct ccn_parsed_ContentObject *pco, const unsigned char **xp, size_t *xs)
given a charbuf cb for a content object, with optional parsing offsets in pco, sets *xp and *xs with the pointer and length of the actual content bytes
struct ccn_charbuf * SyncSignBuf (struct SyncBaseStruct *base, struct ccn_charbuf *cb, struct ccn_charbuf *name, long fresh, int flags)
given a charbuf cb and name for a content object, signs the bytes and
int SyncLocalRepoStore (struct SyncBaseStruct *base, struct ccn_charbuf *name, struct ccn_charbuf *content, int flags)
given a sync node hash,
int SyncLocalRepoFetch (struct SyncBaseStruct *base, struct ccn_charbuf *name, struct ccn_charbuf *cb, struct ccn_parsed_ContentObject *pco)
given a local repo name and a buffer to fill, fills cb with the content object (note: not the content itself) pco is filled as a useful side effect, but may be NULL
Variables
static int freshLimit = 30
Detailed Description
Part of CCNx Sync.
Definition in file SyncUtil.c.
Define Documentation
#define SET_ERR(d) SyncSetDecodeErr(d, -__LINE__)
Definition at line 45 of file SyncUtil.c.
Referenced by SyncCmpNamesInner(), SyncInitDecoderFromCharbufRange(), SyncParseName(), and SyncParseUnsigned().
#define UseLocalTopoPrefix 1
Definition at line 1252 of file SyncUtil.c.
Function Documentation
static int appendExclusions (struct ccn_charbuf * cb, struct SyncNameAccum * excl) [static]
Definition at line 1189 of file SyncUtil.c.
Referenced by SyncGenInterest().
static int appendLifetime (struct ccn_charbuf * cb, int lifetime) [static]
Definition at line 1173 of file SyncUtil.c.
Referenced by SyncGenInterest().
void SyncAccumHash (struct SyncLongHashStruct * hp, const struct ccn_charbuf * cb)
Definition at line 653 of file SyncUtil.c.
Referenced by MakeNodeFromNames(), node_from_names(), SyncNodeAddName(), and testReadBuilder().
void SyncAccumHashInner (struct SyncLongHashStruct * hp, const struct ccn_buf_decoder * d)
Definition at line 640 of file SyncUtil.c.
Referenced by SyncAccumHash(), and SyncNodeAddNode().
void SyncAccumHashRaw (struct SyncLongHashStruct * hp, const unsigned char * xp, size_t xs)
Definition at line 608 of file SyncUtil.c.
Referenced by SyncAccumHashInner().
void SyncAccumNode (struct SyncNodeAccum * na, struct SyncNodeComposite * nc)
Definition at line 1064 of file SyncUtil.c.
Referenced by MakeNodeFromNames(), newNodeCommon(), and node_from_names().
int SyncAddName (struct SyncBaseStruct * base, struct ccn_charbuf * name, uint64_t seq_num)
Adds the given name to any applicable roots. Use seq_num == 0 to ignore sequence number.
Returns:
< 0 for failure, number of additions to roots for success.
Definition at line 1083 of file SyncUtil.c.
Referenced by sync_notify_default(), sync_notify_for_actions(), and SyncStartContentFetch().
struct SyncNameAccum* SyncAllocNameAccum (int lim) [read]"Returns:
a new name accum with at least lim space for names
Definition at line 944 of file SyncUtil.c.
Referenced by addNameFromCompare(), copyFilter(), extractDeltas(), genTestRootRepos(), my_add(), readAndAccumNames(), sync_update_start(), SyncAddRoot(), SyncExclusionsFromHashList(), SyncNewBase(), SyncRootDecodeAndAdd(), SyncSortNames(), SyncUpdateRoot(), and UpdateAction().
struct SyncNodeAccum* SyncAllocNodeAccum (int lim) [read]
Definition at line 1046 of file SyncUtil.c.
Referenced by node_from_nodes(), nodeFromNodes(), sync_update_start(), and UpdateAction().
int SyncAppendAllComponents (struct ccn_charbuf * dst, const struct ccn_charbuf * src)
appends components from src to dst (both must be names) Returns:
< 0 for an error
the number of components copied otherwise
Definition at line 468 of file SyncUtil.c.
Referenced by constructCommandPrefix(), existingRootOp(), and SyncConstructCommandPrefix().
int SyncAppendElement (struct ccn_charbuf * dst, const struct ccn_charbuf * src)
Definition at line 868 of file SyncUtil.c.
Referenced by SyncEndComposite(), and SyncNodeAddName().
int SyncAppendElementInner (struct ccn_charbuf * cb, struct ccn_buf_decoder * d)
Definition at line 830 of file SyncUtil.c.
Referenced by extractBuf(), printTreeInner(), SyncAppendElement(), SyncExtractName(), and SyncTreeGenerateNames().
int SyncAppendRandomBytes (struct ccn_charbuf * cb, int n)
Definition at line 777 of file SyncUtil.c.
Referenced by SyncAppendRandomHash(), and SyncAppendRandomName().
int SyncAppendRandomHash (struct ccn_charbuf * cb, int n)
Definition at line 793 of file SyncUtil.c.
int SyncAppendRandomName (struct ccn_charbuf * cb, int nComp, int maxCompLen)
Definition at line 803 of file SyncUtil.c.
Referenced by testGenComposite().
int SyncAppendTaggedNumber (struct ccn_charbuf * cb, enum ccn_dtag dtag, unsigned val)
Definition at line 768 of file SyncUtil.c.
Referenced by NewDeltas(), sendSlice(), SyncEndComposite(), SyncResetComposite(), SyncRootAppendSlice(), and testRootBasic().
int SyncCheckDecodeErr (struct ccn_buf_decoder * d)
Definition at line 66 of file SyncUtil.c.
Referenced by appendComponents(), extractDeltas(), SyncAppendAllComponents(), SyncAppendElementInner(), SyncCmpNames(), SyncCmpNamesInner(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncGetHashPtr(), SyncIsName(), SyncParseComposite(), SyncParseUnsigned(), SyncPatternMatch(), SyncPrefixMatch(), and SyncRootDecodeAndAdd().
int SyncCmpHashesRaw (const unsigned char * xp, ssize_t xs, const unsigned char * yp, ssize_t ys)
compares two hash codes in charbufs Returns:
< 0 for X < Y, 0 for X = Y, > 0 for X > Y
Definition at line 586 of file SyncUtil.c.
Referenced by SyncHashEnter(), and SyncHashLookup().
int SyncCmpNames (const struct ccn_charbuf * cbx, const struct ccn_charbuf * cby)
Definition at line 227 of file SyncUtil.c.
Referenced by AdvanceName(), canonFilter(), doComparison(), SyncAddName(), SyncNameAccumCanon(), SyncNameAccumSorter(), SyncNodeCompareMinMax(), SyncNodeMaintainMinMax(), SyncSortNames(), SyncTreeMergeNames(), and testReader().
int SyncCmpNamesInner (struct ccn_buf_decoder * xx, struct ccn_buf_decoder * yy)
compare two names advances both decoders, but early exit may leave them not fully over the names decoder error flags may be useful, though, if any errors occur
Definition at line 185 of file SyncUtil.c.
Referenced by SyncCmpNames(), and SyncNodeCompareLeaf().
int SyncCompareHash (struct ccn_charbuf * hashX, struct ccn_charbuf * hashY)
compares two hash codes in charbufs Returns:
< 0 for X < Y, 0 for X = Y, > 0 for X > Y
Definition at line 594 of file SyncUtil.c.
Referenced by abortCompare(), chooseNextHash(), and SyncStartNodeFetch().
int SyncComponentCount (const struct ccn_charbuf * name)"Returns:
number of components in the name
Definition at line 249 of file SyncUtil.c.
Referenced by advise_interest_arrived(), putFile(), putFileList(), SyncRegisterInterest(), SyncRootLookupName(), SyncSendRootAdviseInterest(), and SyncStartNodeFetch().
int SyncComponentMatch (const struct ccn_charbuf * x, const struct ccn_charbuf * y)"Returns:
number of components in the longest prefix of both x and y
-1 if there is a parsing error
Definition at line 407 of file SyncUtil.c.
Referenced by try_node_split(), and TryNodeSplit().
struct ccn_charbuf* SyncConstructCommandPrefix (struct SyncRootStruct * root, char * marker) [read]
Convenience routine to make a Sync protocol command prefix for a marker. The returned name includes the topo prefix, the marker, and the slice hash. The storage for the returned charbuf is owned by the caller.
Returns:
the charbuf with the uri for the name (NULL if an error)
Definition at line 529 of file SyncUtil.c.
struct ccn_charbuf* SyncCopyName (const struct ccn_charbuf * name) [read]
Definition at line 892 of file SyncUtil.c.
Referenced by add_update_name(), addNameFromCompare(), AddUpdateName(), ccns_open(), merge_names(), my_add(), my_get(), start_interest(), storeHandler(), SyncAddName(), and SyncInterestArrived().
int64_t SyncCurrentTime (void)
Definition at line 71 of file SyncUtil.c.
Referenced by addNodeFetch(), chooseRemoteHash(), CompareAction(), compareAction(), formatStats(), HeartbeatAction(), merge_names(), newActionData(), NewDeltas(), noteHash(), purgeOldEntries(), SendDeltasReply(), start_interest(), sync_diff_note_node(), sync_diff_start(), sync_update_start(), SyncAddRoot(), SyncExclusionsFromHashList(), SyncHashEnter(), SyncNewBase(), SyncNoteHash(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartCompareAction(), SyncTreeMergeNames(), SyncUpdateRoot(), testReader(), UpdateAction(), and updateAction().
int SyncDecodeHexDigit (char c)
Definition at line 105 of file SyncUtil.c.
Referenced by parseAndAccumName().
int SyncDecodeUriChar (char c)
Definition at line 113 of file SyncUtil.c.
Referenced by parseAndAccumName().
int64_t SyncDeltaTime (int64_t mt1, int64_t mt2)
Definition at line 79 of file SyncUtil.c.
Referenced by chooseRemoteHash(), CompareAction(), compareAction(), formatStats(), HeartbeatAction(), merge_names(), purgeOldEntries(), SyncExclusionsFromHashList(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncTreeMergeNames(), testReader(), UpdateAction(), and updateAction().
struct SyncNameAccum* SyncExclusionsFromHashList (struct SyncRootStruct * root, struct SyncNameAccum * acc, struct SyncHashInfoList * list) [read]
Definition at line 708 of file SyncUtil.c.
Referenced by start_interest(), and SyncSendRootAdviseInterest().
struct ccn_charbuf* SyncExtractName (struct ccn_buf_decoder * d) [read]
Definition at line 876 of file SyncUtil.c.
Referenced by extractDeltas(), SyncParseComposite(), and SyncRootDecodeAndAdd().
struct SyncNameAccum* SyncFreeNameAccum (struct SyncNameAccum * na) [read]
frees the name accum, but not the names Returns:
NULL
Definition at line 953 of file SyncUtil.c.
Referenced by genTestRootRepos(), SyncExclusionsFromHashList(), testReadBuilder(), and testReader().
struct SyncNameAccum* SyncFreeNameAccumAndNames (struct SyncNameAccum * na) [read]
frees the name accum and all of the names Returns:
NULL
Definition at line 962 of file SyncUtil.c.
Referenced by destroyCompareData(), extractDeltas(), FreeUpdateData(), putFileList(), resetUpdateData(), start_interest(), SyncFreeBase(), SyncRemRoot(), SyncRootDecodeAndAdd(), SyncSendRootAdviseInterest(), SyncStartCompareAction(), and UpdateAction().
struct SyncNodeAccum* SyncFreeNodeAccum (struct SyncNodeAccum * na) [read]
Definition at line 1055 of file SyncUtil.c.
Referenced by FreeUpdateData(), node_from_nodes(), nodeFromNodes(), and resetUpdateData().
struct ccn_charbuf* SyncGenInterest (struct ccn_charbuf * name, int scope, int lifetime, int maxSuffix, int childPref, struct SyncNameAccum * excl) [read]
given a spec for the desired fields (scope, lifetime, maxSuffix, child are omitted if negative) Returns:
the encoding for an interest
Definition at line 1219 of file SyncUtil.c.
Referenced by existingRootOp(), getFile(), localStore(), my_get(), putFile(), putFileList(), start_interest(), SyncHandleSlice(), SyncLocalRepoFetch(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), SyncStartHeartbeat(), SyncStartNodeFetch(), and SyncStartSliceEnum().
int SyncGetComponentPtr (const struct ccn_charbuf * src, int comp, const unsigned char ** xp, ssize_t * xs)
finds the bytes for a component (not including the tag) src must be a name, comp the component index Returns:
< 0 for an error, 0 otherwise
Definition at line 444 of file SyncUtil.c.
Referenced by putFile(), putFileList(), and SyncHandleSlice().
void SyncGetHashPtr (const struct ccn_buf_decoder * hd, const unsigned char ** xp, ssize_t * xs)
finds the hash code, storing the pointer to *xp and the length to *xs if the hash is valid (test for *xs != 0 to be sure) a hash code may be a ContentHash, or the last component of a Name (for convenience, a Component may also be used) non-destructive to the decoder no error codes, but a pointer is set only for valid cases
Definition at line 553 of file SyncUtil.c.
Referenced by cacheEntryForElem(), SyncAccumHashInner(), and SyncTreeWorkerPush().
char* SyncHexStr (const unsigned char * cp, size_t sz)
Definition at line 125 of file SyncUtil.c.
Referenced by abortCompare(), findAndDeleteRoot(), formatStats(), MakeNodeFromNames(), newNodeCommon(), node_from_names(), noteHash(), printTreeInner(), purgeOldEntries(), reportExclude(), setCovered(), SyncHandleSlice(), SyncInterestArrived(), SyncRegisterInterests(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartCompareAction(), SyncStartNodeFetch(), SyncUpdateRoot(), testReadBuilder(), UpdateAction(), and updateAction().
struct ccn_buf_decoder* SyncInitDecoderFromCharbuf (struct ccn_buf_decoder * d, const struct ccn_charbuf * cb, ssize_t start) [read]
Definition at line 98 of file SyncUtil.c.
Referenced by appendComponents(), appendExclusions(), SyncAccumHash(), SyncAppendAllComponents(), SyncAppendElement(), SyncCmpNames(), SyncComponentCount(), SyncComponentMatch(), SyncGetComponentPtr(), SyncIsName(), SyncNodeCompareLeaf(), SyncPatternMatch(), SyncPrefixMatch(), testEncodeDecode(), and testRootCoding().
struct ccn_buf_decoder* SyncInitDecoderFromCharbufRange (struct ccn_buf_decoder * d, const struct ccn_charbuf * cb, ssize_t start, ssize_t stop) [read]
Definition at line 84 of file SyncUtil.c.
Referenced by SyncInitDecoderFromCharbuf(), SyncInitDecoderFromElem(), SyncInitDecoderFromOffset(), and SyncNodeAddNode().
int SyncIsName (const struct ccn_charbuf * cb)
tests to see if charbuf refers to a name Returns:
1 for a name, 0 otherwise
Definition at line 240 of file SyncUtil.c.
int SyncLocalRepoFetch (struct SyncBaseStruct * base, struct ccn_charbuf * name, struct ccn_charbuf * cb, struct ccn_parsed_ContentObject * pco)
given a local repo name and a buffer to fill, fills cb with the content object (note: not the content itself) pco is filled as a useful side effect, but may be NULL Returns:
< 0 if the node fails
Definition at line 1367 of file SyncUtil.c.
Referenced by SyncCacheEntryFetch().
int SyncLocalRepoStore (struct SyncBaseStruct * base, struct ccn_charbuf * name, struct ccn_charbuf * content, int flags)
given a sync node hash, Returns:
the local repo name for the node
Definition at line 1338 of file SyncUtil.c.
Referenced by SyncCacheEntryStore().
struct ccn_charbuf* SyncLongHashToBuf (const struct SyncLongHashStruct * hp) [read]
Definition at line 660 of file SyncUtil.c.
Referenced by SyncEndComposite(), SyncParseComposite(), testReadBuilder(), UpdateAction(), and updateAction().
int SyncNameAccumAppend (struct SyncNameAccum * na, struct ccn_charbuf * name, intmax_t data)
appends a new name with associated data important: the name is not copied!
Definition at line 997 of file SyncUtil.c.
Referenced by add_update_name(), addNameFromCompare(), AddUpdateName(), extractDeltas(), genTestRootRepos(), my_add(), parseAndAccumName(), SyncAddName(), SyncExclusionsFromHashList(), SyncNameAccumCanon(), SyncRootDecodeAndAdd(), SyncSortNames(), and SyncTreeGenerateNames().
struct ccn_charbuf* SyncNameAccumCanon (struct SyncNameAccum * na, const struct ccn_charbuf * name) [read]
canonicalizes a name with respect to the given name accum should be used for relatively small canon sets Returns:
an equal name if it was in the accum
a copy of the name (and enters it) if no equal name was in the accum
Definition at line 1022 of file SyncUtil.c.
Referenced by SyncAddRoot().
int SyncNameAccumSorter (IndexSorter_Base base, IndexSorter_Index x, IndexSorter_Index y)
default sorter callback for a name accum uses CCN standard name order
Definition at line 982 of file SyncUtil.c.
Referenced by SyncSortNames(), SyncUpdateRoot(), and testReader().
struct ccn_charbuf* SyncNameForIndexbuf (const unsigned char * buf, struct ccn_indexbuf * comps) [read]
Convenience routine to make a name from a ccn_indexbuf. The storage for the returned charbuf is owned by the caller.
Returns:
a charbuf for the name (NULL if an error)
Definition at line 497 of file SyncUtil.c.
Referenced by advise_interest_arrived(), my_response(), and SyncRootAdviseResponse().
struct ccn_charbuf* SyncNameForLocalNode (struct SyncRootStruct * root, struct ccn_charbuf * hash) [read]
given a sync node hash, Returns:
the local repo name for the node
Definition at line 1254 of file SyncUtil.c.
Referenced by SyncCacheEntryFetch(), and SyncCacheEntryStore().
void SyncNoteErr (const char * msg)
Definition at line 47 of file SyncUtil.c.
Referenced by SyncAccumHashRaw(), SyncNameAccumAppend(), SyncNameAccumSorter(), SyncNameForIndexbuf(), SyncNoteFailed(), SyncSetCompErr(), and SyncSetDecodeErr().
int SyncNoteFailed (struct SyncRootStruct * root, char * where, char * why, int line)
Definition at line 141 of file SyncUtil.c.
Referenced by cacheEntryForElem(), comparisonFailed(), ensureRemoteEntry(), extractDeltas(), extractNode(), my_get(), newNodeCommon(), node_from_nodes(), nodeFromNodes(), start_interest(), SyncHandleSlice(), SyncRegisterInterest(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSortNames(), SyncStartCompareAction(), SyncStartContentFetch(), SyncStartNodeFetch(), UpdateAction(), and updateAction().
struct SyncHashInfoList* SyncNoteHash (struct SyncHashInfoList * head, struct SyncHashCacheEntry * ce) [read]
Definition at line 683 of file SyncUtil.c.
Referenced by advise_interest_arrived(), and my_response().
void SyncNoteSimple (struct SyncRootStruct * root, char * where, char * s1)
Definition at line 150 of file SyncUtil.c.
Referenced by abortCompare(), advise_interest_arrived(), CompareAction(), compareAction(), doPreload(), HeartbeatAction(), MakeNodeFromNames(), merge_names(), my_add(), my_response(), node_from_names(), note_update_done(), purgeOldEntries(), reportExclude(), setCovered(), sync_diff_note_node(), sync_notify_for_actions(), sync_update_start(), sync_update_stop(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncTreeMergeNames(), try_node_split(), TryNodeSplit(), UpdateAction(), and updateAction().
void SyncNoteSimple2 (struct SyncRootStruct * root, char * where, char * s1, char * s2)
Definition at line 155 of file SyncUtil.c.
Referenced by CompareAction(), compareAction(), MakeNodeFromNames(), newNodeCommon(), node_from_names(), showCacheEntry1(), showCacheEntry2(), SyncHandleSlice(), SyncInterestArrived(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncStartNodeFetch(), try_node_split(), TryNodeSplit(), UpdateAction(), and updateAction().
void SyncNoteSimple3 (struct SyncRootStruct * root, char * where, char * s1, char * s2, char * s3)
Definition at line 160 of file SyncUtil.c.
Referenced by SyncInterestArrived().
void SyncNoteUri (struct SyncRootStruct * root, char * where, char * why, struct ccn_charbuf * name)
Definition at line 165 of file SyncUtil.c.
Referenced by add_update_name(), addNameFromCompare(), AddUpdateName(), advise_interest_arrived(), my_add(), my_get(), SendDeltasReply(), start_interest(), SyncAddName(), SyncCacheEntryFetch(), SyncInterestArrived(), SyncRegisterInterest(), SyncRemoteFetchResponse(), SyncRootAdviseResponse(), SyncSendRootAdviseInterest(), SyncStartContentFetch(), SyncStartSliceEnum(), SyncTreeMergeNames(), and UpdateAction().
void SyncNoteUriBase (struct SyncBaseStruct * base, char * where, char * why, struct ccn_charbuf * name)
Definition at line 173 of file SyncUtil.c.
Referenced by SyncLocalRepoFetch(), and SyncLocalRepoStore().
ssize_t SyncParseHash (struct ccn_buf_decoder * d)
Definition at line 918 of file SyncUtil.c.
Referenced by SyncParseComposite().
ssize_t SyncParseName (struct ccn_buf_decoder * d)
Definition at line 925 of file SyncUtil.c.
Referenced by SyncParseComposite().
unsigned SyncParseUnsigned (struct ccn_buf_decoder * d, enum ccn_dtag dtag)
Definition at line 903 of file SyncUtil.c.
Referenced by extractDeltas(), SyncParseComposite(), SyncRootDecodeAndAdd(), and testRootBasic().
int SyncPatternMatch (const struct ccn_charbuf * pattern, const struct ccn_charbuf * name, int start)
simple pattern matching, where the pattern may contain components with a single 255 byte to match a single name component Returns:
number of matching components in the pattern if the name (starting at component index start) matches the prefix,
-1 if there is a parsing error or no match
Definition at line 271 of file SyncUtil.c.
Referenced by SyncRootLookupName().
int SyncPointerToContent (struct ccn_charbuf * cb, struct ccn_parsed_ContentObject * pco, const unsigned char ** xp, size_t * xs)
given a charbuf cb for a content object, with optional parsing offsets in pco, sets *xp and *xs with the pointer and length of the actual content bytes Returns:
< 0 for failure
Definition at line 1276 of file SyncUtil.c.
Referenced by existingRootOp(), and SyncHandleSlice().
int SyncPrefixMatch (const struct ccn_charbuf * prefix, const struct ccn_charbuf * name, int start)"Returns:
number of components in the prefix if the name (starting at component index start) matches the prefix,
-1 if there is a parsing error or no match
Definition at line 346 of file SyncUtil.c.
Referenced by sync_notify_for_actions(), SyncHandleSlice(), and SyncRootLookupName().
int SyncSetDecodeErr (struct ccn_buf_decoder * d, int val)
Definition at line 59 of file SyncUtil.c.
Referenced by SyncExtractName(), and SyncGetHashPtr().
struct ccn_charbuf* SyncSignBuf (struct SyncBaseStruct * base, struct ccn_charbuf * cb, struct ccn_charbuf * name, long fresh, int flags) [read]
given a charbuf cb and name for a content object, signs the bytes and Returns:
the signed buffer (NULL for failure)
Definition at line 1293 of file SyncUtil.c.
Referenced by SendDeltasReply(), SyncInterestArrived(), and SyncLocalRepoStore().
uint32_t SyncSmallHash (const unsigned char * xp, ssize_t xs)
Definition at line 670 of file SyncUtil.c.
Referenced by SyncHashEnter(), and SyncHashLookup().
struct SyncNameAccum* SyncSortNames (struct SyncRootStruct * root, struct SyncNameAccum * src) [read]
takes a list of names and sort them, removing duplicates names are transfered to the return accum, so src is left empty Returns:
an accum with the sorted names
Definition at line 1130 of file SyncUtil.c.
Referenced by sync_update_start(), and SyncExclusionsFromHashList().
struct ccn_charbuf* SyncUriForName (struct ccn_charbuf * name) [read]
Convenience routine to make a uri for a name. The storage for the returned charbuf is owned by the caller.
Returns:
the charbuf with the uri for the name (NULL if an error)
Definition at line 520 of file SyncUtil.c.
Referenced by existingRootOp(), my_response(), putFile(), putFileList(), sendSlice(), sync_notify_for_actions(), SyncNoteUri(), SyncNoteUriBase(), and SyncRegisterInterests().
Variable Documentation
int freshLimit = 30 [static]
Definition at line 41 of file SyncUtil.c.
Referenced by SyncSignBuf().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.