sync/sync_api.c
NAME
sync/sync_api.c -
Sync library interface.
SYNOPSIS
Defines
#define CACHE_PURGE_TRIGGER 60
#define CACHE_CLEAN_BATCH 16
#define CACHE_CLEAN_DELTA 8
#define ADVISE_NEED_RESET 1
#define UPDATE_STALL_DELTA 15
#define UPDATE_NEED_DELTA 6
#define SHORT_DELAY_MICROS 500
#define COMPARE_ASSUME_BAD 20
#define NODE_SPLIT_TRIGGER 400
#define EXCLUSION_LIMIT 1000
#define EXCLUSION_TRIG 5
#define STABLE_TIME_TRIG 10
#define HASH_SPLIT_TRIGGER 17
#define NAMES_YIELD_INC 100
#define NAMES_YIELD_MICROS 20*1000
#define CCNS_FLAGS_SC 1
Enumerations
enum local_flags { LF_NULL, LF_ADVISE, LF_NODE, LF_OTHER }
Functions
struct ccns_slice * ccns_slice_create ()
Allocate a ccns_slice structure.
void ccns_slice_destroy (struct ccns_slice **sp)
Deallocate a ccns_slice structure.
int ccns_slice_add_clause (struct ccns_slice *s, struct ccn_charbuf *c)
Add a (filter) clause to a ccns_slice structure.
int ccns_slice_set_topo_prefix (struct ccns_slice *s, struct ccn_charbuf *t, struct ccn_charbuf *p)
static int append_slice (struct ccn_charbuf *c, struct ccns_slice *s)
static int slice_parse (struct ccns_slice *s, const unsigned char *p, size_t size)
int ccns_slice_name (struct ccn_charbuf *nm, struct ccns_slice *s)
Construct the name of a Sync configuration slice based on the parameters.
int ccns_read_slice (struct ccn *h, struct ccn_charbuf *name, struct ccns_slice *slice)
Read a slice (from a repository) given the name.
struct ccn_charbuf * make_scope1_template (void)
static enum ccn_upcall_res write_interest_handler (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int write_slice (struct ccn *h, struct ccns_slice *slice, struct ccn_charbuf *name)
int ccns_write_slice (struct ccn *h, struct ccns_slice *slice, struct ccn_charbuf *name)
Write a ccns_slice object to a repository.
int ccns_delete_slice (struct ccn *h, struct ccn_charbuf *name)
Delete a ccns_slice object from a repository.
static void gettime (const struct ccn_gettime *self, struct ccn_timeval *result)
static int start_interest (struct sync_diff_data *diff_data)
static int noteErr2 (const char *why, const char *msg)
static void my_r_sync_msg (struct sync_plumbing *sd, const char *fmt,...)
static struct SyncNodeComposite * extractNode (struct SyncRootStruct *root, struct ccn_upcall_info *info)
struct sync_diff_fetch_data * check_fetch_data (struct ccns_handle *ch, struct sync_diff_fetch_data *fd)
static struct sync_diff_fetch_data * find_fetch_data (struct ccns_handle *ch, struct SyncHashCacheEntry *ce)
static int delink_fetch_data (struct ccns_handle *ch, struct sync_diff_fetch_data *fd)
static void free_fetch_data (struct ccns_handle *ch, struct sync_diff_fetch_data *fd)
static void setCurrentHash (struct SyncRootStruct *root, struct SyncHashCacheEntry *ce)
static struct SyncHashCacheEntry * chooseNextHash (struct ccns_handle *ch)
static int each_round (struct ccn_schedule *sched, void *clienth, struct ccn_scheduled_event *ev, int flags)
static void start_round (struct ccns_handle *ch, int micros)
static enum ccn_upcall_res my_response (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static enum ccn_upcall_res advise_interest_arrived (struct ccn_closure *selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info *info)
static int my_get (struct sync_diff_get_closure *gc, struct sync_diff_fetch_data *fd)
static int my_add (struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
static int note_update_done (struct sync_done_closure *dc)
struct ccns_handle * ccns_open (struct ccn *h, struct ccns_slice *slice, struct ccns_name_closure *nc, struct ccn_charbuf *rhash, struct ccn_charbuf *pname)
Start notification of addition of names to a sync slice.
void ccns_close (struct ccns_handle **sh, struct ccn_charbuf *rhash, struct ccn_charbuf *pname)
Stop notification of changes of names in a sync slice and free the handle.
Variables
static struct sync_plumbing_client_methods client_methods
Detailed Description
Sync library interface.
Implements a library interface to the Sync protocol facilities implemented by the Repository
Part of the CCNx C Library.
Copyright (C) 2012 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file sync_api.c.
Define Documentation
#define ADVISE_NEED_RESET 1
Definition at line 47 of file sync_api.c.
#define CACHE_CLEAN_BATCH 16
Definition at line 45 of file sync_api.c.
#define CACHE_CLEAN_DELTA 8
Definition at line 46 of file sync_api.c.
#define CACHE_PURGE_TRIGGER 60
Definition at line 44 of file sync_api.c.
#define CCNS_FLAGS_SC 1
Definition at line 68 of file sync_api.c.
#define COMPARE_ASSUME_BAD 20
Definition at line 51 of file sync_api.c.
#define EXCLUSION_LIMIT 1000
Definition at line 53 of file sync_api.c.
#define EXCLUSION_TRIG 5
Definition at line 54 of file sync_api.c.
#define HASH_SPLIT_TRIGGER 17
Definition at line 56 of file sync_api.c.
#define NAMES_YIELD_INC 100
Definition at line 57 of file sync_api.c.
#define NAMES_YIELD_MICROS 20*1000
Definition at line 58 of file sync_api.c.
#define NODE_SPLIT_TRIGGER 400
Definition at line 52 of file sync_api.c.
#define SHORT_DELAY_MICROS 500
Definition at line 50 of file sync_api.c.
#define STABLE_TIME_TRIG 10
Definition at line 55 of file sync_api.c.
#define UPDATE_NEED_DELTA 6
Definition at line 49 of file sync_api.c.
#define UPDATE_STALL_DELTA 15
Definition at line 48 of file sync_api.c.
Enumeration Type Documentation
enum local_flags
Enumerator:
LF_NULL
LF_ADVISE
LF_NODE
LF_OTHER
Definition at line 547 of file sync_api.c.
Function Documentation
static enum ccn_upcall_res advise_interest_arrived (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 892 of file sync_api.c.
Referenced by ccns_open().
static int append_slice (struct ccn_charbuf * c, struct ccns_slice * s) [static]
Definition at line 185 of file sync_api.c.
Referenced by ccns_slice_name(), and write_slice().
void ccns_close (struct ccns_handle ** sh, struct ccn_charbuf * rhash, struct ccn_charbuf * pname)
Stop notification of changes of names in a sync slice and free the handle. Parameters:
sh is a pointer (to a pointer) to the sync handle returned by ccns_open, which will be freed and set to NULL.
rhash if non-NULL will be filled in with the current root hash.
pname if non-NULL will be filled in with the starting name for enumeration within the sync tree represented by the root hash rhash.
Definition at line 1256 of file sync_api.c.
Referenced by ccns_open(), and main().
int ccns_delete_slice (struct ccn * h, struct ccn_charbuf * name)
Delete a ccns_slice object from a repository. Parameters:
h is the ccn_handle on which to write.
name is a pointer to a charbuf naming the slice to be deleted.
Returns:
0 on success, -1 otherwise.
Definition at line 517 of file sync_api.c.
Referenced by main().
struct ccns_handle* ccns_open (struct ccn * h, struct ccns_slice * slice, struct ccns_name_closure * nc, struct ccn_charbuf * rhash, struct ccn_charbuf * pname) [read]
Start notification of addition of names to a sync slice. Parameters:
h is the ccn_handle on which to communicate.
slice is the slice to be opened.
nc is the closure which will be called for each new name, and returns 0 to continue enumeration, -1 to stop further enumeration. NOTE: It is not safe to call ccns_close from within the callback.
rhash If NULL, indicates that the enumeration should start from the empty set. If non-NULL but empty, indicates that the enumeration should start from the current root. If non-NULL, and not empty, indicates that the enumeration should start from the specified root hash
pname if non-NULL represents the starting name for enumeration within the sync tree represented by the root hash rhash.
Returns:
a pointer to a new sync handle, which will be freed at close.
Definition at line 1155 of file sync_api.c.
Referenced by main().
int ccns_read_slice (struct ccn * h, struct ccn_charbuf * name, struct ccns_slice * slice)
Read a slice (from a repository) given the name. Read a slice given the name.
Parameters:
h is the ccn_handle on which to read.
name is the charbuf containing the name of the sync slice to be read.
slice is a pointer to a ccns_slice object which will be filled in on successful return.
Returns:
0 on success, -1 otherwise.
Definition at line 318 of file sync_api.c.
int ccns_slice_add_clause (struct ccns_slice * s, struct ccn_charbuf * f)
Add a (filter) clause to a ccns_slice structure. Parameters:
slice is the slice to be modified
f is a filter clause ccnb-encoded as a Name
Returns:
0 on success, -1 otherwise.
Definition at line 135 of file sync_api.c.
Referenced by main(), and slice_parse().
struct ccns_slice* ccns_slice_create (void) [read]
Allocate a ccns_slice structure. Returns:
a pointer to a new ccns_slice structure
Definition at line 95 of file sync_api.c.
Referenced by main().
void ccns_slice_destroy (struct ccns_slice ** sp)
Deallocate a ccns_slice structure. Parameters:
a pointer to a pointer to a ccns_slice structure. The pointer will be set to NULL on return.
Definition at line 114 of file sync_api.c.
Referenced by main().
int ccns_slice_name (struct ccn_charbuf * nm, struct ccns_slice * s)
Construct the name of a Sync configuration slice based on the parameters. Construct the name of a Sync configuration slice.
Parameters:
nm is the ccn_charbuf which will be set to the ccnb encoded Name
s is the definition of the slice for which the name is required.
Returns:
a ccn_charbuf with the ccnb encoded Name of the slice.
Definition at line 274 of file sync_api.c.
Referenced by ccns_write_slice(), and main().
int ccns_slice_set_topo_prefix (struct ccns_slice * s, struct ccn_charbuf * t, struct ccn_charbuf * p)
Definition at line 165 of file sync_api.c.
Referenced by main().
int ccns_write_slice (struct ccn * h, struct ccns_slice * slice, struct ccn_charbuf * name)
Write a ccns_slice object to a repository. Parameters:
h is the ccn_handle on which to write.
slice is a pointer to a ccns_slice object to be written.
name,if non-NULL, is a pointer to a charbuf which will be filled in with the name of the slice that was written.
Returns:
0 on success, -1 otherwise.
Definition at line 484 of file sync_api.c.
Referenced by main().
struct sync_diff_fetch_data* check_fetch_data (struct ccns_handle * ch, struct sync_diff_fetch_data * fd) [read]
Definition at line 620 of file sync_api.c.
static struct SyncHashCacheEntry* chooseNextHash (struct ccns_handle * ch) [static, read]
Definition at line 682 of file sync_api.c.
Referenced by each_round().
static int delink_fetch_data (struct ccns_handle * ch, struct sync_diff_fetch_data * fd) [static]
Definition at line 642 of file sync_api.c.
Referenced by free_fetch_data().
static int each_round (struct ccn_schedule * sched, void * clienth, struct ccn_scheduled_event * ev, int flags) [static]
Definition at line 704 of file sync_api.c.
Referenced by start_round().
static struct SyncNodeComposite* extractNode (struct SyncRootStruct * root, struct ccn_upcall_info * info) [static, read]
Definition at line 591 of file sync_api.c.
Referenced by my_response().
static struct sync_diff_fetch_data* find_fetch_data (struct ccns_handle * ch, struct SyncHashCacheEntry * ce) [static, read]
Definition at line 631 of file sync_api.c.
Referenced by chooseNextHash().
static void free_fetch_data (struct ccns_handle * ch, struct sync_diff_fetch_data * fd) [static]
Definition at line 661 of file sync_api.c.
Referenced by ccns_close(), my_response(), and start_interest().
static void gettime (const struct ccn_gettime * self, struct ccn_timeval * result) [static]
Definition at line 538 of file sync_api.c.
Referenced by ccns_open().
struct ccn_charbuf* make_scope1_template (void) [read]
Definition at line 358 of file sync_api.c.
Referenced by write_slice().
static int my_add (struct sync_diff_add_closure * ac, struct ccn_charbuf * name) [static]
Definition at line 1060 of file sync_api.c.
Referenced by ccns_open().
static int my_get (struct sync_diff_get_closure * gc, struct sync_diff_fetch_data * fd) [static]
Definition at line 1010 of file sync_api.c.
Referenced by ccns_open().
static void my_r_sync_msg (struct sync_plumbing * sd, const char * fmt, ...) [static]
Definition at line 579 of file sync_api.c.
static enum ccn_upcall_res my_response (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 784 of file sync_api.c.
Referenced by my_get(), and start_interest().
static int note_update_done (struct sync_done_closure * dc) [static]
Definition at line 1126 of file sync_api.c.
Referenced by ccns_open().
static int noteErr2 (const char * why, const char * msg) [static]
Definition at line 572 of file sync_api.c.
Referenced by ccns_open().
static void setCurrentHash (struct SyncRootStruct * root, struct SyncHashCacheEntry * ce) [static]
Definition at line 674 of file sync_api.c.
Referenced by my_add(), and note_update_done().
static int slice_parse (struct ccns_slice * s, const unsigned char * p, size_t size) [static]
Definition at line 207 of file sync_api.c.
Referenced by ccns_read_slice().
static int start_interest (struct sync_diff_data * diff_data) [static]
Definition at line 957 of file sync_api.c.
Referenced by advise_interest_arrived().
static void start_round (struct ccns_handle * ch, int micros) [static]
Definition at line 768 of file sync_api.c.
Referenced by ccns_open(), my_add(), and my_response().
static enum ccn_upcall_res write_interest_handler (struct ccn_closure * selfp, enum ccn_upcall_kind kind, struct ccn_upcall_info * info) [static]
Definition at line 370 of file sync_api.c.
Referenced by write_slice().
static int write_slice (struct ccn * h, struct ccns_slice * slice, struct ccn_charbuf * name) [static]
Definition at line 391 of file sync_api.c.
Referenced by ccns_delete_slice(), and ccns_write_slice().
Variable Documentation
struct sync_plumbing_client_methods client_methods [static]"Initial value:
 {
    my_r_sync_msg, NULL, NULL, NULL, NULL, NULL
}
Definition at line 1150 of file sync_api.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.