sync/SyncBase.c
NAME
sync/SyncBase.c -
Part of CCNx Sync.
SYNOPSIS
Functions
void SyncSetErrInner (struct SyncBaseStruct *base, enum SyncErrCode code, char *file, int line)
void SyncClearErr (struct SyncBaseStruct *base)
void sync_msg (struct SyncBaseStruct *base, const char *fmt,...)
static int getEnvLimited (char *key, int lo, int hi, int def)
static int sync_start_default (struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
the default behavior for sync_start is to read the options, but not start anything
static void SyncFreeBase (struct SyncBaseStruct **bp)
static int sync_notify_default (struct sync_plumbing *sd, struct ccn_charbuf *name, int enum_index, uint64_t seq_num)
void sync_stop_default (struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
struct SyncBaseStruct * SyncNewBase (struct sync_plumbing *sd)
Variables
struct sync_plumbing_sync_methods defaultMethods
Detailed Description
Part of CCNx Sync.
Definition in file SyncBase.c.
Function Documentation
static int getEnvLimited (char * key, int lo, int hi, int def) [static]
Definition at line 81 of file SyncBase.c.
Referenced by sync_start_default().
void sync_msg (struct SyncBaseStruct * base, const char * fmt, ...)
Definition at line 63 of file SyncBase.c.
Referenced by abortCompare(), CompareAction(), findAndDeleteRoot(), newNodeCommon(), node_from_nodes(), nodeFromNodes(), noteHash(), sync_notify_for_actions(), sync_start_default(), sync_start_for_actions(), sync_stop_default(), SyncHandleSlice(), SyncNoteFailed(), SyncNoteSimple(), SyncNoteSimple2(), SyncNoteSimple3(), SyncNoteUri(), SyncNoteUriBase(), SyncRegisterInterests(), SyncRootLookupName(), SyncStartCompareAction(), SyncStartHeartbeat(), SyncUpdateRoot(), UpdateAction(), and updateAction().
static int sync_notify_default (struct sync_plumbing * sd, struct ccn_charbuf * name, int enum_index, uint64_t seq_num) [static]
Definition at line 275 of file SyncBase.c.
static int sync_start_default (struct sync_plumbing * sd, struct ccn_charbuf * state_buf) [static]
the default behavior for sync_start is to read the options, but not start anything
Definition at line 94 of file SyncBase.c.
void sync_stop_default (struct sync_plumbing * sd, struct ccn_charbuf * state_buf)
Definition at line 287 of file SyncBase.c.
void SyncClearErr (struct SyncBaseStruct * base)
Definition at line 52 of file SyncBase.c.
Referenced by SyncFreeBase().
static void SyncFreeBase (struct SyncBaseStruct ** bp) [static]
Definition at line 237 of file SyncBase.c.
Referenced by sync_stop_default().
struct SyncBaseStruct* SyncNewBase (struct sync_plumbing * sd) [read]
Definition at line 308 of file SyncBase.c.
Referenced by ccns_open(), main(), and SyncNewBaseForActions().
void SyncSetErrInner (struct SyncBaseStruct * base, enum SyncErrCode code, char * file, int line)
Definition at line 34 of file SyncBase.c.
Variable Documentation
struct sync_plumbing_sync_methods defaultMethods"Initial value:
 {
    &sync_start_default,
    &sync_notify_default,
    &sync_stop_default
}
Definition at line 301 of file SyncBase.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.