sync_diff_add_closure
NAME
sync_diff_add_closure -
sync_diff_add_closure is called from the differencing operation to note a name difference for sdd.
SYNOPSIS
Data Fields
int(* add )(struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
struct sync_diff_data * diff_data
void * data
Detailed Description
sync_diff_add_closure is called from the differencing operation to note a name difference for sdd.
If name == NULL then there are no more names to be produced, and there should be no future references to sdd. The data is private to the closure, and the client owns all storage in the closure, except for sync_diff_data.
Definition at line 39 of file sync_diff.h.
Field Documentation
int(* sync_diff_add_closure::add)(struct sync_diff_add_closure *ac, struct ccn_charbuf *name)
Definition at line 40 of file sync_diff.h.
Referenced by abortCompare(), addNameFromCompare(), ccns_open(), and compareAction().
void* sync_diff_add_closure::data
Definition at line 43 of file sync_diff.h.
Referenced by ccns_open().
struct sync_diff_data* sync_diff_add_closure::diff_data
Definition at line 42 of file sync_diff.h.
Referenced by ccns_open(), and my_add().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.