.TH "SyncMethodsList" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyncMethodsList \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBSyncMethodsList\fP * \fBnext\fP"
.br
.ti -1c
.RI "struct \fBsync_plumbing_sync_methods\fP * \fBsync_methods\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 30 of file SyncPrivate.h.
.SH "Field Documentation"
.PP 
.SS "struct \fBSyncMethodsList\fP* \fBSyncMethodsList::next\fP"
.PP
Definition at line 31 of file SyncPrivate.h.
.PP
Referenced by SyncNewBaseForActions().
.SS "struct \fBsync_plumbing_sync_methods\fP* \fBSyncMethodsList::sync_methods\fP"
.PP
Definition at line 32 of file SyncPrivate.h.
.PP
Referenced by sync_start_for_actions(), sync_stop_for_actions(), and SyncNewBaseForActions().

.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
