sync/SyncBase.h
NAME
sync/SyncBase.h -
Part of CCNx Sync.
SYNOPSIS
Data Structures
struct SyncBaseStruct
struct SyncErrStruct
Enumerations
enum SyncErrCode { SyncErrCode_none = 0, SyncErrCode_bug = 1, SyncErrCode_caller = 2 }
Functions
void sync_msg (struct SyncBaseStruct *base, const char *fmt,...)
void SyncSetErrInner (struct SyncBaseStruct *base, enum SyncErrCode code, char *file, int line)
void SyncClearErr (struct SyncBaseStruct *base)
struct SyncBaseStruct * SyncNewBase (struct sync_plumbing *sd)
Detailed Description
Part of CCNx Sync.
Copyright (C) 2011 Palo Alto Research Center, Inc.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file SyncBase.h.
Enumeration Type Documentation
enum SyncErrCode
Enumerator:
SyncErrCode_none
SyncErrCode_bug
SyncErrCode_caller
Definition at line 48 of file SyncBase.h.
Function Documentation
void sync_msg (struct SyncBaseStruct * base, const char * fmt, ...)
Definition at line 63 of file SyncBase.c.
Referenced by abortCompare(), CompareAction(), findAndDeleteRoot(), newNodeCommon(), node_from_nodes(), nodeFromNodes(), noteHash(), sync_notify_for_actions(), sync_start_default(), sync_start_for_actions(), sync_stop_default(), SyncHandleSlice(), SyncNoteFailed(), SyncNoteSimple(), SyncNoteSimple2(), SyncNoteSimple3(), SyncNoteUri(), SyncNoteUriBase(), SyncRegisterInterests(), SyncRootLookupName(), SyncStartCompareAction(), SyncStartHeartbeat(), SyncUpdateRoot(), UpdateAction(), and updateAction().
void SyncClearErr (struct SyncBaseStruct * base)
Definition at line 52 of file SyncBase.c.
Referenced by SyncFreeBase().
struct SyncBaseStruct* SyncNewBase (struct sync_plumbing * sd) [read]
Definition at line 308 of file SyncBase.c.
Referenced by ccns_open(), main(), and SyncNewBaseForActions().
void SyncSetErrInner (struct SyncBaseStruct * base, enum SyncErrCode code, char * file, int line)
Definition at line 34 of file SyncBase.c.
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.