.TH "sync/SyncPrivate.h" 3 "4 Feb 2013" "Version 0.7.1" "Content-Centric Networking in C" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sync/SyncPrivate.h \- 
.PP
Part of CCNx Sync.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBSyncMethodsList\fP"
.br
.ti -1c
.RI "struct \fBSyncPrivate\fP"
.br
.ti -1c
.RI "struct \fBSyncRootStats\fP"
.br
.ti -1c
.RI "struct \fBSyncRootDeltas\fP"
.br
.ti -1c
.RI "struct \fBSyncRootPrivate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Part of CCNx Sync. 


.PP
Definition in file \fBSyncPrivate.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.
