sync_plumbing_sync_methods
NAME
sync_plumbing_sync_methods -
SYNOPSIS
Data Fields
int(* sync_start )(struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
int(* sync_notify )(struct sync_plumbing *sd, struct ccn_charbuf *name, int enum_index, uint64_t seq_num)
void(* sync_stop )(struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
Detailed Description
Definition at line 57 of file sync_plumbing.h.
Field Documentation
int(* sync_plumbing_sync_methods::sync_notify)(struct sync_plumbing *sd, struct ccn_charbuf *name, int enum_index, uint64_t seq_num)
Definition at line 74 of file sync_plumbing.h.
Referenced by r_sync_notify_content().
int(* sync_plumbing_sync_methods::sync_start)(struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
Definition at line 63 of file sync_plumbing.h.
Referenced by ccns_open(), r_init_create(), and sync_start_for_actions().
void(* sync_plumbing_sync_methods::sync_stop)(struct sync_plumbing *sd, struct ccn_charbuf *state_buf)
Definition at line 81 of file sync_plumbing.h.
Referenced by ccns_close(), r_init_destroy(), sync_stop_for_actions(), and SyncFreeBase().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.