sync/SyncNode.c
NAME
sync/SyncNode.c -
Part of CCNx Sync.
SYNOPSIS
Functions
int SyncSetCompErr (struct SyncNodeComposite *nc, int val)
Sets the error field when there is a processing error.
int SyncCheckCompErr (struct SyncNodeComposite *nc)
Tests the error field for an error returns 0 for no error != 0 for an error).
struct ccn_buf_decoder * SyncInitDecoderFromOffset (struct ccn_buf_decoder *d, struct SyncNodeComposite *nc, ssize_t start, ssize_t stop)
Makes a decoder from an offset range using the node charbuf.
struct ccn_buf_decoder * SyncInitDecoderFromElem (struct ccn_buf_decoder *d, struct SyncNodeComposite *nc, struct SyncNodeElem *ep)
Makes a decoder from an element.
void SyncNodeIncRC (struct SyncNodeComposite *nc)
Increments the reference count.
struct SyncNodeComposite * SyncNodeDecRC (struct SyncNodeComposite *nc)
Decrements the reference count.
enum SyncCompareResult SyncNodeCompareMinMax (struct SyncNodeComposite *nc, struct ccn_charbuf *name)
Compares a name against the min and max names in the node.
enum SyncCompareResult SyncNodeCompareLeaf (struct SyncNodeComposite *nc, struct SyncNodeElem *ep, struct ccn_charbuf *name)
Compares a name against the leaf in the element.
void SyncResetComposite (struct SyncNodeComposite *nc)
resets a composite node to its initial state except that it retains any allocated storage
struct SyncNodeComposite * SyncAllocComposite (struct SyncBaseStruct *base)
allocates a new, empty, composite object
void SyncExtendComposite (struct SyncNodeComposite *nc, SyncElemKind kind, ssize_t start, ssize_t stop)
extends the references section of a composite object with a new offset pair useful if NOT using SyncNodeAddName and SyncNodeAddNode
void SyncNodeMaintainMinMax (struct SyncNodeComposite *nc, const struct ccn_charbuf *name)
maintains the minName and maxName bounds useful if NOT using SyncNodeAddName and SyncNodeAddNode
void SyncNodeAddName (struct SyncNodeComposite *nc, const struct ccn_charbuf *name)
extends the references section of a composite object with a new name, updating the composite fields (including the name bounds) the names MUST be added in sorted order!
void SyncNodeAddNode (struct SyncNodeComposite *nc, struct SyncNodeComposite *node)
extends the references section of a composite object with a new node, updating the composite fields (including the name bounds) the nodes MUST be added in sorted order!
int SyncNodeAppendLongHash (struct ccn_charbuf *cb, struct SyncNodeComposite *nc)
appends the ccnb encoding for the long hash of nc to cb
void SyncEndComposite (struct SyncNodeComposite *nc)
endComposite finishes up the encoding, appending the composite fields the hash field will be valid after this call
void SyncFreeComposite (struct SyncNodeComposite *nc)
freeComposite returns the storage for the composite object
void SyncWriteComposite (struct SyncNodeComposite *nc, FILE *f)
writes the encoding to a file (primarily useful for test and debug code)
int SyncParseComposite (struct SyncNodeComposite *nc, struct ccn_buf_decoder *d)
parses an encoded node and fills in the supplied node implicitly resets the node at the start of the parse
struct SyncNodeComposite * SyncNodeFromBytes (struct SyncRootStruct *root, const unsigned char *cp, size_t cs)
struct SyncNodeComposite * SyncNodeFromParsedObject (struct SyncRootStruct *root, const unsigned char *msg, struct ccn_parsed_ContentObject *pco)
struct SyncNodeComposite * SyncNodeFromInfo (struct SyncRootStruct *root, struct ccn_upcall_info *info)
Detailed Description
Part of CCNx Sync.
Definition in file SyncNode.c.
Function Documentation
struct SyncNodeComposite* SyncAllocComposite (struct SyncBaseStruct * base) [read]
allocates a new, empty, composite object
Definition at line 157 of file SyncNode.c.
Referenced by extractNode(), MakeNodeFromNames(), node_from_names(), node_from_nodes(), nodeFromNodes(), SyncCacheEntryFetch(), SyncNodeFromBytes(), testEncodeDecode(), and testGenComposite().
int SyncCheckCompErr (struct SyncNodeComposite * nc)
Tests the error field for an error returns 0 for no error != 0 for an error).
Definition at line 38 of file SyncNode.c.
Referenced by SyncEndComposite(), and SyncParseComposite().
void SyncEndComposite (struct SyncNodeComposite * nc)
endComposite finishes up the encoding, appending the composite fields the hash field will be valid after this call
Definition at line 262 of file SyncNode.c.
Referenced by MakeNodeFromNames(), node_from_names(), node_from_nodes(), nodeFromNodes(), and testGenComposite().
void SyncExtendComposite (struct SyncNodeComposite * nc, SyncElemKind kind, ssize_t start, ssize_t stop)
extends the references section of a composite object with a new offset pair useful if NOT using SyncNodeAddName and SyncNodeAddNode
Definition at line 168 of file SyncNode.c.
Referenced by SyncNodeAddName(), SyncNodeAddNode(), and SyncParseComposite().
void SyncFreeComposite (struct SyncNodeComposite * nc)
freeComposite returns the storage for the composite object
Definition at line 291 of file SyncNode.c.
Referenced by extractNode(), newNodeCommon(), SyncCacheEntryFetch(), SyncNodeDecRC(), SyncNodeFromBytes(), and testEncodeDecode().
struct ccn_buf_decoder* SyncInitDecoderFromElem (struct ccn_buf_decoder * d, struct SyncNodeComposite * nc, struct SyncNodeElem * ep) [read]
Makes a decoder from an element.
Definition at line 54 of file SyncNode.c.
Referenced by extractBuf().
struct ccn_buf_decoder* SyncInitDecoderFromOffset (struct ccn_buf_decoder * d, struct SyncNodeComposite * nc, ssize_t start, ssize_t stop) [read]
Makes a decoder from an offset range using the node charbuf.
Definition at line 43 of file SyncNode.c.
Referenced by cacheEntryForElem(), printTreeInner(), SyncNodeCompareLeaf(), SyncTreeGenerateNames(), and SyncTreeWorkerPush().
void SyncNodeAddName (struct SyncNodeComposite * nc, const struct ccn_charbuf * name)
extends the references section of a composite object with a new name, updating the composite fields (including the name bounds) the names MUST be added in sorted order!
Definition at line 217 of file SyncNode.c.
Referenced by MakeNodeFromNames(), node_from_names(), and testGenComposite().
void SyncNodeAddNode (struct SyncNodeComposite * nc, struct SyncNodeComposite * node)
extends the references section of a composite object with a new node, updating the composite fields (including the name bounds) the nodes MUST be added in sorted order!
Definition at line 230 of file SyncNode.c.
Referenced by node_from_nodes(), and nodeFromNodes().
int SyncNodeAppendLongHash (struct ccn_charbuf * cb, struct SyncNodeComposite * nc)
appends the ccnb encoding for the long hash of nc to cb
Definition at line 249 of file SyncNode.c.
Referenced by SyncEndComposite(), and SyncNodeAddNode().
enum SyncCompareResult SyncNodeCompareLeaf (struct SyncNodeComposite * nc, struct SyncNodeElem * ep, struct ccn_charbuf * name)
Compares a name against the leaf in the element.
Definition at line 100 of file SyncNode.c.
Referenced by merge_names(), SyncTreeLookupName(), and SyncTreeMergeNames().
enum SyncCompareResult SyncNodeCompareMinMax (struct SyncNodeComposite * nc, struct ccn_charbuf * name)
Compares a name against the min and max names in the node.
Definition at line 85 of file SyncNode.c.
Referenced by BuildTree(), doComparison(), and SyncTreeLookupName().
struct SyncNodeComposite* SyncNodeDecRC (struct SyncNodeComposite * nc) [read]
Decrements the reference count. Returns:
nc if the resulting count is > 0.
NULL if the resulting count == 0 (and frees the node).
Definition at line 69 of file SyncNode.c.
Referenced by localFreeEntry(), my_response(), newNodeCommon(), and purgeOldEntries().
struct SyncNodeComposite* SyncNodeFromBytes (struct SyncRootStruct * root, const unsigned char * cp, size_t cs) [read]
Definition at line 440 of file SyncNode.c.
Referenced by SyncNodeFromParsedObject().
struct SyncNodeComposite* SyncNodeFromInfo (struct SyncRootStruct * root, struct ccn_upcall_info * info) [read]
Definition at line 469 of file SyncNode.c.
struct SyncNodeComposite* SyncNodeFromParsedObject (struct SyncRootStruct * root, const unsigned char * msg, struct ccn_parsed_ContentObject * pco) [read]
Definition at line 454 of file SyncNode.c.
Referenced by start_node_fetch(), and SyncNodeFromInfo().
void SyncNodeIncRC (struct SyncNodeComposite * nc)
Increments the reference count.
Definition at line 63 of file SyncNode.c.
Referenced by MakeNodeFromNames(), my_response(), newNodeCommon(), node_from_names(), SyncCacheEntryFetch(), SyncRemoteFetchResponse(), and SyncRootAdviseResponse().
void SyncNodeMaintainMinMax (struct SyncNodeComposite * nc, const struct ccn_charbuf * name)
maintains the minName and maxName bounds useful if NOT using SyncNodeAddName and SyncNodeAddNode
Definition at line 194 of file SyncNode.c.
Referenced by SyncNodeAddName(), and SyncNodeAddNode().
int SyncParseComposite (struct SyncNodeComposite * nc, struct ccn_buf_decoder * d)
parses an encoded node and fills in the supplied node implicitly resets the node at the start of the parse Returns:
nc->err
Definition at line 310 of file SyncNode.c.
Referenced by extractNode(), SyncCacheEntryFetch(), SyncNodeFromBytes(), and testEncodeDecode().
void SyncResetComposite (struct SyncNodeComposite * nc)
resets a composite node to its initial state except that it retains any allocated storage
Definition at line 128 of file SyncNode.c.
Referenced by SyncAllocComposite(), SyncFreeComposite(), and SyncParseComposite().
int SyncSetCompErr (struct SyncNodeComposite * nc, int val)
Sets the error field when there is a processing error.
Definition at line 31 of file SyncNode.c.
Referenced by SyncEndComposite(), and SyncParseComposite().
void SyncWriteComposite (struct SyncNodeComposite * nc, FILE * f)
writes the encoding to a file (primarily useful for test and debug code)
Definition at line 304 of file SyncNode.c.
Referenced by testEncodeDecode(), and testReadBuilder().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.