sync/UpdateSketch.c
NAME
sync/UpdateSketch.c -
Part of CCNx Sync.
SYNOPSIS
Functions
void UpdateAddName (struct SyncUpdateData *ud, struct ccn_charbuf *name)
struct SyncNodeComposite * CacheEntryFetch (struct SyncUpdateData *ud, struct SyncHashCacheEntry *ce)
struct ccn_charbuf * BestName (struct SyncUpdateData *ud)
int AdvanceName (struct SyncUpdateData *ud)
int AcceptNode (struct SyncUpdateData *ud)
int BuildTree (struct SyncUpdateData *ud, struct SyncTreeWorkerHead *tw, struct SyncNameAccum *src)
Detailed Description
Part of CCNx Sync.
This library is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License version 2.1 as published by the Free Software Foundation. This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more details. You should have received a copy of the GNU Lesser General Public License along with this library; if not, write to the Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
Definition in file UpdateSketch.c.
Function Documentation
int AcceptNode (struct SyncUpdateData * ud)
Definition at line 75 of file UpdateSketch.c.
Referenced by BuildTree().
int AdvanceName (struct SyncUpdateData * ud)
Definition at line 56 of file UpdateSketch.c.
Referenced by BuildTree().
struct ccn_charbuf* BestName (struct SyncUpdateData * ud) [read]
Definition at line 41 of file UpdateSketch.c.
Referenced by AdvanceName(), and BuildTree().
int BuildTree (struct SyncUpdateData * ud, struct SyncTreeWorkerHead * tw, struct SyncNameAccum * src)
Definition at line 82 of file UpdateSketch.c.
struct SyncNodeComposite* CacheEntryFetch (struct SyncUpdateData * ud, struct SyncHashCacheEntry * ce) [read]
Definition at line 24 of file UpdateSketch.c.
Referenced by BuildTree().
void UpdateAddName (struct SyncUpdateData * ud, struct ccn_charbuf * name)
Definition at line 19 of file UpdateSketch.c.
Referenced by BuildTree().
Author
Generated automatically by Doxygen for Content-Centric Networking in C from the source code.